"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.account_holder_capability import (
    AccountHolderCapability,
)
from adyen.models.contact_details import ContactDetails
from adyen.models.verification_deadline import (
    VerificationDeadline,
)


class AccountHolderUpdateRequest(object):
    """Implementation of the 'AccountHolderUpdateRequest' model.

    Attributes:
        balance_platform (str): The unique identifier of the [balance
            platform](https://docs.adyen.com/api-explorer/#/balanceplatform/latest/get
            /balancePlatforms/{id}__queryParam_id) to which the account holder
            belongs. Required in the request if your API credentials can be used for
            multiple balance platforms.
        capabilities (Dict[str, AccountHolderCapability]): Contains key-value pairs
            that specify the actions that an account holder can do in your platform.
            The key is a capability required for your integration. For example,
            **issueCard** for Issuing. The value is an object containing the settings
            for the capability.
        contact_details (ContactDetails): The model property of type ContactDetails.
        description (str): Your description for the account holder.
        metadata (Dict[str, str]): A set of key and value pairs for general use. The
            keys do not have specific names and may be used for storing miscellaneous
            data as desired. > Note that during an update of metadata, the omission
            of existing key-value pairs will result in the deletion of those
            key-value pairs.
        migrated_account_holder_code (str): The unique identifier of the migrated
            account holder in the classic integration.
        primary_balance_account (str): The ID of the account holder's primary balance
            account. By default, this is set to the first balance account that you
            create for the account holder. To assign a different balance account,
            send a PATCH request.
        reference (str): Your reference for the account holder.
        status (Status5): The model property of type Status5.
        time_zone (str): The time zone of the account holder. For example,
            **Europe/Amsterdam**. Defaults to the time zone of the balance platform
            if no time zone is set. For possible values, see the [list of time zone
            codes](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).
        verification_deadlines (List[VerificationDeadline]): List of verification
            deadlines and the capabilities that will be disallowed if verification
            errors are not resolved.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "balance_platform": "balancePlatform",
        "capabilities": "capabilities",
        "contact_details": "contactDetails",
        "description": "description",
        "metadata": "metadata",
        "migrated_account_holder_code": "migratedAccountHolderCode",
        "primary_balance_account": "primaryBalanceAccount",
        "reference": "reference",
        "status": "status",
        "time_zone": "timeZone",
        "verification_deadlines": "verificationDeadlines",
    }

    _optionals = [
        "balance_platform",
        "capabilities",
        "contact_details",
        "description",
        "metadata",
        "migrated_account_holder_code",
        "primary_balance_account",
        "reference",
        "status",
        "time_zone",
        "verification_deadlines",
    ]

    def __init__(
        self,
        balance_platform=APIHelper.SKIP,
        capabilities=APIHelper.SKIP,
        contact_details=APIHelper.SKIP,
        description=APIHelper.SKIP,
        metadata=APIHelper.SKIP,
        migrated_account_holder_code=APIHelper.SKIP,
        primary_balance_account=APIHelper.SKIP,
        reference=APIHelper.SKIP,
        status=APIHelper.SKIP,
        time_zone=APIHelper.SKIP,
        verification_deadlines=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AccountHolderUpdateRequest instance."""
        # Initialize members of the class
        if balance_platform is not APIHelper.SKIP:
            self.balance_platform = balance_platform
        if capabilities is not APIHelper.SKIP:
            self.capabilities = capabilities
        if contact_details is not APIHelper.SKIP:
            self.contact_details = contact_details
        if description is not APIHelper.SKIP:
            self.description = description
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata
        if migrated_account_holder_code is not APIHelper.SKIP:
            self.migrated_account_holder_code = migrated_account_holder_code
        if primary_balance_account is not APIHelper.SKIP:
            self.primary_balance_account = primary_balance_account
        if reference is not APIHelper.SKIP:
            self.reference = reference
        if status is not APIHelper.SKIP:
            self.status = status
        if time_zone is not APIHelper.SKIP:
            self.time_zone = time_zone
        if verification_deadlines is not APIHelper.SKIP:
            self.verification_deadlines = verification_deadlines

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        balance_platform =\
            dictionary.get("balancePlatform")\
            if dictionary.get("balancePlatform")\
                else APIHelper.SKIP
        capabilities =\
            AccountHolderCapability.from_dictionary(
                dictionary.get("capabilities"))\
                if "capabilities" in dictionary.keys()\
                else APIHelper.SKIP
        contact_details =\
            ContactDetails.from_dictionary(
                dictionary.get("contactDetails"))\
                if "contactDetails" in dictionary.keys()\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else APIHelper.SKIP
        migrated_account_holder_code =\
            dictionary.get("migratedAccountHolderCode")\
            if dictionary.get("migratedAccountHolderCode")\
                else APIHelper.SKIP
        primary_balance_account =\
            dictionary.get("primaryBalanceAccount")\
            if dictionary.get("primaryBalanceAccount")\
                else APIHelper.SKIP
        reference =\
            dictionary.get("reference")\
            if dictionary.get("reference")\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP
        time_zone =\
            dictionary.get("timeZone")\
            if dictionary.get("timeZone")\
                else APIHelper.SKIP
        verification_deadlines = None
        if dictionary.get("verificationDeadlines") is not None:
            verification_deadlines = [
                VerificationDeadline.from_dictionary(x)
                    for x in dictionary.get("verificationDeadlines")
            ]
        else:
            verification_deadlines = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(balance_platform,
                   capabilities,
                   contact_details,
                   description,
                   metadata,
                   migrated_account_holder_code,
                   primary_balance_account,
                   reference,
                   status,
                   time_zone,
                   verification_deadlines,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _balance_platform=(
            self.balance_platform
            if hasattr(self, "balance_platform")
            else None
        )
        _capabilities=(
            self.capabilities
            if hasattr(self, "capabilities")
            else None
        )
        _contact_details=(
            self.contact_details
            if hasattr(self, "contact_details")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _migrated_account_holder_code=(
            self.migrated_account_holder_code
            if hasattr(self, "migrated_account_holder_code")
            else None
        )
        _primary_balance_account=(
            self.primary_balance_account
            if hasattr(self, "primary_balance_account")
            else None
        )
        _reference=(
            self.reference
            if hasattr(self, "reference")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _time_zone=(
            self.time_zone
            if hasattr(self, "time_zone")
            else None
        )
        _verification_deadlines=(
            self.verification_deadlines
            if hasattr(self, "verification_deadlines")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"balance_platform={_balance_platform!r}, "
            f"capabilities={_capabilities!r}, "
            f"contact_details={_contact_details!r}, "
            f"description={_description!r}, "
            f"metadata={_metadata!r}, "
            f"migrated_account_holder_code={_migrated_account_holder_code!r}, "
            f"primary_balance_account={_primary_balance_account!r}, "
            f"reference={_reference!r}, "
            f"status={_status!r}, "
            f"time_zone={_time_zone!r}, "
            f"verification_deadlines={_verification_deadlines!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _balance_platform=(
            self.balance_platform
            if hasattr(self, "balance_platform")
            else None
        )
        _capabilities=(
            self.capabilities
            if hasattr(self, "capabilities")
            else None
        )
        _contact_details=(
            self.contact_details
            if hasattr(self, "contact_details")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _migrated_account_holder_code=(
            self.migrated_account_holder_code
            if hasattr(self, "migrated_account_holder_code")
            else None
        )
        _primary_balance_account=(
            self.primary_balance_account
            if hasattr(self, "primary_balance_account")
            else None
        )
        _reference=(
            self.reference
            if hasattr(self, "reference")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _time_zone=(
            self.time_zone
            if hasattr(self, "time_zone")
            else None
        )
        _verification_deadlines=(
            self.verification_deadlines
            if hasattr(self, "verification_deadlines")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"balance_platform={_balance_platform!s}, "
            f"capabilities={_capabilities!s}, "
            f"contact_details={_contact_details!s}, "
            f"description={_description!s}, "
            f"metadata={_metadata!s}, "
            f"migrated_account_holder_code={_migrated_account_holder_code!s}, "
            f"primary_balance_account={_primary_balance_account!s}, "
            f"reference={_reference!s}, "
            f"status={_status!s}, "
            f"time_zone={_time_zone!s}, "
            f"verification_deadlines={_verification_deadlines!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
