"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.account_supporting_entity_capability import (
    AccountSupportingEntityCapability,
)
from adyen.models.capability_problem import (
    CapabilityProblem,
)
from adyen.models.capability_settings_1 import (
    CapabilitySettings1,
)
from adyen.models.capability_settings_3 import (
    CapabilitySettings3,
)


class AccountHolderCapability(object):
    """Implementation of the 'AccountHolderCapability' model.

    Attributes:
        allowed (bool): Indicates whether the capability is allowed. Adyen sets this
            to **true** if the verification is successful and the account holder is
            permitted to use the capability.
        allowed_level (AllowedLevelEnum): The capability level that is allowed for
            the account holder.  Possible values: **notApplicable**, **low**,
            **medium**, **high**.
        allowed_settings (CapabilitySettings3): A JSON object containing the settings
            that are allowed for the account holder.
        enabled (bool): Indicates whether the capability is enabled. If **false**,
            the capability is temporarily disabled for the account holder.
        problems (List[CapabilityProblem]): Contains verification errors and the
            actions that you can take to resolve them.
        requested (bool): Indicates whether the capability is requested. To check
            whether the account holder is permitted to use the capability, refer to
            the `allowed` field.
        requested_level (RequestedLevelEnum): The requested level of the capability.
            Some capabilities, such as those used in [card
            issuing](https://docs.adyen.com/issuing/add-capabilities#capability-levels
            ), have different levels. Levels increase the capability, but also
            require additional checks and increased monitoring.  Possible values:
            **notApplicable**, **low**, **medium**, **high**.
        requested_settings (CapabilitySettings1): A JSON object containing the
            settings that were requested for the account holder.
        transfer_instruments (List[AccountSupportingEntityCapability]): Contains the
            status of the transfer instruments associated with this capability.
        verification_status (VerificationStatusEnum): The status of the verification
            checks for the capability.  Possible values:  * **pending**: Adyen is
            running the verification.  * **invalid**: The verification failed. Check
            if the `errors` array contains more information.  * **valid**: The
            verification has been successfully completed.  * **rejected**: Adyen has
            verified the information, but found reasons to not allow the capability.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "allowed": "allowed",
        "allowed_level": "allowedLevel",
        "allowed_settings": "allowedSettings",
        "enabled": "enabled",
        "problems": "problems",
        "requested": "requested",
        "requested_level": "requestedLevel",
        "requested_settings": "requestedSettings",
        "transfer_instruments": "transferInstruments",
        "verification_status": "verificationStatus",
    }

    _optionals = [
        "allowed",
        "allowed_level",
        "allowed_settings",
        "enabled",
        "problems",
        "requested",
        "requested_level",
        "requested_settings",
        "transfer_instruments",
        "verification_status",
    ]

    def __init__(
        self,
        allowed=APIHelper.SKIP,
        allowed_level=APIHelper.SKIP,
        allowed_settings=APIHelper.SKIP,
        enabled=APIHelper.SKIP,
        problems=APIHelper.SKIP,
        requested=APIHelper.SKIP,
        requested_level=APIHelper.SKIP,
        requested_settings=APIHelper.SKIP,
        transfer_instruments=APIHelper.SKIP,
        verification_status=APIHelper.SKIP):
        """Initialize a AccountHolderCapability instance."""
        # Initialize members of the class
        if allowed is not APIHelper.SKIP:
            self.allowed = allowed
        if allowed_level is not APIHelper.SKIP:
            self.allowed_level = allowed_level
        if allowed_settings is not APIHelper.SKIP:
            self.allowed_settings = allowed_settings
        if enabled is not APIHelper.SKIP:
            self.enabled = enabled
        if problems is not APIHelper.SKIP:
            self.problems = problems
        if requested is not APIHelper.SKIP:
            self.requested = requested
        if requested_level is not APIHelper.SKIP:
            self.requested_level = requested_level
        if requested_settings is not APIHelper.SKIP:
            self.requested_settings = requested_settings
        if transfer_instruments is not APIHelper.SKIP:
            self.transfer_instruments = transfer_instruments
        if verification_status is not APIHelper.SKIP:
            self.verification_status = verification_status

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        allowed =\
            dictionary.get("allowed")\
            if "allowed" in dictionary.keys()\
                else APIHelper.SKIP
        allowed_level =\
            dictionary.get("allowedLevel")\
            if dictionary.get("allowedLevel")\
                else APIHelper.SKIP
        allowed_settings =\
            CapabilitySettings3.from_dictionary(
                dictionary.get("allowedSettings"))\
                if "allowedSettings" in dictionary.keys()\
                else APIHelper.SKIP
        enabled =\
            dictionary.get("enabled")\
            if "enabled" in dictionary.keys()\
                else APIHelper.SKIP
        problems = None
        if dictionary.get("problems") is not None:
            problems = [
                CapabilityProblem.from_dictionary(x)
                    for x in dictionary.get("problems")
            ]
        else:
            problems = APIHelper.SKIP
        requested =\
            dictionary.get("requested")\
            if "requested" in dictionary.keys()\
                else APIHelper.SKIP
        requested_level =\
            dictionary.get("requestedLevel")\
            if dictionary.get("requestedLevel")\
                else APIHelper.SKIP
        requested_settings =\
            CapabilitySettings1.from_dictionary(
                dictionary.get("requestedSettings"))\
                if "requestedSettings" in dictionary.keys()\
                else APIHelper.SKIP
        transfer_instruments = None
        if dictionary.get("transferInstruments") is not None:
            transfer_instruments = [
                AccountSupportingEntityCapability.from_dictionary(x)
                    for x in dictionary.get("transferInstruments")
            ]
        else:
            transfer_instruments = APIHelper.SKIP
        verification_status =\
            dictionary.get("verificationStatus")\
            if dictionary.get("verificationStatus")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(allowed,
                   allowed_level,
                   allowed_settings,
                   enabled,
                   problems,
                   requested,
                   requested_level,
                   requested_settings,
                   transfer_instruments,
                   verification_status)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _allowed=(
            self.allowed
            if hasattr(self, "allowed")
            else None
        )
        _allowed_level=(
            self.allowed_level
            if hasattr(self, "allowed_level")
            else None
        )
        _allowed_settings=(
            self.allowed_settings
            if hasattr(self, "allowed_settings")
            else None
        )
        _enabled=(
            self.enabled
            if hasattr(self, "enabled")
            else None
        )
        _problems=(
            self.problems
            if hasattr(self, "problems")
            else None
        )
        _requested=(
            self.requested
            if hasattr(self, "requested")
            else None
        )
        _requested_level=(
            self.requested_level
            if hasattr(self, "requested_level")
            else None
        )
        _requested_settings=(
            self.requested_settings
            if hasattr(self, "requested_settings")
            else None
        )
        _transfer_instruments=(
            self.transfer_instruments
            if hasattr(self, "transfer_instruments")
            else None
        )
        _verification_status=(
            self.verification_status
            if hasattr(self, "verification_status")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"allowed={_allowed!r}, "
            f"allowed_level={_allowed_level!r}, "
            f"allowed_settings={_allowed_settings!r}, "
            f"enabled={_enabled!r}, "
            f"problems={_problems!r}, "
            f"requested={_requested!r}, "
            f"requested_level={_requested_level!r}, "
            f"requested_settings={_requested_settings!r}, "
            f"transfer_instruments={_transfer_instruments!r}, "
            f"verification_status={_verification_status!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _allowed=(
            self.allowed
            if hasattr(self, "allowed")
            else None
        )
        _allowed_level=(
            self.allowed_level
            if hasattr(self, "allowed_level")
            else None
        )
        _allowed_settings=(
            self.allowed_settings
            if hasattr(self, "allowed_settings")
            else None
        )
        _enabled=(
            self.enabled
            if hasattr(self, "enabled")
            else None
        )
        _problems=(
            self.problems
            if hasattr(self, "problems")
            else None
        )
        _requested=(
            self.requested
            if hasattr(self, "requested")
            else None
        )
        _requested_level=(
            self.requested_level
            if hasattr(self, "requested_level")
            else None
        )
        _requested_settings=(
            self.requested_settings
            if hasattr(self, "requested_settings")
            else None
        )
        _transfer_instruments=(
            self.transfer_instruments
            if hasattr(self, "transfer_instruments")
            else None
        )
        _verification_status=(
            self.verification_status
            if hasattr(self, "verification_status")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"allowed={_allowed!s}, "
            f"allowed_level={_allowed_level!s}, "
            f"allowed_settings={_allowed_settings!s}, "
            f"enabled={_enabled!s}, "
            f"problems={_problems!s}, "
            f"requested={_requested!s}, "
            f"requested_level={_requested_level!s}, "
            f"requested_settings={_requested_settings!s}, "
            f"transfer_instruments={_transfer_instruments!s}, "
            f"verification_status={_verification_status!s}, "
            f")"
        )
