"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class AccountIdentification(object):
    """Implementation of the 'AccountIdentification' model.

    Attributes:
        mtype (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
    }

    _optionals = [
        "mtype",
    ]

    def __init__(
        self,
        mtype="AccountIdentification",
        additional_properties=None):
        """Initialize a AccountIdentification instance."""
        # Initialize members of the class
        self.mtype = mtype

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        discriminators = {
            "iban": IbanAccountIdentification.from_dictionary,
        }
        unboxer = discriminators.get(dictionary.get("type"))

        # Delegate unboxing to another function if a discriminator
        # value for a child class is present.
        if unboxer:
            return unboxer(dictionary)

        # Extract variables from the dictionary
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else "AccountIdentification"

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(mtype,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )

class IbanAccountIdentification(AccountIdentification):
    """Implementation of the 'IbanAccountIdentification' model.
    NOTE: This class inherits from 'AccountIdentification'.

    Attributes:
        iban (str): The IBAN of the bank account.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "iban": "iban",
        "mtype": "type",
    }

    def __init__(
        self,
        iban=None,
        mtype="iban",
        additional_properties=None):
        """Initialize a IbanAccountIdentification instance."""
        # Initialize members of the class
        self.iban = iban

        # Call the constructor for the base class
        super(IbanAccountIdentification, self).__init__(
            mtype,
            additional_properties)

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        iban =\
            dictionary.get("iban")\
            if dictionary.get("iban")\
                else None
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else "iban"

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(iban,
                   mtype,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _iban=self.iban
        _base_repr = super().__repr__()
        _base_repr = _base_repr[_base_repr.find("(") + 1:-1]
        return (
            f"{self.__class__.__name__}("
            f"base_repr={_base_repr!r}, "
            f"iban={_iban!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _iban=self.iban
        _base_str = super().__str__()
        _base_str = _base_str[_base_str.find("(") + 1:-1]
        return (
            f"{self.__class__.__name__}("
            f"base_str={_base_str!s}, "
            f"iban={_iban!s}, "
            f")"
        )
