"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.payout_limit import PayoutLimit


class AccountPayoutState(object):
    """Implementation of the 'AccountPayoutState' model.

    Attributes:
        allow_payout (bool): Indicates whether payouts are allowed. This field is the
            overarching payout status, and is the aggregate of multiple conditions
            (e.g., KYC status, disabled flag, etc). If this field is false, no
            payouts will be permitted for any of the account holder's accounts. If
            this field is true, payouts will be permitted for any of the account
            holder's accounts.
        disable_reason (str): The reason why payouts (to all of the account holder's
            accounts) have been disabled (by the platform). If the `disabled` field
            is true, this field can be used to explain why.
        disabled (bool): Indicates whether payouts have been disabled (by the
            platform) for all of the account holder's accounts. A platform may enable
            and disable this field at their discretion. If this field is true,
            `allowPayout` will be false and no payouts will be permitted for any of
            the account holder's accounts. If this field is false, `allowPayout` may
            or may not be enabled, depending on other factors.
        not_allowed_reason (str): The reason why payouts (to all of the account
            holder's accounts) have been disabled (by Adyen). If payouts have been
            disabled by Adyen, this field will explain why. If this field is blank,
            payouts have not been disabled by Adyen.
        payout_limit (PayoutLimit): The model property of type PayoutLimit.
        tier_number (int): The payout tier that the account holder occupies.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "allow_payout": "allowPayout",
        "disable_reason": "disableReason",
        "disabled": "disabled",
        "not_allowed_reason": "notAllowedReason",
        "payout_limit": "payoutLimit",
        "tier_number": "tierNumber",
    }

    _optionals = [
        "allow_payout",
        "disable_reason",
        "disabled",
        "not_allowed_reason",
        "payout_limit",
        "tier_number",
    ]

    def __init__(
        self,
        allow_payout=APIHelper.SKIP,
        disable_reason=APIHelper.SKIP,
        disabled=APIHelper.SKIP,
        not_allowed_reason=APIHelper.SKIP,
        payout_limit=APIHelper.SKIP,
        tier_number=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AccountPayoutState instance."""
        # Initialize members of the class
        if allow_payout is not APIHelper.SKIP:
            self.allow_payout = allow_payout
        if disable_reason is not APIHelper.SKIP:
            self.disable_reason = disable_reason
        if disabled is not APIHelper.SKIP:
            self.disabled = disabled
        if not_allowed_reason is not APIHelper.SKIP:
            self.not_allowed_reason = not_allowed_reason
        if payout_limit is not APIHelper.SKIP:
            self.payout_limit = payout_limit
        if tier_number is not APIHelper.SKIP:
            self.tier_number = tier_number

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        allow_payout =\
            dictionary.get("allowPayout")\
            if "allowPayout" in dictionary.keys()\
                else APIHelper.SKIP
        disable_reason =\
            dictionary.get("disableReason")\
            if dictionary.get("disableReason")\
                else APIHelper.SKIP
        disabled =\
            dictionary.get("disabled")\
            if "disabled" in dictionary.keys()\
                else APIHelper.SKIP
        not_allowed_reason =\
            dictionary.get("notAllowedReason")\
            if dictionary.get("notAllowedReason")\
                else APIHelper.SKIP
        payout_limit =\
            PayoutLimit.from_dictionary(
                dictionary.get("payoutLimit"))\
                if "payoutLimit" in dictionary.keys()\
                else APIHelper.SKIP
        tier_number =\
            dictionary.get("tierNumber")\
            if dictionary.get("tierNumber")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(allow_payout,
                   disable_reason,
                   disabled,
                   not_allowed_reason,
                   payout_limit,
                   tier_number,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _allow_payout=(
            self.allow_payout
            if hasattr(self, "allow_payout")
            else None
        )
        _disable_reason=(
            self.disable_reason
            if hasattr(self, "disable_reason")
            else None
        )
        _disabled=(
            self.disabled
            if hasattr(self, "disabled")
            else None
        )
        _not_allowed_reason=(
            self.not_allowed_reason
            if hasattr(self, "not_allowed_reason")
            else None
        )
        _payout_limit=(
            self.payout_limit
            if hasattr(self, "payout_limit")
            else None
        )
        _tier_number=(
            self.tier_number
            if hasattr(self, "tier_number")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"allow_payout={_allow_payout!r}, "
            f"disable_reason={_disable_reason!r}, "
            f"disabled={_disabled!r}, "
            f"not_allowed_reason={_not_allowed_reason!r}, "
            f"payout_limit={_payout_limit!r}, "
            f"tier_number={_tier_number!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _allow_payout=(
            self.allow_payout
            if hasattr(self, "allow_payout")
            else None
        )
        _disable_reason=(
            self.disable_reason
            if hasattr(self, "disable_reason")
            else None
        )
        _disabled=(
            self.disabled
            if hasattr(self, "disabled")
            else None
        )
        _not_allowed_reason=(
            self.not_allowed_reason
            if hasattr(self, "not_allowed_reason")
            else None
        )
        _payout_limit=(
            self.payout_limit
            if hasattr(self, "payout_limit")
            else None
        )
        _tier_number=(
            self.tier_number
            if hasattr(self, "tier_number")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"allow_payout={_allow_payout!s}, "
            f"disable_reason={_disable_reason!s}, "
            f"disabled={_disabled!s}, "
            f"not_allowed_reason={_not_allowed_reason!s}, "
            f"payout_limit={_payout_limit!s}, "
            f"tier_number={_tier_number!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
