"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.account_transaction_list import (
    AccountTransactionList,
)
from adyen.models.error_field_type import ErrorFieldType


class AccountHolderTransactionListResponse(object):
    """Implementation of the 'AccountHolderTransactionListResponse' model.

    Attributes:
        account_transaction_lists (List[AccountTransactionList]): A list of the
            transactions.
        invalid_fields (List[ErrorFieldType]): Contains field validation errors that
            would prevent requests from being processed.
        psp_reference (str): The reference of a request. Can be used to uniquely
            identify the request.
        result_code (str): The result code.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_transaction_lists": "accountTransactionLists",
        "invalid_fields": "invalidFields",
        "psp_reference": "pspReference",
        "result_code": "resultCode",
    }

    _optionals = [
        "account_transaction_lists",
        "invalid_fields",
        "psp_reference",
        "result_code",
    ]

    def __init__(
        self,
        account_transaction_lists=APIHelper.SKIP,
        invalid_fields=APIHelper.SKIP,
        psp_reference=APIHelper.SKIP,
        result_code=APIHelper.SKIP):
        """Initialize a AccountHolderTransactionListResponse instance."""
        # Initialize members of the class
        if account_transaction_lists is not APIHelper.SKIP:
            self.account_transaction_lists = account_transaction_lists
        if invalid_fields is not APIHelper.SKIP:
            self.invalid_fields = invalid_fields
        if psp_reference is not APIHelper.SKIP:
            self.psp_reference = psp_reference
        if result_code is not APIHelper.SKIP:
            self.result_code = result_code

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_transaction_lists = None
        if dictionary.get("accountTransactionLists") is not None:
            account_transaction_lists = [
                AccountTransactionList.from_dictionary(x)
                    for x in dictionary.get("accountTransactionLists")
            ]
        else:
            account_transaction_lists = APIHelper.SKIP
        invalid_fields = None
        if dictionary.get("invalidFields") is not None:
            invalid_fields = [
                ErrorFieldType.from_dictionary(x)
                    for x in dictionary.get("invalidFields")
            ]
        else:
            invalid_fields = APIHelper.SKIP
        psp_reference =\
            dictionary.get("pspReference")\
            if dictionary.get("pspReference")\
                else APIHelper.SKIP
        result_code =\
            dictionary.get("resultCode")\
            if dictionary.get("resultCode")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(account_transaction_lists,
                   invalid_fields,
                   psp_reference,
                   result_code)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_transaction_lists=(
            self.account_transaction_lists
            if hasattr(self, "account_transaction_lists")
            else None
        )
        _invalid_fields=(
            self.invalid_fields
            if hasattr(self, "invalid_fields")
            else None
        )
        _psp_reference=(
            self.psp_reference
            if hasattr(self, "psp_reference")
            else None
        )
        _result_code=(
            self.result_code
            if hasattr(self, "result_code")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_transaction_lists={_account_transaction_lists!r}, "
            f"invalid_fields={_invalid_fields!r}, "
            f"psp_reference={_psp_reference!r}, "
            f"result_code={_result_code!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_transaction_lists=(
            self.account_transaction_lists
            if hasattr(self, "account_transaction_lists")
            else None
        )
        _invalid_fields=(
            self.invalid_fields
            if hasattr(self, "invalid_fields")
            else None
        )
        _psp_reference=(
            self.psp_reference
            if hasattr(self, "psp_reference")
            else None
        )
        _result_code=(
            self.result_code
            if hasattr(self, "result_code")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_transaction_lists={_account_transaction_lists!s}, "
            f"invalid_fields={_invalid_fields!s}, "
            f"psp_reference={_psp_reference!s}, "
            f"result_code={_result_code!s}, "
            f")"
        )
