"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class Action1(object):
    """Implementation of the 'Action1' model.

    Attributes:
        action_code (str): The code identifying the action that needs to be completed.
        resolved (bool): Indicates whether this action has been successfully
            completed.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "action_code": "actionCode",
        "resolved": "resolved",
    }

    def __init__(
        self,
        action_code=None,
        resolved=None):
        """Initialize a Action1 instance."""
        # Initialize members of the class
        self.action_code = action_code
        self.resolved = resolved

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        action_code =\
            dictionary.get("actionCode")\
            if dictionary.get("actionCode")\
                else None
        resolved =\
            dictionary.get("resolved")\
            if "resolved" in dictionary.keys()\
                else None

        # Return an object of this model
        return cls(action_code,
                   resolved)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _action_code=self.action_code
        _resolved=self.resolved
        return (
            f"{self.__class__.__name__}("
            f"action_code={_action_code!r}, "
            f"resolved={_resolved!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _action_code=self.action_code
        _resolved=self.resolved
        return (
            f"{self.__class__.__name__}("
            f"action_code={_action_code!s}, "
            f"resolved={_resolved!s}, "
            f")"
        )
