"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class AdditionalDataRiskStandalone(object):
    """Implementation of the 'AdditionalDataRiskStandalone' model.

    Attributes:
        pay_pal_country_code (str): Shopper's country of residence in the form of ISO
            standard 3166 2-character country codes.
        pay_pal_email_id (str): Shopper's email.
        pay_pal_first_name (str): Shopper's first name.
        pay_pal_last_name (str): Shopper's last name.
        pay_pal_payer_id (str): Unique PayPal Customer Account identification number.
            Character length and limitations: 13 single-byte alphanumeric characters.
        pay_pal_phone (str): Shopper's phone number.
        pay_pal_protection_eligibility (str): Allowed values: * **Eligible** —
            Merchant is protected by PayPal's Seller Protection Policy for
            Unauthorized Payments and Item Not Received.  * **PartiallyEligible** —
            Merchant is protected by PayPal's Seller Protection Policy for Item Not
            Received.  * **Ineligible** — Merchant is not protected under the Seller
            Protection Policy.
        pay_pal_transaction_id (str): Unique transaction ID of the payment.
        avs_result_raw (str): Raw AVS result received from the acquirer, where
            available. Example: D
        bin (str): The Bank Identification Number of a credit card, which is the
            first six digits of a card number. Required for [tokenized card
            request](https://docs.adyen.com/online-payments/tokenization).
        cvc_result_raw (str): Raw CVC result received from the acquirer, where
            available. Example: 1
        risk_token (str): Unique identifier or token for the shopper's card details.
        three_d_authenticated (str): A Boolean value indicating whether 3DS
            authentication was completed on this payment. Example: true
        three_d_offered (str): A Boolean value indicating whether 3DS was offered for
            this payment. Example: true
        token_data_type (str): Required for PayPal payments only. The only supported
            value is: **paypal**.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "pay_pal_country_code": "PayPal.CountryCode",
        "pay_pal_email_id": "PayPal.EmailId",
        "pay_pal_first_name": "PayPal.FirstName",
        "pay_pal_last_name": "PayPal.LastName",
        "pay_pal_payer_id": "PayPal.PayerId",
        "pay_pal_phone": "PayPal.Phone",
        "pay_pal_protection_eligibility": "PayPal.ProtectionEligibility",
        "pay_pal_transaction_id": "PayPal.TransactionId",
        "avs_result_raw": "avsResultRaw",
        "bin": "bin",
        "cvc_result_raw": "cvcResultRaw",
        "risk_token": "riskToken",
        "three_d_authenticated": "threeDAuthenticated",
        "three_d_offered": "threeDOffered",
        "token_data_type": "tokenDataType",
    }

    _optionals = [
        "pay_pal_country_code",
        "pay_pal_email_id",
        "pay_pal_first_name",
        "pay_pal_last_name",
        "pay_pal_payer_id",
        "pay_pal_phone",
        "pay_pal_protection_eligibility",
        "pay_pal_transaction_id",
        "avs_result_raw",
        "bin",
        "cvc_result_raw",
        "risk_token",
        "three_d_authenticated",
        "three_d_offered",
        "token_data_type",
    ]

    def __init__(
        self,
        pay_pal_country_code=APIHelper.SKIP,
        pay_pal_email_id=APIHelper.SKIP,
        pay_pal_first_name=APIHelper.SKIP,
        pay_pal_last_name=APIHelper.SKIP,
        pay_pal_payer_id=APIHelper.SKIP,
        pay_pal_phone=APIHelper.SKIP,
        pay_pal_protection_eligibility=APIHelper.SKIP,
        pay_pal_transaction_id=APIHelper.SKIP,
        avs_result_raw=APIHelper.SKIP,
        bin=APIHelper.SKIP,
        cvc_result_raw=APIHelper.SKIP,
        risk_token=APIHelper.SKIP,
        three_d_authenticated=APIHelper.SKIP,
        three_d_offered=APIHelper.SKIP,
        token_data_type=APIHelper.SKIP):
        """Initialize a AdditionalDataRiskStandalone instance."""
        # Initialize members of the class
        if pay_pal_country_code is not APIHelper.SKIP:
            self.pay_pal_country_code = pay_pal_country_code
        if pay_pal_email_id is not APIHelper.SKIP:
            self.pay_pal_email_id = pay_pal_email_id
        if pay_pal_first_name is not APIHelper.SKIP:
            self.pay_pal_first_name = pay_pal_first_name
        if pay_pal_last_name is not APIHelper.SKIP:
            self.pay_pal_last_name = pay_pal_last_name
        if pay_pal_payer_id is not APIHelper.SKIP:
            self.pay_pal_payer_id = pay_pal_payer_id
        if pay_pal_phone is not APIHelper.SKIP:
            self.pay_pal_phone = pay_pal_phone
        if pay_pal_protection_eligibility is not APIHelper.SKIP:
            self.pay_pal_protection_eligibility = pay_pal_protection_eligibility
        if pay_pal_transaction_id is not APIHelper.SKIP:
            self.pay_pal_transaction_id = pay_pal_transaction_id
        if avs_result_raw is not APIHelper.SKIP:
            self.avs_result_raw = avs_result_raw
        if bin is not APIHelper.SKIP:
            self.bin = bin
        if cvc_result_raw is not APIHelper.SKIP:
            self.cvc_result_raw = cvc_result_raw
        if risk_token is not APIHelper.SKIP:
            self.risk_token = risk_token
        if three_d_authenticated is not APIHelper.SKIP:
            self.three_d_authenticated = three_d_authenticated
        if three_d_offered is not APIHelper.SKIP:
            self.three_d_offered = three_d_offered
        if token_data_type is not APIHelper.SKIP:
            self.token_data_type = token_data_type

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        pay_pal_country_code =\
            dictionary.get("PayPal.CountryCode")\
            if dictionary.get("PayPal.CountryCode")\
                else APIHelper.SKIP
        pay_pal_email_id =\
            dictionary.get("PayPal.EmailId")\
            if dictionary.get("PayPal.EmailId")\
                else APIHelper.SKIP
        pay_pal_first_name =\
            dictionary.get("PayPal.FirstName")\
            if dictionary.get("PayPal.FirstName")\
                else APIHelper.SKIP
        pay_pal_last_name =\
            dictionary.get("PayPal.LastName")\
            if dictionary.get("PayPal.LastName")\
                else APIHelper.SKIP
        pay_pal_payer_id =\
            dictionary.get("PayPal.PayerId")\
            if dictionary.get("PayPal.PayerId")\
                else APIHelper.SKIP
        pay_pal_phone =\
            dictionary.get("PayPal.Phone")\
            if dictionary.get("PayPal.Phone")\
                else APIHelper.SKIP
        pay_pal_protection_eligibility =\
            dictionary.get("PayPal.ProtectionEligibility")\
            if dictionary.get("PayPal.ProtectionEligibility")\
                else APIHelper.SKIP
        pay_pal_transaction_id =\
            dictionary.get("PayPal.TransactionId")\
            if dictionary.get("PayPal.TransactionId")\
                else APIHelper.SKIP
        avs_result_raw =\
            dictionary.get("avsResultRaw")\
            if dictionary.get("avsResultRaw")\
                else APIHelper.SKIP
        bin =\
            dictionary.get("bin")\
            if dictionary.get("bin")\
                else APIHelper.SKIP
        cvc_result_raw =\
            dictionary.get("cvcResultRaw")\
            if dictionary.get("cvcResultRaw")\
                else APIHelper.SKIP
        risk_token =\
            dictionary.get("riskToken")\
            if dictionary.get("riskToken")\
                else APIHelper.SKIP
        three_d_authenticated =\
            dictionary.get("threeDAuthenticated")\
            if dictionary.get("threeDAuthenticated")\
                else APIHelper.SKIP
        three_d_offered =\
            dictionary.get("threeDOffered")\
            if dictionary.get("threeDOffered")\
                else APIHelper.SKIP
        token_data_type =\
            dictionary.get("tokenDataType")\
            if dictionary.get("tokenDataType")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(pay_pal_country_code,
                   pay_pal_email_id,
                   pay_pal_first_name,
                   pay_pal_last_name,
                   pay_pal_payer_id,
                   pay_pal_phone,
                   pay_pal_protection_eligibility,
                   pay_pal_transaction_id,
                   avs_result_raw,
                   bin,
                   cvc_result_raw,
                   risk_token,
                   three_d_authenticated,
                   three_d_offered,
                   token_data_type)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _pay_pal_country_code=(
            self.pay_pal_country_code
            if hasattr(self, "pay_pal_country_code")
            else None
        )
        _pay_pal_email_id=(
            self.pay_pal_email_id
            if hasattr(self, "pay_pal_email_id")
            else None
        )
        _pay_pal_first_name=(
            self.pay_pal_first_name
            if hasattr(self, "pay_pal_first_name")
            else None
        )
        _pay_pal_last_name=(
            self.pay_pal_last_name
            if hasattr(self, "pay_pal_last_name")
            else None
        )
        _pay_pal_payer_id=(
            self.pay_pal_payer_id
            if hasattr(self, "pay_pal_payer_id")
            else None
        )
        _pay_pal_phone=(
            self.pay_pal_phone
            if hasattr(self, "pay_pal_phone")
            else None
        )
        _pay_pal_protection_eligibility=(
            self.pay_pal_protection_eligibility
            if hasattr(self, "pay_pal_protection_eligibility")
            else None
        )
        _pay_pal_transaction_id=(
            self.pay_pal_transaction_id
            if hasattr(self, "pay_pal_transaction_id")
            else None
        )
        _avs_result_raw=(
            self.avs_result_raw
            if hasattr(self, "avs_result_raw")
            else None
        )
        _bin=(
            self.bin
            if hasattr(self, "bin")
            else None
        )
        _cvc_result_raw=(
            self.cvc_result_raw
            if hasattr(self, "cvc_result_raw")
            else None
        )
        _risk_token=(
            self.risk_token
            if hasattr(self, "risk_token")
            else None
        )
        _three_d_authenticated=(
            self.three_d_authenticated
            if hasattr(self, "three_d_authenticated")
            else None
        )
        _three_d_offered=(
            self.three_d_offered
            if hasattr(self, "three_d_offered")
            else None
        )
        _token_data_type=(
            self.token_data_type
            if hasattr(self, "token_data_type")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"pay_pal_country_code={_pay_pal_country_code!r}, "
            f"pay_pal_email_id={_pay_pal_email_id!r}, "
            f"pay_pal_first_name={_pay_pal_first_name!r}, "
            f"pay_pal_last_name={_pay_pal_last_name!r}, "
            f"pay_pal_payer_id={_pay_pal_payer_id!r}, "
            f"pay_pal_phone={_pay_pal_phone!r}, "
            f"pay_pal_protection_eligibility={_pay_pal_protection_eligibility!r}, "
            f"pay_pal_transaction_id={_pay_pal_transaction_id!r}, "
            f"avs_result_raw={_avs_result_raw!r}, "
            f"bin={_bin!r}, "
            f"cvc_result_raw={_cvc_result_raw!r}, "
            f"risk_token={_risk_token!r}, "
            f"three_d_authenticated={_three_d_authenticated!r}, "
            f"three_d_offered={_three_d_offered!r}, "
            f"token_data_type={_token_data_type!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _pay_pal_country_code=(
            self.pay_pal_country_code
            if hasattr(self, "pay_pal_country_code")
            else None
        )
        _pay_pal_email_id=(
            self.pay_pal_email_id
            if hasattr(self, "pay_pal_email_id")
            else None
        )
        _pay_pal_first_name=(
            self.pay_pal_first_name
            if hasattr(self, "pay_pal_first_name")
            else None
        )
        _pay_pal_last_name=(
            self.pay_pal_last_name
            if hasattr(self, "pay_pal_last_name")
            else None
        )
        _pay_pal_payer_id=(
            self.pay_pal_payer_id
            if hasattr(self, "pay_pal_payer_id")
            else None
        )
        _pay_pal_phone=(
            self.pay_pal_phone
            if hasattr(self, "pay_pal_phone")
            else None
        )
        _pay_pal_protection_eligibility=(
            self.pay_pal_protection_eligibility
            if hasattr(self, "pay_pal_protection_eligibility")
            else None
        )
        _pay_pal_transaction_id=(
            self.pay_pal_transaction_id
            if hasattr(self, "pay_pal_transaction_id")
            else None
        )
        _avs_result_raw=(
            self.avs_result_raw
            if hasattr(self, "avs_result_raw")
            else None
        )
        _bin=(
            self.bin
            if hasattr(self, "bin")
            else None
        )
        _cvc_result_raw=(
            self.cvc_result_raw
            if hasattr(self, "cvc_result_raw")
            else None
        )
        _risk_token=(
            self.risk_token
            if hasattr(self, "risk_token")
            else None
        )
        _three_d_authenticated=(
            self.three_d_authenticated
            if hasattr(self, "three_d_authenticated")
            else None
        )
        _three_d_offered=(
            self.three_d_offered
            if hasattr(self, "three_d_offered")
            else None
        )
        _token_data_type=(
            self.token_data_type
            if hasattr(self, "token_data_type")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"pay_pal_country_code={_pay_pal_country_code!s}, "
            f"pay_pal_email_id={_pay_pal_email_id!s}, "
            f"pay_pal_first_name={_pay_pal_first_name!s}, "
            f"pay_pal_last_name={_pay_pal_last_name!s}, "
            f"pay_pal_payer_id={_pay_pal_payer_id!s}, "
            f"pay_pal_phone={_pay_pal_phone!s}, "
            f"pay_pal_protection_eligibility={_pay_pal_protection_eligibility!s}, "
            f"pay_pal_transaction_id={_pay_pal_transaction_id!s}, "
            f"avs_result_raw={_avs_result_raw!s}, "
            f"bin={_bin!s}, "
            f"cvc_result_raw={_cvc_result_raw!s}, "
            f"risk_token={_risk_token!s}, "
            f"three_d_authenticated={_three_d_authenticated!s}, "
            f"three_d_offered={_three_d_offered!s}, "
            f"token_data_type={_token_data_type!s}, "
            f")"
        )
