"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.leg_1 import Leg1


class Airline11(object):
    """Implementation of the 'Airline11' model.

    Airline information.

    Attributes:
        legs (List[Leg1]): Details about the flight legs for this ticket.
        ticket_number (str): The ticket's unique identifier

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "legs": "legs",
        "ticket_number": "ticketNumber",
    }

    _optionals = [
        "legs",
        "ticket_number",
    ]

    def __init__(
        self,
        legs=APIHelper.SKIP,
        ticket_number=APIHelper.SKIP):
        """Initialize a Airline11 instance."""
        # Initialize members of the class
        if legs is not APIHelper.SKIP:
            self.legs = legs
        if ticket_number is not APIHelper.SKIP:
            self.ticket_number = ticket_number

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        legs = None
        if dictionary.get("legs") is not None:
            legs = [
                Leg1.from_dictionary(x)
                    for x in dictionary.get("legs")
            ]
        else:
            legs = APIHelper.SKIP
        ticket_number =\
            dictionary.get("ticketNumber")\
            if dictionary.get("ticketNumber")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(legs,
                   ticket_number)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _legs=(
            self.legs
            if hasattr(self, "legs")
            else None
        )
        _ticket_number=(
            self.ticket_number
            if hasattr(self, "ticket_number")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"legs={_legs!r}, "
            f"ticket_number={_ticket_number!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _legs=(
            self.legs
            if hasattr(self, "legs")
            else None
        )
        _ticket_number=(
            self.ticket_number
            if hasattr(self, "ticket_number")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"legs={_legs!s}, "
            f"ticket_number={_ticket_number!s}, "
            f")"
        )
