"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class Alma(object):
    """Implementation of the 'Alma' model.

    Attributes:
        checkout_attempt_id (str): The checkout attempt identifier.
        fee_type (FeeTypeEnum): **Alma payment request fee type**
        sdk_data (str): Base64-encoded JSON object containing SDK related parameters
            required by the SDK
        mtype (Type3Enum): The payment method type.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "checkout_attempt_id": "checkoutAttemptId",
        "fee_type": "feeType",
        "sdk_data": "sdkData",
        "mtype": "type",
    }

    _optionals = [
        "checkout_attempt_id",
        "fee_type",
        "sdk_data",
        "mtype",
    ]

    def __init__(
        self,
        checkout_attempt_id=APIHelper.SKIP,
        fee_type=APIHelper.SKIP,
        sdk_data=APIHelper.SKIP,
        mtype=APIHelper.SKIP):
        """Initialize a Alma instance."""
        # Initialize members of the class
        if checkout_attempt_id is not APIHelper.SKIP:
            self.checkout_attempt_id = checkout_attempt_id
        if fee_type is not APIHelper.SKIP:
            self.fee_type = fee_type
        if sdk_data is not APIHelper.SKIP:
            self.sdk_data = sdk_data
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        checkout_attempt_id =\
            dictionary.get("checkoutAttemptId")\
            if dictionary.get("checkoutAttemptId")\
                else APIHelper.SKIP
        fee_type =\
            dictionary.get("feeType")\
            if dictionary.get("feeType")\
                else APIHelper.SKIP
        sdk_data =\
            dictionary.get("sdkData")\
            if dictionary.get("sdkData")\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(checkout_attempt_id,
                   fee_type,
                   sdk_data,
                   mtype)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _checkout_attempt_id=(
            self.checkout_attempt_id
            if hasattr(self, "checkout_attempt_id")
            else None
        )
        _fee_type=(
            self.fee_type
            if hasattr(self, "fee_type")
            else None
        )
        _sdk_data=(
            self.sdk_data
            if hasattr(self, "sdk_data")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"checkout_attempt_id={_checkout_attempt_id!r}, "
            f"fee_type={_fee_type!r}, "
            f"sdk_data={_sdk_data!r}, "
            f"mtype={_mtype!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _checkout_attempt_id=(
            self.checkout_attempt_id
            if hasattr(self, "checkout_attempt_id")
            else None
        )
        _fee_type=(
            self.fee_type
            if hasattr(self, "fee_type")
            else None
        )
        _sdk_data=(
            self.sdk_data
            if hasattr(self, "sdk_data")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"checkout_attempt_id={_checkout_attempt_id!s}, "
            f"fee_type={_fee_type!s}, "
            f"sdk_data={_sdk_data!s}, "
            f"mtype={_mtype!s}, "
            f")"
        )
