"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class AndroidAppError(object):
    """Implementation of the 'AndroidAppError' model.

    Attributes:
        error_code (str): The error code of the Android app with the `status` of
            either **error** or **invalid**.
        terminal_models (List[str]): The list of payment terminal models to which the
            returned `errorCode` applies.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "error_code": "errorCode",
        "terminal_models": "terminalModels",
    }

    _optionals = [
        "error_code",
        "terminal_models",
    ]

    def __init__(
        self,
        error_code=APIHelper.SKIP,
        terminal_models=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AndroidAppError instance."""
        # Initialize members of the class
        if error_code is not APIHelper.SKIP:
            self.error_code = error_code
        if terminal_models is not APIHelper.SKIP:
            self.terminal_models = terminal_models

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        error_code =\
            dictionary.get("errorCode")\
            if dictionary.get("errorCode")\
                else APIHelper.SKIP
        terminal_models =\
            dictionary.get("terminalModels")\
            if dictionary.get("terminalModels")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(error_code,
                   terminal_models,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _error_code=(
            self.error_code
            if hasattr(self, "error_code")
            else None
        )
        _terminal_models=(
            self.terminal_models
            if hasattr(self, "terminal_models")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"error_code={_error_code!r}, "
            f"terminal_models={_terminal_models!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _error_code=(
            self.error_code
            if hasattr(self, "error_code")
            else None
        )
        _terminal_models=(
            self.terminal_models
            if hasattr(self, "terminal_models")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"error_code={_error_code!s}, "
            f"terminal_models={_terminal_models!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
