"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.three_ds_request_data import (
    ThreeDsRequestData,
)


class AuthenticationData(object):
    """Implementation of the 'AuthenticationData' model.

    Attributes:
        attempt_authentication (AttemptAuthentication): The model property of type
            AttemptAuthentication.
        authentication_only (bool): Required to trigger the [authentication-only
            flow](https://docs.adyen.com/online-payments/3d-secure/authentication-only
            /). If set to **true**, you will only perform the 3D Secure 2
            authentication, and will not proceed to the payment authorization.
            Default: **false**.
        three_ds_request_data (ThreeDsRequestData): The model property of type
            ThreeDsRequestData.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "attempt_authentication": "attemptAuthentication",
        "authentication_only": "authenticationOnly",
        "three_ds_request_data": "threeDSRequestData",
    }

    _optionals = [
        "attempt_authentication",
        "authentication_only",
        "three_ds_request_data",
    ]

    def __init__(
        self,
        attempt_authentication=APIHelper.SKIP,
        authentication_only=False,
        three_ds_request_data=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AuthenticationData instance."""
        # Initialize members of the class
        if attempt_authentication is not APIHelper.SKIP:
            self.attempt_authentication = attempt_authentication
        self.authentication_only = authentication_only
        if three_ds_request_data is not APIHelper.SKIP:
            self.three_ds_request_data = three_ds_request_data

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        attempt_authentication =\
            dictionary.get("attemptAuthentication")\
            if dictionary.get("attemptAuthentication")\
                else APIHelper.SKIP
        authentication_only =\
            dictionary.get("authenticationOnly")\
            if dictionary.get("authenticationOnly")\
                else False
        three_ds_request_data =\
            ThreeDsRequestData.from_dictionary(
                dictionary.get("threeDSRequestData"))\
                if "threeDSRequestData" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(attempt_authentication,
                   authentication_only,
                   three_ds_request_data,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _attempt_authentication=(
            self.attempt_authentication
            if hasattr(self, "attempt_authentication")
            else None
        )
        _authentication_only=(
            self.authentication_only
            if hasattr(self, "authentication_only")
            else None
        )
        _three_ds_request_data=(
            self.three_ds_request_data
            if hasattr(self, "three_ds_request_data")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"attempt_authentication={_attempt_authentication!r}, "
            f"authentication_only={_authentication_only!r}, "
            f"three_ds_request_data={_three_ds_request_data!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _attempt_authentication=(
            self.attempt_authentication
            if hasattr(self, "attempt_authentication")
            else None
        )
        _authentication_only=(
            self.authentication_only
            if hasattr(self, "authentication_only")
            else None
        )
        _three_ds_request_data=(
            self.three_ds_request_data
            if hasattr(self, "three_ds_request_data")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"attempt_authentication={_attempt_authentication!s}, "
            f"authentication_only={_authentication_only!s}, "
            f"three_ds_request_data={_three_ds_request_data!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
