"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.loyalty_account_req_2 import (
    LoyaltyAccountReq2,
)
from adyen.models.payment_account_req_2 import (
    PaymentAccountReq2,
)


class BalanceInquiryRequest2(object):
    """Implementation of the 'BalanceInquiryRequest2' model.

    Content of the Balance Inquiry Request message.

    Attributes:
        payment_account_req (PaymentAccountReq2): Data related to the account pointed
            by the payment card.
        loyalty_account_req (LoyaltyAccountReq2): Data related to a requested Loyalty
            program or account.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "payment_account_req": "PaymentAccountReq",
        "loyalty_account_req": "LoyaltyAccountReq",
    }

    _optionals = [
        "payment_account_req",
        "loyalty_account_req",
    ]

    def __init__(
        self,
        payment_account_req=APIHelper.SKIP,
        loyalty_account_req=APIHelper.SKIP):
        """Initialize a BalanceInquiryRequest2 instance."""
        # Initialize members of the class
        if payment_account_req is not APIHelper.SKIP:
            self.payment_account_req = payment_account_req
        if loyalty_account_req is not APIHelper.SKIP:
            self.loyalty_account_req = loyalty_account_req

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        payment_account_req =\
            PaymentAccountReq2.from_dictionary(
                dictionary.get("PaymentAccountReq"))\
                if "PaymentAccountReq" in dictionary.keys()\
                else APIHelper.SKIP
        loyalty_account_req =\
            LoyaltyAccountReq2.from_dictionary(
                dictionary.get("LoyaltyAccountReq"))\
                if "LoyaltyAccountReq" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(payment_account_req,
                   loyalty_account_req)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _payment_account_req=(
            self.payment_account_req
            if hasattr(self, "payment_account_req")
            else None
        )
        _loyalty_account_req=(
            self.loyalty_account_req
            if hasattr(self, "loyalty_account_req")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"payment_account_req={_payment_account_req!r}, "
            f"loyalty_account_req={_loyalty_account_req!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _payment_account_req=(
            self.payment_account_req
            if hasattr(self, "payment_account_req")
            else None
        )
        _loyalty_account_req=(
            self.loyalty_account_req
            if hasattr(self, "loyalty_account_req")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"payment_account_req={_payment_account_req!s}, "
            f"loyalty_account_req={_loyalty_account_req!s}, "
            f")"
        )
