"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.payment_account_status_2 import (
    PaymentAccountStatus2,
)
from adyen.models.payment_receipt import PaymentReceipt
from adyen.models.response_11 import Response11


class BalanceInquiryResponse2(object):
    """Implementation of the 'BalanceInquiryResponse2' model.

    Content of the Balance Inquiry Response message.

    Attributes:
        response (Response11): Result of a message request processing.
        payment_account_status (PaymentAccountStatus2): Data related to the result of
            a Balance Inquiry request. If BalanceInquiryRequest. PaymentAccount
            present.
        payment_receipt (List[PaymentReceipt]): The model property of type
            List[PaymentReceipt].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "response": "Response",
        "payment_account_status": "PaymentAccountStatus",
        "payment_receipt": "PaymentReceipt",
    }

    _optionals = [
        "payment_account_status",
        "payment_receipt",
    ]

    def __init__(
        self,
        response=None,
        payment_account_status=APIHelper.SKIP,
        payment_receipt=APIHelper.SKIP):
        """Initialize a BalanceInquiryResponse2 instance."""
        # Initialize members of the class
        self.response = response
        if payment_account_status is not APIHelper.SKIP:
            self.payment_account_status = payment_account_status
        if payment_receipt is not APIHelper.SKIP:
            self.payment_receipt = payment_receipt

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        response =\
            Response11.from_dictionary(
                dictionary.get("Response"))\
                if dictionary.get("Response") else None
        payment_account_status =\
            PaymentAccountStatus2.from_dictionary(
                dictionary.get("PaymentAccountStatus"))\
                if "PaymentAccountStatus" in dictionary.keys()\
                else APIHelper.SKIP
        payment_receipt = None
        if dictionary.get("PaymentReceipt") is not None:
            payment_receipt = [
                PaymentReceipt.from_dictionary(x)
                    for x in dictionary.get("PaymentReceipt")
            ]
        else:
            payment_receipt = APIHelper.SKIP

        # Return an object of this model
        return cls(response,
                   payment_account_status,
                   payment_receipt)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _response=self.response
        _payment_account_status=(
            self.payment_account_status
            if hasattr(self, "payment_account_status")
            else None
        )
        _payment_receipt=(
            self.payment_receipt
            if hasattr(self, "payment_receipt")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"response={_response!r}, "
            f"payment_account_status={_payment_account_status!r}, "
            f"payment_receipt={_payment_receipt!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _response=self.response
        _payment_account_status=(
            self.payment_account_status
            if hasattr(self, "payment_account_status")
            else None
        )
        _payment_receipt=(
            self.payment_receipt
            if hasattr(self, "payment_receipt")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"response={_response!s}, "
            f"payment_account_status={_payment_account_status!s}, "
            f"payment_receipt={_payment_receipt!s}, "
            f")"
        )
