"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.sca_device import ScaDevice


class BeginScaDeviceRegistrationResponse(object):
    """Implementation of the 'BeginScaDeviceRegistrationResponse' model.

    Attributes:
        sca_device (ScaDevice): A resource that contains information about a device,
            including its unique ID, name, and type.
        sdk_input (str): A string that you must pass to the authentication SDK to
            continue with the registration process.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "sca_device": "scaDevice",
        "sdk_input": "sdkInput",
    }

    _optionals = [
        "sca_device",
        "sdk_input",
    ]

    def __init__(
        self,
        sca_device=APIHelper.SKIP,
        sdk_input=APIHelper.SKIP):
        """Initialize a BeginScaDeviceRegistrationResponse instance."""
        # Initialize members of the class
        if sca_device is not APIHelper.SKIP:
            self.sca_device = sca_device
        if sdk_input is not APIHelper.SKIP:
            self.sdk_input = sdk_input

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        sca_device =\
            ScaDevice.from_dictionary(
                dictionary.get("scaDevice"))\
                if "scaDevice" in dictionary.keys()\
                else APIHelper.SKIP
        sdk_input =\
            dictionary.get("sdkInput")\
            if dictionary.get("sdkInput")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(sca_device,
                   sdk_input)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _sca_device=(
            self.sca_device
            if hasattr(self, "sca_device")
            else None
        )
        _sdk_input=(
            self.sdk_input
            if hasattr(self, "sdk_input")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"sca_device={_sca_device!r}, "
            f"sdk_input={_sdk_input!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _sca_device=(
            self.sca_device
            if hasattr(self, "sca_device")
            else None
        )
        _sdk_input=(
            self.sdk_input
            if hasattr(self, "sdk_input")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"sca_device={_sca_device!s}, "
            f"sdk_input={_sdk_input!s}, "
            f")"
        )
