"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.address_6 import Address6


class BillingEntity(object):
    """Implementation of the 'BillingEntity' model.

    Attributes:
        address (Address6): The model property of type Address6.
        email (str): The email address of the billing entity.
        id (str): The unique identifier of the billing entity, for use as
            `billingEntityId` when creating an order.
        name (str): The unique name of the billing entity.
        tax_id (str): The tax number of the billing entity.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "address": "address",
        "email": "email",
        "id": "id",
        "name": "name",
        "tax_id": "taxId",
    }

    _optionals = [
        "address",
        "email",
        "id",
        "name",
        "tax_id",
    ]

    def __init__(
        self,
        address=APIHelper.SKIP,
        email=APIHelper.SKIP,
        id=APIHelper.SKIP,
        name=APIHelper.SKIP,
        tax_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a BillingEntity instance."""
        # Initialize members of the class
        if address is not APIHelper.SKIP:
            self.address = address
        if email is not APIHelper.SKIP:
            self.email = email
        if id is not APIHelper.SKIP:
            self.id = id
        if name is not APIHelper.SKIP:
            self.name = name
        if tax_id is not APIHelper.SKIP:
            self.tax_id = tax_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        address =\
            Address6.from_dictionary(
                dictionary.get("address"))\
                if "address" in dictionary.keys()\
                else APIHelper.SKIP
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        tax_id =\
            dictionary.get("taxId")\
            if dictionary.get("taxId")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(address,
                   email,
                   id,
                   name,
                   tax_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _tax_id=(
            self.tax_id
            if hasattr(self, "tax_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"address={_address!r}, "
            f"email={_email!r}, "
            f"id={_id!r}, "
            f"name={_name!r}, "
            f"tax_id={_tax_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _tax_id=(
            self.tax_id
            if hasattr(self, "tax_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"address={_address!s}, "
            f"email={_email!s}, "
            f"id={_id!s}, "
            f"name={_name!s}, "
            f"tax_id={_tax_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
