"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class BillingAddress(object):
    """Implementation of the 'BillingAddress' model.

    Attributes:
        city (str): The name of the city. Maximum length: 3000 characters.
        country (str): The two-character ISO-3166-1 alpha-2 country code. For
            example, **US**. > If you don't know the country or are not collecting
            the country from the shopper, provide `country` as `ZZ`.
        house_number_or_name (str): The number or name of the house. Maximum length:
            3000 characters.
        postal_code (str): A maximum of five digits for an address in the US, or a
            maximum of ten characters for an address in all other countries.
        state_or_province (str): The two-character ISO 3166-2 state or province code.
            For example, **CA** in the US or **ON** in Canada. > Required for the US
            and Canada.
        street (str): The name of the street. Maximum length: 3000 characters. > The
            house number should not be included in this field; it should be
            separately provided via `houseNumberOrName`.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "city": "city",
        "country": "country",
        "house_number_or_name": "houseNumberOrName",
        "postal_code": "postalCode",
        "street": "street",
        "state_or_province": "stateOrProvince",
    }

    _optionals = [
        "state_or_province",
    ]

    def __init__(
        self,
        city=None,
        country=None,
        house_number_or_name=None,
        postal_code=None,
        street=None,
        state_or_province=APIHelper.SKIP):
        """Initialize a BillingAddress instance."""
        # Initialize members of the class
        self.city = city
        self.country = country
        self.house_number_or_name = house_number_or_name
        self.postal_code = postal_code
        if state_or_province is not APIHelper.SKIP:
            self.state_or_province = state_or_province
        self.street = street

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        city =\
            dictionary.get("city")\
            if dictionary.get("city")\
                else None
        country =\
            dictionary.get("country")\
            if dictionary.get("country")\
                else None
        house_number_or_name =\
            dictionary.get("houseNumberOrName")\
            if dictionary.get("houseNumberOrName")\
                else None
        postal_code =\
            dictionary.get("postalCode")\
            if dictionary.get("postalCode")\
                else None
        street =\
            dictionary.get("street")\
            if dictionary.get("street")\
                else None
        state_or_province =\
            dictionary.get("stateOrProvince")\
            if dictionary.get("stateOrProvince")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(city,
                   country,
                   house_number_or_name,
                   postal_code,
                   street,
                   state_or_province)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _city=self.city
        _country=self.country
        _house_number_or_name=self.house_number_or_name
        _postal_code=self.postal_code
        _state_or_province=(
            self.state_or_province
            if hasattr(self, "state_or_province")
            else None
        )
        _street=self.street
        return (
            f"{self.__class__.__name__}("
            f"city={_city!r}, "
            f"country={_country!r}, "
            f"house_number_or_name={_house_number_or_name!r}, "
            f"postal_code={_postal_code!r}, "
            f"state_or_province={_state_or_province!r}, "
            f"street={_street!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _city=self.city
        _country=self.country
        _house_number_or_name=self.house_number_or_name
        _postal_code=self.postal_code
        _state_or_province=(
            self.state_or_province
            if hasattr(self, "state_or_province")
            else None
        )
        _street=self.street
        return (
            f"{self.__class__.__name__}("
            f"city={_city!s}, "
            f"country={_country!s}, "
            f"house_number_or_name={_house_number_or_name!s}, "
            f"postal_code={_postal_code!s}, "
            f"state_or_province={_state_or_province!s}, "
            f"street={_street!s}, "
            f")"
        )
