"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class BoardingTokenRequest(object):
    """Implementation of the 'BoardingTokenRequest' model.

    Attributes:
        boarding_request_token (str): The boardingToken request token.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "boarding_request_token": "boardingRequestToken",
    }

    def __init__(
        self,
        boarding_request_token=None,
        additional_properties=None):
        """Initialize a BoardingTokenRequest instance."""
        # Initialize members of the class
        self.boarding_request_token = boarding_request_token

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        boarding_request_token =\
            dictionary.get("boardingRequestToken")\
            if dictionary.get("boardingRequestToken")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(boarding_request_token,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _boarding_request_token=self.boarding_request_token
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"boarding_request_token={_boarding_request_token!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _boarding_request_token=self.boarding_request_token
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"boarding_request_token={_boarding_request_token!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
