"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class CapabilityProblemEntityRecursive2(object):
    """Implementation of the 'CapabilityProblemEntity-recursive2' model.

    Contains details about the owner of the entity that has an error.

    Attributes:
        documents (List[str]): List of document IDs to which the verification errors
            related to the capabilities correspond to.
        id (str): The ID of the entity.
        mtype (Type33Enum): Type of entity.   Possible values: **LegalEntity**,
            **BankAccount**, **Document**.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "documents": "documents",
        "id": "id",
        "mtype": "type",
    }

    _optionals = [
        "documents",
        "id",
        "mtype",
    ]

    def __init__(
        self,
        documents=APIHelper.SKIP,
        id=APIHelper.SKIP,
        mtype=APIHelper.SKIP):
        """Initialize a CapabilityProblemEntityRecursive2 instance."""
        # Initialize members of the class
        if documents is not APIHelper.SKIP:
            self.documents = documents
        if id is not APIHelper.SKIP:
            self.id = id
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        documents =\
            dictionary.get("documents")\
            if dictionary.get("documents")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(documents,
                   id,
                   mtype)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _documents=(
            self.documents
            if hasattr(self, "documents")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"documents={_documents!r}, "
            f"id={_id!r}, "
            f"mtype={_mtype!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _documents=(
            self.documents
            if hasattr(self, "documents")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"documents={_documents!s}, "
            f"id={_id!s}, "
            f"mtype={_mtype!s}, "
            f")"
        )
