"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class CardDetailsRequest(object):
    """Implementation of the 'CardDetailsRequest' model.

    Attributes:
        card_number (str): A minimum of the first six digits of the card number. The
            full card number gives the best result.   You must be [fully PCI
            compliant](https://docs.adyen.com/development-resources/pci-dss-compliance
            -guide) to collect raw card data. Alternatively, you can use the
            `encryptedCardNumber` field.
        country_code (str): The shopper country code.  Format: [ISO 3166-1
            alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) Example: NL or
            DE
        encrypted_card_number (str): The encrypted card number.
        merchant_account (str): The merchant account identifier, with which you want
            to process the transaction.
        supported_brands (List[str]): The card brands you support. This is the
            [`brands`](https://docs.adyen.com/api-explorer/Checkout/latest/post/paymen
            tMethods#responses-200-paymentMethods-brands) array from your
            [`/paymentMethods`](https://docs.adyen.com/api-explorer/#/CheckoutService/
            latest/post/paymentMethods) response.   If not included, our API uses the
            ones configured for your merchant account and, if provided, the country
            code.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "merchant_account": "merchantAccount",
        "card_number": "cardNumber",
        "country_code": "countryCode",
        "encrypted_card_number": "encryptedCardNumber",
        "supported_brands": "supportedBrands",
    }

    _optionals = [
        "card_number",
        "country_code",
        "encrypted_card_number",
        "supported_brands",
    ]

    def __init__(
        self,
        merchant_account=None,
        card_number=APIHelper.SKIP,
        country_code=APIHelper.SKIP,
        encrypted_card_number=APIHelper.SKIP,
        supported_brands=APIHelper.SKIP):
        """Initialize a CardDetailsRequest instance."""
        # Initialize members of the class
        if card_number is not APIHelper.SKIP:
            self.card_number = card_number
        if country_code is not APIHelper.SKIP:
            self.country_code = country_code
        if encrypted_card_number is not APIHelper.SKIP:
            self.encrypted_card_number = encrypted_card_number
        self.merchant_account = merchant_account
        if supported_brands is not APIHelper.SKIP:
            self.supported_brands = supported_brands

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        merchant_account =\
            dictionary.get("merchantAccount")\
            if dictionary.get("merchantAccount")\
                else None
        card_number =\
            dictionary.get("cardNumber")\
            if dictionary.get("cardNumber")\
                else APIHelper.SKIP
        country_code =\
            dictionary.get("countryCode")\
            if dictionary.get("countryCode")\
                else APIHelper.SKIP
        encrypted_card_number =\
            dictionary.get("encryptedCardNumber")\
            if dictionary.get("encryptedCardNumber")\
                else APIHelper.SKIP
        supported_brands =\
            dictionary.get("supportedBrands")\
            if dictionary.get("supportedBrands")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(merchant_account,
                   card_number,
                   country_code,
                   encrypted_card_number,
                   supported_brands)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _card_number=(
            self.card_number
            if hasattr(self, "card_number")
            else None
        )
        _country_code=(
            self.country_code
            if hasattr(self, "country_code")
            else None
        )
        _encrypted_card_number=(
            self.encrypted_card_number
            if hasattr(self, "encrypted_card_number")
            else None
        )
        _merchant_account=self.merchant_account
        _supported_brands=(
            self.supported_brands
            if hasattr(self, "supported_brands")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"card_number={_card_number!r}, "
            f"country_code={_country_code!r}, "
            f"encrypted_card_number={_encrypted_card_number!r}, "
            f"merchant_account={_merchant_account!r}, "
            f"supported_brands={_supported_brands!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _card_number=(
            self.card_number
            if hasattr(self, "card_number")
            else None
        )
        _country_code=(
            self.country_code
            if hasattr(self, "country_code")
            else None
        )
        _encrypted_card_number=(
            self.encrypted_card_number
            if hasattr(self, "encrypted_card_number")
            else None
        )
        _merchant_account=self.merchant_account
        _supported_brands=(
            self.supported_brands
            if hasattr(self, "supported_brands")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"card_number={_card_number!s}, "
            f"country_code={_country_code!s}, "
            f"encrypted_card_number={_encrypted_card_number!s}, "
            f"merchant_account={_merchant_account!s}, "
            f"supported_brands={_supported_brands!s}, "
            f")"
        )
