"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.sub_merchant_data_2 import (
    SubMerchantData2,
)


class CertificateLoadingRequest(object):
    """Implementation of the 'CertificateLoadingRequest' model.

    Attributes:
        merchant_account (str): The unique identifier of your merchant account.
        setup_token (str): The setup token provided by the SDK in a Mobile solution
            for in-person payments.  - When using the Android SDK, obtain the token
            through the `MerchantAuthenticationService.authenticate(setupToken)`
            callback of `AuthenticationService`.  - When using the iOS SDK, obtain
            the token through the `PaymentServiceDelegate.register(with:)` callback
            of `PaymentServiceDelegate`.
        store (str): The reference of the store that you want to process transactions
            for. Do not include this parameter if your account structure uses
            merchant accounts as stores, or if you are a registered payment
            facilitator.
        sub_merchant_data (SubMerchantData2): The model property of type
            SubMerchantData2.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "merchant_account": "merchantAccount",
        "setup_token": "setupToken",
        "store": "store",
        "sub_merchant_data": "subMerchantData",
    }

    _optionals = [
        "store",
        "sub_merchant_data",
    ]

    def __init__(
        self,
        merchant_account=None,
        setup_token=None,
        store=APIHelper.SKIP,
        sub_merchant_data=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CertificateLoadingRequest instance."""
        # Initialize members of the class
        self.merchant_account = merchant_account
        self.setup_token = setup_token
        if store is not APIHelper.SKIP:
            self.store = store
        if sub_merchant_data is not APIHelper.SKIP:
            self.sub_merchant_data = sub_merchant_data

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        merchant_account =\
            dictionary.get("merchantAccount")\
            if dictionary.get("merchantAccount")\
                else None
        setup_token =\
            dictionary.get("setupToken")\
            if dictionary.get("setupToken")\
                else None
        store =\
            dictionary.get("store")\
            if dictionary.get("store")\
                else APIHelper.SKIP
        sub_merchant_data =\
            SubMerchantData2.from_dictionary(
                dictionary.get("subMerchantData"))\
                if "subMerchantData" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(merchant_account,
                   setup_token,
                   store,
                   sub_merchant_data,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _merchant_account=self.merchant_account
        _setup_token=self.setup_token
        _store=(
            self.store
            if hasattr(self, "store")
            else None
        )
        _sub_merchant_data=(
            self.sub_merchant_data
            if hasattr(self, "sub_merchant_data")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"merchant_account={_merchant_account!r}, "
            f"setup_token={_setup_token!r}, "
            f"store={_store!r}, "
            f"sub_merchant_data={_sub_merchant_data!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _merchant_account=self.merchant_account
        _setup_token=self.setup_token
        _store=(
            self.store
            if hasattr(self, "store")
            else None
        )
        _sub_merchant_data=(
            self.sub_merchant_data
            if hasattr(self, "sub_merchant_data")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"merchant_account={_merchant_account!s}, "
            f"setup_token={_setup_token!s}, "
            f"store={_store!s}, "
            f"sub_merchant_data={_sub_merchant_data!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
