"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class CheckoutForwardResponseFromUrl(object):
    """Implementation of the 'CheckoutForwardResponseFromUrl' model.

    Attributes:
        body (str): The body of the response Adyen received from the third party, in
            string format.
        headers (Dict[str, str]): The HTTP headers of the response Adyen received
            from the third party.
        status (int): The HTTP status of the response Adyen received from the third
            party.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "body": "body",
        "headers": "headers",
        "status": "status",
    }

    _optionals = [
        "body",
        "headers",
        "status",
    ]

    def __init__(
        self,
        body=APIHelper.SKIP,
        headers=APIHelper.SKIP,
        status=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CheckoutForwardResponseFromUrl instance."""
        # Initialize members of the class
        if body is not APIHelper.SKIP:
            self.body = body
        if headers is not APIHelper.SKIP:
            self.headers = headers
        if status is not APIHelper.SKIP:
            self.status = status

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        body =\
            dictionary.get("body")\
            if dictionary.get("body")\
                else APIHelper.SKIP
        headers =\
            dictionary.get("headers")\
            if dictionary.get("headers")\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(body,
                   headers,
                   status,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _headers=(
            self.headers
            if hasattr(self, "headers")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"body={_body!r}, "
            f"headers={_headers!r}, "
            f"status={_status!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _headers=(
            self.headers
            if hasattr(self, "headers")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"body={_body!s}, "
            f"headers={_headers!s}, "
            f"status={_status!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
