"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.amount_11 import Amount11
from adyen.models.checkout_forward_request_card_2 import (
    CheckoutForwardRequestCard2,
)
from adyen.models.checkout_forward_request_options_2 import (
    CheckoutForwardRequestOptions2,
)
from adyen.models.checkout_outgoing_forward_request_2 import (
    CheckoutOutgoingForwardRequest2,
)


class CheckoutForwardRequest(object):
    """Implementation of the 'CheckoutForwardRequest' model.

    Attributes:
        amount (Amount11): The amount of the forwarded payment.
        base_url (str): The base URL of the third party API, where Adyen will send
            the request to forward the payment details.
        merchant_account (str): Your merchant account.
        merchant_reference (str): Merchant defined payment reference.
        options (CheckoutForwardRequestOptions2): The customizations that can be
            applied when making a forward request.
        payment_method (CheckoutForwardRequestCard2): The card details.
        request (CheckoutOutgoingForwardRequest2): The [details of the
            request](https://docs.adyen.com/online-payments/tokenization/forward-payme
            nt-details#request-to-adyen-card) that you want to forward to the
            third-party.
        shopper_reference (str): Your reference to uniquely identify this shopper,
            for example user ID or account ID. The value is case-sensitive and must
            be at least three characters. > Your reference must not include
            personally identifiable information (PII) such as name or email address.
        stored_payment_method_id (str): The unique identifier of the token that you
            want to forward to the third party. This is the `storedPaymentMethodId`
            you received in the webhook after you created the token.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "base_url": "baseUrl",
        "merchant_account": "merchantAccount",
        "request": "request",
        "shopper_reference": "shopperReference",
        "amount": "amount",
        "merchant_reference": "merchantReference",
        "options": "options",
        "payment_method": "paymentMethod",
        "stored_payment_method_id": "storedPaymentMethodId",
    }

    _optionals = [
        "amount",
        "merchant_reference",
        "options",
        "payment_method",
        "stored_payment_method_id",
    ]

    def __init__(
        self,
        base_url=None,
        merchant_account=None,
        request=None,
        shopper_reference=None,
        amount=APIHelper.SKIP,
        merchant_reference=APIHelper.SKIP,
        options=APIHelper.SKIP,
        payment_method=APIHelper.SKIP,
        stored_payment_method_id=APIHelper.SKIP):
        """Initialize a CheckoutForwardRequest instance."""
        # Initialize members of the class
        if amount is not APIHelper.SKIP:
            self.amount = amount
        self.base_url = base_url
        self.merchant_account = merchant_account
        if merchant_reference is not APIHelper.SKIP:
            self.merchant_reference = merchant_reference
        if options is not APIHelper.SKIP:
            self.options = options
        if payment_method is not APIHelper.SKIP:
            self.payment_method = payment_method
        self.request = request
        self.shopper_reference = shopper_reference
        if stored_payment_method_id is not APIHelper.SKIP:
            self.stored_payment_method_id = stored_payment_method_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        base_url =\
            dictionary.get("baseUrl")\
            if dictionary.get("baseUrl")\
                else None
        merchant_account =\
            dictionary.get("merchantAccount")\
            if dictionary.get("merchantAccount")\
                else None
        request =\
            CheckoutOutgoingForwardRequest2.from_dictionary(
                dictionary.get("request"))\
                if dictionary.get("request") else None
        shopper_reference =\
            dictionary.get("shopperReference")\
            if dictionary.get("shopperReference")\
                else None
        amount =\
            Amount11.from_dictionary(
                dictionary.get("amount"))\
                if "amount" in dictionary.keys()\
                else APIHelper.SKIP
        merchant_reference =\
            dictionary.get("merchantReference")\
            if dictionary.get("merchantReference")\
                else APIHelper.SKIP
        options =\
            CheckoutForwardRequestOptions2.from_dictionary(
                dictionary.get("options"))\
                if "options" in dictionary.keys()\
                else APIHelper.SKIP
        payment_method =\
            CheckoutForwardRequestCard2.from_dictionary(
                dictionary.get("paymentMethod"))\
                if "paymentMethod" in dictionary.keys()\
                else APIHelper.SKIP
        stored_payment_method_id =\
            dictionary.get("storedPaymentMethodId")\
            if dictionary.get("storedPaymentMethodId")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(base_url,
                   merchant_account,
                   request,
                   shopper_reference,
                   amount,
                   merchant_reference,
                   options,
                   payment_method,
                   stored_payment_method_id)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _base_url=self.base_url
        _merchant_account=self.merchant_account
        _merchant_reference=(
            self.merchant_reference
            if hasattr(self, "merchant_reference")
            else None
        )
        _options=(
            self.options
            if hasattr(self, "options")
            else None
        )
        _payment_method=(
            self.payment_method
            if hasattr(self, "payment_method")
            else None
        )
        _request=self.request
        _shopper_reference=self.shopper_reference
        _stored_payment_method_id=(
            self.stored_payment_method_id
            if hasattr(self, "stored_payment_method_id")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!r}, "
            f"base_url={_base_url!r}, "
            f"merchant_account={_merchant_account!r}, "
            f"merchant_reference={_merchant_reference!r}, "
            f"options={_options!r}, "
            f"payment_method={_payment_method!r}, "
            f"request={_request!r}, "
            f"shopper_reference={_shopper_reference!r}, "
            f"stored_payment_method_id={_stored_payment_method_id!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _base_url=self.base_url
        _merchant_account=self.merchant_account
        _merchant_reference=(
            self.merchant_reference
            if hasattr(self, "merchant_reference")
            else None
        )
        _options=(
            self.options
            if hasattr(self, "options")
            else None
        )
        _payment_method=(
            self.payment_method
            if hasattr(self, "payment_method")
            else None
        )
        _request=self.request
        _shopper_reference=self.shopper_reference
        _stored_payment_method_id=(
            self.stored_payment_method_id
            if hasattr(self, "stored_payment_method_id")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!s}, "
            f"base_url={_base_url!s}, "
            f"merchant_account={_merchant_account!s}, "
            f"merchant_reference={_merchant_reference!s}, "
            f"options={_options!s}, "
            f"payment_method={_payment_method!s}, "
            f"request={_request!s}, "
            f"shopper_reference={_shopper_reference!s}, "
            f"stored_payment_method_id={_stored_payment_method_id!s}, "
            f")"
        )
