"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class Condition(object):
    """Implementation of the 'Condition' model.

    Attributes:
        balance_type (BalanceTypeEnum): Define the type of balance about which you
            want to get notified. Possible values:  * **available**: the balance
            available for use.  * **balance**: the sum of transactions that have
            already been settled.  * **pending**: the sum of transactions that will
            be settled in the future.  * **reserved**: the balance currently held in
            reserve.
        condition_type (ConditionTypeEnum): Define when you want to get notified
            about a balance change. Possible values:  * **greaterThan**: the balance
            in the account(s) exceeds the specified `value`.  *
            **greaterThanOrEqual**: the balance in the account(s) reaches or exceeds
            the specified `value`.  * **lessThan**: the balance in the account(s)
            drops below the specified `value`.  * **lessThanOrEqual**: the balance in
            the account(s) reaches to drops below the specified `value`.
        value (int): The value limit in the specified balance type and currency, in
            minor units.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "balance_type": "balanceType",
        "condition_type": "conditionType",
        "value": "value",
    }

    def __init__(
        self,
        balance_type=None,
        condition_type=None,
        value=None):
        """Initialize a Condition instance."""
        # Initialize members of the class
        self.balance_type = balance_type
        self.condition_type = condition_type
        self.value = value

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        balance_type =\
            dictionary.get("balanceType")\
            if dictionary.get("balanceType")\
                else None
        condition_type =\
            dictionary.get("conditionType")\
            if dictionary.get("conditionType")\
                else None
        value =\
            dictionary.get("value")\
            if dictionary.get("value")\
                else None

        # Return an object of this model
        return cls(balance_type,
                   condition_type,
                   value)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _balance_type=self.balance_type
        _condition_type=self.condition_type
        _value=self.value
        return (
            f"{self.__class__.__name__}("
            f"balance_type={_balance_type!r}, "
            f"condition_type={_condition_type!r}, "
            f"value={_value!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _balance_type=self.balance_type
        _condition_type=self.condition_type
        _value=self.value
        return (
            f"{self.__class__.__name__}("
            f"balance_type={_balance_type!s}, "
            f"condition_type={_condition_type!s}, "
            f"value={_value!s}, "
            f")"
        )
