"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.currency import Currency


class Configuration(object):
    """Implementation of the 'Configuration' model.

    Attributes:
        brand (str): Payment method, like **eftpos_australia** or **mc**. See the
            [possible
            values](https://docs.adyen.com/development-resources/paymentmethodvariant#
            management-api).
        commercial (bool): Set to **true** to apply surcharges only to
            commercial/business cards.
        country (List[str]): The country/region of the card issuer. If used, the
            surcharge settings only apply to the card issued in that country/region.
        currencies (List[Currency]): Currency and percentage or amount of the
            surcharge.
        sources (List[str]): Funding source. Possible values: * **Credit** * **Debit**
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "brand": "brand",
        "currencies": "currencies",
        "commercial": "commercial",
        "country": "country",
        "sources": "sources",
    }

    _optionals = [
        "commercial",
        "country",
        "sources",
    ]

    def __init__(
        self,
        brand=None,
        currencies=None,
        commercial=APIHelper.SKIP,
        country=APIHelper.SKIP,
        sources=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Configuration instance."""
        # Initialize members of the class
        self.brand = brand
        if commercial is not APIHelper.SKIP:
            self.commercial = commercial
        if country is not APIHelper.SKIP:
            self.country = country
        self.currencies = currencies
        if sources is not APIHelper.SKIP:
            self.sources = sources

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        brand =\
            dictionary.get("brand")\
            if dictionary.get("brand")\
                else None
        currencies = None
        if dictionary.get("currencies") is not None:
            currencies = [
                Currency.from_dictionary(x)
                    for x in dictionary.get("currencies")
            ]
        commercial =\
            dictionary.get("commercial")\
            if "commercial" in dictionary.keys()\
                else APIHelper.SKIP
        country =\
            dictionary.get("country")\
            if dictionary.get("country")\
                else APIHelper.SKIP
        sources =\
            dictionary.get("sources")\
            if dictionary.get("sources")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(brand,
                   currencies,
                   commercial,
                   country,
                   sources,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _brand=self.brand
        _commercial=(
            self.commercial
            if hasattr(self, "commercial")
            else None
        )
        _country=(
            self.country
            if hasattr(self, "country")
            else None
        )
        _currencies=self.currencies
        _sources=(
            self.sources
            if hasattr(self, "sources")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"brand={_brand!r}, "
            f"commercial={_commercial!r}, "
            f"country={_country!r}, "
            f"currencies={_currencies!r}, "
            f"sources={_sources!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _brand=self.brand
        _commercial=(
            self.commercial
            if hasattr(self, "commercial")
            else None
        )
        _country=(
            self.country
            if hasattr(self, "country")
            else None
        )
        _currencies=self.currencies
        _sources=(
            self.sources
            if hasattr(self, "sources")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"brand={_brand!s}, "
            f"commercial={_commercial!s}, "
            f"country={_country!s}, "
            f"currencies={_currencies!s}, "
            f"sources={_sources!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
