"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class CreateScaInformation1(object):
    """Implementation of the 'CreateScaInformation1' model.

    Information for the Strong Customer Authentication (SCA)

    Attributes:
        exemption (ScaExemption): The model property of type ScaExemption.
        sca_on_approval (bool): Indicates whether to initiate Strong Customer
            Authentication (SCA) later, during approval, or immediately after you
            submit this request. Possible values: * **true**: you can initiate SCA
            later, during approval, for all pending transfer limits. * **false**
            (default): you initiate SCA immediately after submitting the transfer
            limit request.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "exemption": "exemption",
        "sca_on_approval": "scaOnApproval",
    }

    _optionals = [
        "exemption",
        "sca_on_approval",
    ]

    def __init__(
        self,
        exemption=APIHelper.SKIP,
        sca_on_approval=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CreateScaInformation1 instance."""
        # Initialize members of the class
        if exemption is not APIHelper.SKIP:
            self.exemption = exemption
        if sca_on_approval is not APIHelper.SKIP:
            self.sca_on_approval = sca_on_approval

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        exemption =\
            dictionary.get("exemption")\
            if dictionary.get("exemption")\
                else APIHelper.SKIP
        sca_on_approval =\
            dictionary.get("scaOnApproval")\
            if "scaOnApproval" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(exemption,
                   sca_on_approval,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _exemption=(
            self.exemption
            if hasattr(self, "exemption")
            else None
        )
        _sca_on_approval=(
            self.sca_on_approval
            if hasattr(self, "sca_on_approval")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"exemption={_exemption!r}, "
            f"sca_on_approval={_sca_on_approval!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _exemption=(
            self.exemption
            if hasattr(self, "exemption")
            else None
        )
        _sca_on_approval=(
            self.sca_on_approval
            if hasattr(self, "sca_on_approval")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"exemption={_exemption!s}, "
            f"sca_on_approval={_sca_on_approval!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
