"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.amount_16 import Amount16


class CustomNotification(object):
    """Implementation of the 'CustomNotification' model.

    Attributes:
        amount (Amount16): The model property of type Amount16.
        event_code (str): The event that caused the notification to be sent.Currently
            supported values: * **AUTHORISATION** * **CANCELLATION** * **REFUND** *
            **CAPTURE** * **REPORT_AVAILABLE** * **CHARGEBACK** *
            **REQUEST_FOR_INFORMATION** * **NOTIFICATION_OF_CHARGEBACK** *
            **NOTIFICATIONTEST** * **ORDER_OPENED** * **ORDER_CLOSED** *
            **CHARGEBACK_REVERSED** * **REFUNDED_REVERSED** * **REFUND_WITH_DATA**
        event_date (datetime): The time of the event. Format: [ISO
            8601](http://www.w3.org/TR/NOTE-datetime), YYYY-MM-DDThh:mm:ssTZD.
        merchant_reference (str): Your reference for the custom test notification.
        payment_method (str): The payment method for the payment that the
            notification is about. Possible values: * **amex** * **visa** * **mc** *
            **maestro** * **bcmc** * **paypal**  * **sms**  * **bankTransfer_NL** *
            **bankTransfer_DE** * **bankTransfer_BE** * **ideal** * **elv** *
            **sepadirectdebit**
        reason (str): A description of what caused the notification.
        success (bool): The outcome of the event which the notification is about. Set
            to either **true** or **false**.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "amount": "amount",
        "event_code": "eventCode",
        "event_date": "eventDate",
        "merchant_reference": "merchantReference",
        "payment_method": "paymentMethod",
        "reason": "reason",
        "success": "success",
    }

    _optionals = [
        "amount",
        "event_code",
        "event_date",
        "merchant_reference",
        "payment_method",
        "reason",
        "success",
    ]

    def __init__(
        self,
        amount=APIHelper.SKIP,
        event_code=APIHelper.SKIP,
        event_date=APIHelper.SKIP,
        merchant_reference=APIHelper.SKIP,
        payment_method=APIHelper.SKIP,
        reason=APIHelper.SKIP,
        success=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CustomNotification instance."""
        # Initialize members of the class
        if amount is not APIHelper.SKIP:
            self.amount = amount
        if event_code is not APIHelper.SKIP:
            self.event_code = event_code
        if event_date is not APIHelper.SKIP:
            self.event_date =\
                 APIHelper.apply_datetime_converter(
                event_date, APIHelper.RFC3339DateTime)\
                 if event_date else None
        if merchant_reference is not APIHelper.SKIP:
            self.merchant_reference = merchant_reference
        if payment_method is not APIHelper.SKIP:
            self.payment_method = payment_method
        if reason is not APIHelper.SKIP:
            self.reason = reason
        if success is not APIHelper.SKIP:
            self.success = success

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        amount =\
            Amount16.from_dictionary(
                dictionary.get("amount"))\
                if "amount" in dictionary.keys()\
                else APIHelper.SKIP
        event_code =\
            dictionary.get("eventCode")\
            if dictionary.get("eventCode")\
                else APIHelper.SKIP
        event_date = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("eventDate")).datetime\
            if dictionary.get("eventDate") else APIHelper.SKIP
        merchant_reference =\
            dictionary.get("merchantReference")\
            if dictionary.get("merchantReference")\
                else APIHelper.SKIP
        payment_method =\
            dictionary.get("paymentMethod")\
            if dictionary.get("paymentMethod")\
                else APIHelper.SKIP
        reason =\
            dictionary.get("reason")\
            if dictionary.get("reason")\
                else APIHelper.SKIP
        success =\
            dictionary.get("success")\
            if "success" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(amount,
                   event_code,
                   event_date,
                   merchant_reference,
                   payment_method,
                   reason,
                   success,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _event_code=(
            self.event_code
            if hasattr(self, "event_code")
            else None
        )
        _event_date=(
            self.event_date
            if hasattr(self, "event_date")
            else None
        )
        _merchant_reference=(
            self.merchant_reference
            if hasattr(self, "merchant_reference")
            else None
        )
        _payment_method=(
            self.payment_method
            if hasattr(self, "payment_method")
            else None
        )
        _reason=(
            self.reason
            if hasattr(self, "reason")
            else None
        )
        _success=(
            self.success
            if hasattr(self, "success")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!r}, "
            f"event_code={_event_code!r}, "
            f"event_date={_event_date!r}, "
            f"merchant_reference={_merchant_reference!r}, "
            f"payment_method={_payment_method!r}, "
            f"reason={_reason!r}, "
            f"success={_success!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _event_code=(
            self.event_code
            if hasattr(self, "event_code")
            else None
        )
        _event_date=(
            self.event_date
            if hasattr(self, "event_date")
            else None
        )
        _merchant_reference=(
            self.merchant_reference
            if hasattr(self, "merchant_reference")
            else None
        )
        _payment_method=(
            self.payment_method
            if hasattr(self, "payment_method")
            else None
        )
        _reason=(
            self.reason
            if hasattr(self, "reason")
            else None
        )
        _success=(
            self.success
            if hasattr(self, "success")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!s}, "
            f"event_code={_event_code!s}, "
            f"event_date={_event_date!s}, "
            f"merchant_reference={_merchant_reference!s}, "
            f"payment_method={_payment_method!s}, "
            f"reason={_reason!s}, "
            f"success={_success!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
