"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.type_23_enum import Type23Enum


class Doku(object):
    """Implementation of the 'Doku' model.

    Attributes:
        checkout_attempt_id (str): The checkout attempt identifier.
        first_name (str): The shopper's first name.
        last_name (str): The shopper's last name.
        sdk_data (str): Base64-encoded JSON object containing SDK related parameters
            required by the SDK
        shopper_email (str): The shopper's email.
        mtype (Type23Enum): **doku**

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "first_name": "firstName",
        "last_name": "lastName",
        "shopper_email": "shopperEmail",
        "mtype": "type",
        "checkout_attempt_id": "checkoutAttemptId",
        "sdk_data": "sdkData",
    }

    _optionals = [
        "checkout_attempt_id",
        "sdk_data",
    ]

    def __init__(
        self,
        first_name=None,
        last_name=None,
        shopper_email=None,
        mtype=None,
        checkout_attempt_id=APIHelper.SKIP,
        sdk_data=APIHelper.SKIP):
        """Initialize a Doku instance."""
        # Initialize members of the class
        if checkout_attempt_id is not APIHelper.SKIP:
            self.checkout_attempt_id = checkout_attempt_id
        self.first_name = first_name
        self.last_name = last_name
        if sdk_data is not APIHelper.SKIP:
            self.sdk_data = sdk_data
        self.shopper_email = shopper_email
        self.mtype = mtype

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        first_name =\
            dictionary.get("firstName")\
            if dictionary.get("firstName")\
                else None
        last_name =\
            dictionary.get("lastName")\
            if dictionary.get("lastName")\
                else None
        shopper_email =\
            dictionary.get("shopperEmail")\
            if dictionary.get("shopperEmail")\
                else None
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        checkout_attempt_id =\
            dictionary.get("checkoutAttemptId")\
            if dictionary.get("checkoutAttemptId")\
                else APIHelper.SKIP
        sdk_data =\
            dictionary.get("sdkData")\
            if dictionary.get("sdkData")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(first_name,
                   last_name,
                   shopper_email,
                   mtype,
                   checkout_attempt_id,
                   sdk_data)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.first_name,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.last_name,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.shopper_email,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.mtype,
                    type_callable=lambda value:
                        Type23Enum.validate(value))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("firstName"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("lastName"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("shopperEmail"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("type"),
                type_callable=lambda value:
                    Type23Enum.validate(value))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _checkout_attempt_id=(
            self.checkout_attempt_id
            if hasattr(self, "checkout_attempt_id")
            else None
        )
        _first_name=self.first_name
        _last_name=self.last_name
        _sdk_data=(
            self.sdk_data
            if hasattr(self, "sdk_data")
            else None
        )
        _shopper_email=self.shopper_email
        _mtype=self.mtype
        return (
            f"{self.__class__.__name__}("
            f"checkout_attempt_id={_checkout_attempt_id!r}, "
            f"first_name={_first_name!r}, "
            f"last_name={_last_name!r}, "
            f"sdk_data={_sdk_data!r}, "
            f"shopper_email={_shopper_email!r}, "
            f"mtype={_mtype!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _checkout_attempt_id=(
            self.checkout_attempt_id
            if hasattr(self, "checkout_attempt_id")
            else None
        )
        _first_name=self.first_name
        _last_name=self.last_name
        _sdk_data=(
            self.sdk_data
            if hasattr(self, "sdk_data")
            else None
        )
        _shopper_email=self.shopper_email
        _mtype=self.mtype
        return (
            f"{self.__class__.__name__}("
            f"checkout_attempt_id={_checkout_attempt_id!s}, "
            f"first_name={_first_name!s}, "
            f"last_name={_last_name!s}, "
            f"sdk_data={_sdk_data!s}, "
            f"shopper_email={_shopper_email!s}, "
            f"mtype={_mtype!s}, "
            f")"
        )
