"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.amount_26 import Amount26
from adyen.models.payment_response_9 import (
    PaymentResponse9,
)


class DonationPaymentResponse(object):
    """Implementation of the 'DonationPaymentResponse' model.

    Attributes:
        amount (Amount26): Authorised amount in the transaction.
        donation_account (str): The Adyen account name of your charity. We will
            provide you with this account name once your chosen charity has been
            [onboarded](https://docs.adyen.com/online-payments/donations#onboarding).
        id (str): Your unique resource identifier.
        merchant_account (str): The merchant account identifier, with which you want
            to process the transaction.
        payment (PaymentResponse9): Action to be taken for completing the payment.
        reference (str): The reference to uniquely identify a payment. This reference
            is used in all communication with you about the payment status. We
            recommend using a unique value per payment; however, it is not a
            requirement. If you need to provide multiple references for a
            transaction, separate them with hyphens ("-"). Maximum length: 80
            characters.
        status (Status1Enum): The status of the donation transaction.  Possible
            values: * **completed** * **pending** * **refused**

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "amount": "amount",
        "donation_account": "donationAccount",
        "id": "id",
        "merchant_account": "merchantAccount",
        "payment": "payment",
        "reference": "reference",
        "status": "status",
    }

    _optionals = [
        "amount",
        "donation_account",
        "id",
        "merchant_account",
        "payment",
        "reference",
        "status",
    ]

    def __init__(
        self,
        amount=APIHelper.SKIP,
        donation_account=APIHelper.SKIP,
        id=APIHelper.SKIP,
        merchant_account=APIHelper.SKIP,
        payment=APIHelper.SKIP,
        reference=APIHelper.SKIP,
        status=APIHelper.SKIP):
        """Initialize a DonationPaymentResponse instance."""
        # Initialize members of the class
        if amount is not APIHelper.SKIP:
            self.amount = amount
        if donation_account is not APIHelper.SKIP:
            self.donation_account = donation_account
        if id is not APIHelper.SKIP:
            self.id = id
        if merchant_account is not APIHelper.SKIP:
            self.merchant_account = merchant_account
        if payment is not APIHelper.SKIP:
            self.payment = payment
        if reference is not APIHelper.SKIP:
            self.reference = reference
        if status is not APIHelper.SKIP:
            self.status = status

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        amount =\
            Amount26.from_dictionary(
                dictionary.get("amount"))\
                if "amount" in dictionary.keys()\
                else APIHelper.SKIP
        donation_account =\
            dictionary.get("donationAccount")\
            if dictionary.get("donationAccount")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        merchant_account =\
            dictionary.get("merchantAccount")\
            if dictionary.get("merchantAccount")\
                else APIHelper.SKIP
        payment =\
            PaymentResponse9.from_dictionary(
                dictionary.get("payment"))\
                if "payment" in dictionary.keys()\
                else APIHelper.SKIP
        reference =\
            dictionary.get("reference")\
            if dictionary.get("reference")\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(amount,
                   donation_account,
                   id,
                   merchant_account,
                   payment,
                   reference,
                   status)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _donation_account=(
            self.donation_account
            if hasattr(self, "donation_account")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _merchant_account=(
            self.merchant_account
            if hasattr(self, "merchant_account")
            else None
        )
        _payment=(
            self.payment
            if hasattr(self, "payment")
            else None
        )
        _reference=(
            self.reference
            if hasattr(self, "reference")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!r}, "
            f"donation_account={_donation_account!r}, "
            f"id={_id!r}, "
            f"merchant_account={_merchant_account!r}, "
            f"payment={_payment!r}, "
            f"reference={_reference!r}, "
            f"status={_status!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _donation_account=(
            self.donation_account
            if hasattr(self, "donation_account")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _merchant_account=(
            self.merchant_account
            if hasattr(self, "merchant_account")
            else None
        )
        _payment=(
            self.payment
            if hasattr(self, "payment")
            else None
        )
        _reference=(
            self.reference
            if hasattr(self, "reference")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"amount={_amount!s}, "
            f"donation_account={_donation_account!s}, "
            f"id={_id!s}, "
            f"merchant_account={_merchant_account!s}, "
            f"payment={_payment!s}, "
            f"reference={_reference!s}, "
            f"status={_status!s}, "
            f")"
        )
