"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class EftAccountIdentifier(object):
    """Implementation of the 'EFTAccountIdentifier' model.

    Attributes:
        account_number (str): The account number of the bank account.
        branch (str): Identifies the specific branch where the account is held within
            the Canadian banking system.
        institution (str): The financial institution that identifies the bank in
            Canada.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_number": "accountNumber",
        "branch": "branch",
        "institution": "institution",
    }

    def __init__(
        self,
        account_number=None,
        branch=None,
        institution=None,
        additional_properties=None):
        """Initialize a EftAccountIdentifier instance."""
        # Initialize members of the class
        self.account_number = account_number
        self.branch = branch
        self.institution = institution

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_number =\
            dictionary.get("accountNumber")\
            if dictionary.get("accountNumber")\
                else None
        branch =\
            dictionary.get("branch")\
            if dictionary.get("branch")\
                else None
        institution =\
            dictionary.get("institution")\
            if dictionary.get("institution")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(account_number,
                   branch,
                   institution,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_number=self.account_number
        _branch=self.branch
        _institution=self.institution
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_number={_account_number!r}, "
            f"branch={_branch!r}, "
            f"institution={_institution!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_number=self.account_number
        _branch=self.branch
        _institution=self.institution
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_number={_account_number!s}, "
            f"branch={_branch!s}, "
            f"institution={_institution!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
