"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class EncryptedOrderData2(object):
    """Implementation of the 'EncryptedOrderData2' model.

    The order information required for partial payments.

    Attributes:
        order_data (str): The encrypted order data.
        psp_reference (str): The `pspReference` that belongs to the order.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "order_data": "orderData",
        "psp_reference": "pspReference",
    }

    def __init__(
        self,
        order_data=None,
        psp_reference=None):
        """Initialize a EncryptedOrderData2 instance."""
        # Initialize members of the class
        self.order_data = order_data
        self.psp_reference = psp_reference

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        order_data =\
            dictionary.get("orderData")\
            if dictionary.get("orderData")\
                else None
        psp_reference =\
            dictionary.get("pspReference")\
            if dictionary.get("pspReference")\
                else None

        # Return an object of this model
        return cls(order_data,
                   psp_reference)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.order_data,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.psp_reference,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("orderData"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("pspReference"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _order_data=self.order_data
        _psp_reference=self.psp_reference
        return (
            f"{self.__class__.__name__}("
            f"order_data={_order_data!r}, "
            f"psp_reference={_psp_reference!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _order_data=self.order_data
        _psp_reference=self.psp_reference
        return (
            f"{self.__class__.__name__}("
            f"order_data={_order_data!s}, "
            f"psp_reference={_psp_reference!s}, "
            f")"
        )
