"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.url import Url


class EventUrl2(object):
    """Implementation of the 'EventUrl2' model.

    The list of local and public URLs to send event notifications to when using
    Terminal API.

    Attributes:
        event_local_urls (List[Url]): One or more local URLs to send event
            notifications to when using Terminal API.
        event_public_urls (List[Url]): One or more public URLs to send event
            notifications to when using Terminal API.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "event_local_urls": "eventLocalUrls",
        "event_public_urls": "eventPublicUrls",
    }

    _optionals = [
        "event_local_urls",
        "event_public_urls",
    ]

    def __init__(
        self,
        event_local_urls=APIHelper.SKIP,
        event_public_urls=APIHelper.SKIP):
        """Initialize a EventUrl2 instance."""
        # Initialize members of the class
        if event_local_urls is not APIHelper.SKIP:
            self.event_local_urls = event_local_urls
        if event_public_urls is not APIHelper.SKIP:
            self.event_public_urls = event_public_urls

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        event_local_urls = None
        if dictionary.get("eventLocalUrls") is not None:
            event_local_urls = [
                Url.from_dictionary(x)
                    for x in dictionary.get("eventLocalUrls")
            ]
        else:
            event_local_urls = APIHelper.SKIP
        event_public_urls = None
        if dictionary.get("eventPublicUrls") is not None:
            event_public_urls = [
                Url.from_dictionary(x)
                    for x in dictionary.get("eventPublicUrls")
            ]
        else:
            event_public_urls = APIHelper.SKIP

        # Return an object of this model
        return cls(event_local_urls,
                   event_public_urls)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _event_local_urls=(
            self.event_local_urls
            if hasattr(self, "event_local_urls")
            else None
        )
        _event_public_urls=(
            self.event_public_urls
            if hasattr(self, "event_public_urls")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"event_local_urls={_event_local_urls!r}, "
            f"event_public_urls={_event_public_urls!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _event_local_urls=(
            self.event_local_urls
            if hasattr(self, "event_local_urls")
            else None
        )
        _event_public_urls=(
            self.event_public_urls
            if hasattr(self, "event_public_urls")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"event_local_urls={_event_local_urls!s}, "
            f"event_public_urls={_event_public_urls!s}, "
            f")"
        )
