"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.counterparty_12 import Counterparty12


class GrantInfo(object):
    """Implementation of the 'GrantInfo' model.

    Attributes:
        counterparty (Counterparty12): The model property of type Counterparty12.
        grant_account_id (str): The unique identifier of the grant account that
            tracks this grant.
        grant_offer_id (str): The unique identifier of the selected offer. Adyen uses
            the details of the selected offer to create a grant.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "grant_account_id": "grantAccountId",
        "grant_offer_id": "grantOfferId",
        "counterparty": "counterparty",
    }

    _optionals = [
        "counterparty",
    ]

    def __init__(
        self,
        grant_account_id=None,
        grant_offer_id=None,
        counterparty=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GrantInfo instance."""
        # Initialize members of the class
        if counterparty is not APIHelper.SKIP:
            self.counterparty = counterparty
        self.grant_account_id = grant_account_id
        self.grant_offer_id = grant_offer_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        grant_account_id =\
            dictionary.get("grantAccountId")\
            if dictionary.get("grantAccountId")\
                else None
        grant_offer_id =\
            dictionary.get("grantOfferId")\
            if dictionary.get("grantOfferId")\
                else None
        counterparty =\
            Counterparty12.from_dictionary(
                dictionary.get("counterparty"))\
                if "counterparty" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(grant_account_id,
                   grant_offer_id,
                   counterparty,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _counterparty=(
            self.counterparty
            if hasattr(self, "counterparty")
            else None
        )
        _grant_account_id=self.grant_account_id
        _grant_offer_id=self.grant_offer_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"counterparty={_counterparty!r}, "
            f"grant_account_id={_grant_account_id!r}, "
            f"grant_offer_id={_grant_offer_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _counterparty=(
            self.counterparty
            if hasattr(self, "counterparty")
            else None
        )
        _grant_account_id=self.grant_account_id
        _grant_offer_id=self.grant_offer_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"counterparty={_counterparty!s}, "
            f"grant_account_id={_grant_account_id!s}, "
            f"grant_offer_id={_grant_offer_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
