"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class InstallmentOption(object):
    """Implementation of the 'InstallmentOption' model.

    Attributes:
        max_value (int): The maximum number of installments offered for this payment
            method.
        plans (List[Plan1]): Defines the type of installment plan. If not set,
            defaults to **regular**.  Possible values: * **regular** * **revolving**
        preselected_value (int): Preselected number of installments offered for this
            payment method.
        values (List[int]): An array of the number of installments that the shopper
            can choose from. For example, **[2,3,5]**. This cannot be specified
            simultaneously with `maxValue`.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "max_value": "maxValue",
        "plans": "plans",
        "preselected_value": "preselectedValue",
        "values": "values",
    }

    _optionals = [
        "max_value",
        "plans",
        "preselected_value",
        "values",
    ]

    def __init__(
        self,
        max_value=APIHelper.SKIP,
        plans=APIHelper.SKIP,
        preselected_value=APIHelper.SKIP,
        values=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a InstallmentOption instance."""
        # Initialize members of the class
        if max_value is not APIHelper.SKIP:
            self.max_value = max_value
        if plans is not APIHelper.SKIP:
            self.plans = plans
        if preselected_value is not APIHelper.SKIP:
            self.preselected_value = preselected_value
        if values is not APIHelper.SKIP:
            self.values = values

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        max_value =\
            dictionary.get("maxValue")\
            if dictionary.get("maxValue")\
                else APIHelper.SKIP
        plans =\
            dictionary.get("plans")\
            if dictionary.get("plans")\
                else APIHelper.SKIP
        preselected_value =\
            dictionary.get("preselectedValue")\
            if dictionary.get("preselectedValue")\
                else APIHelper.SKIP
        values =\
            dictionary.get("values")\
            if dictionary.get("values")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(max_value,
                   plans,
                   preselected_value,
                   values,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _max_value=(
            self.max_value
            if hasattr(self, "max_value")
            else None
        )
        _plans=(
            self.plans
            if hasattr(self, "plans")
            else None
        )
        _preselected_value=(
            self.preselected_value
            if hasattr(self, "preselected_value")
            else None
        )
        _values=(
            self.values
            if hasattr(self, "values")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"max_value={_max_value!r}, "
            f"plans={_plans!r}, "
            f"preselected_value={_preselected_value!r}, "
            f"values={_values!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _max_value=(
            self.max_value
            if hasattr(self, "max_value")
            else None
        )
        _plans=(
            self.plans
            if hasattr(self, "plans")
            else None
        )
        _preselected_value=(
            self.preselected_value
            if hasattr(self, "preselected_value")
            else None
        )
        _values=(
            self.values
            if hasattr(self, "values")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"max_value={_max_value!s}, "
            f"plans={_plans!s}, "
            f"preselected_value={_preselected_value!s}, "
            f"values={_values!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
