"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class Leg(object):
    """Implementation of the 'Leg' model.

    Attributes:
        carrier_code (str): The
            [IATA](https://www.iata.org/services/pages/codes.aspx) 2-letter
            accounting code (PAX) that identifies the carrier. This field is required
            if the airline data includes leg details. * Example: KLM = KL *
            minLength: 2 characters * maxLength: 2 characters * Must not start with a
            space or be all spaces. * Must not be all zeros. * **additionalData
            key:** `airline.leg[N].carrier_code`
        class_of_travel (str): A one-letter travel class identifier.  The following
            are common:  * F: first class * J: business class * Y: economy class * W:
            premium economy  * Encoding: ASCII * minLength: 1 character * maxLength:
            1 character * Must not start with a space or be all spaces. * Must not be
            all zeros. * **additionalData key:** `airline.leg[N].class_of_travel`
        date_of_travel (datetime): Date and time of travel in format
            `yyyy-MM-ddTHH:mm`. * Use local time of departure airport. * minLength:
            16 characters * maxLength: 16 characters * **additionalData key:**
            `airline.leg[N].date_of_travel`
        departure_airport_code (str): The
            [IATA](https://www.iata.org/services/pages/codes.aspx) three-letter
            airport code of the departure airport. This field is required if the
            airline data includes leg details.  * Encoding: ASCII * Example:
            Amsterdam = AMS * minLength: 3 characters * maxLength: 3 characters *
            Must not start with a space or be all spaces. * Must not be all zeros. *
            **additionalData key:** `airline.leg[N].depart_airport`
        departure_tax (int): The amount of [departure
            tax](https://en.wikipedia.org/wiki/Departure_tax) charged, in [minor
            units](https://docs.adyen.com/development-resources/currency-codes). *
            Encoding: Numeric * minLength: 1 * maxLength: 11 * Must not be all zeros.
            * **additionalData key:** `airline.leg[N].depart_tax`
        destination_airport_code (str): The
            [IATA](https://www.iata.org/services/pages/codes.aspx) 3-letter airport
            code of the destination airport. This field is required if the airline
            data includes leg details. * Example: Amsterdam = AMS * Encoding: ASCII *
            minLength: 3 characters * maxLength: 3 characters * Must not start with a
            space or be all spaces. * Must not be all zeros. * **additionalData
            key:** `airline.leg[N].destination_code`
        fare_basis_code (str): The [fare basis
            code](https://en.wikipedia.org/wiki/Fare_basis_code), alphanumeric. *
            minLength: 1 character * maxLength: 15 characters * Must not start with a
            space or be all spaces. * Must not be all zeros. * **additionalData
            key:** `airline.leg[N].fare_base_code`
        flight_number (str): The flight identifier. * minLength: 1 character *
            maxLength: 5 characters * Must not start with a space or be all spaces. *
            Must not be all zeros. * **additionalData key:**
            `airline.leg[N].flight_number`
        stop_over_code (str): A one-letter code that indicates whether the passenger
            is entitled to make a stopover. Can be a space, O if the passenger is
            entitled to make a stopover, or X if they are not. * Encoding: ASCII *
            minLength: 1 character * maxLength: 1 character * **additionalData key:**
            `airline.leg[N].stop_over_code`

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "carrier_code": "carrierCode",
        "class_of_travel": "classOfTravel",
        "date_of_travel": "dateOfTravel",
        "departure_airport_code": "departureAirportCode",
        "departure_tax": "departureTax",
        "destination_airport_code": "destinationAirportCode",
        "fare_basis_code": "fareBasisCode",
        "flight_number": "flightNumber",
        "stop_over_code": "stopOverCode",
    }

    _optionals = [
        "carrier_code",
        "class_of_travel",
        "date_of_travel",
        "departure_airport_code",
        "departure_tax",
        "destination_airport_code",
        "fare_basis_code",
        "flight_number",
        "stop_over_code",
    ]

    def __init__(
        self,
        carrier_code=APIHelper.SKIP,
        class_of_travel=APIHelper.SKIP,
        date_of_travel=APIHelper.SKIP,
        departure_airport_code=APIHelper.SKIP,
        departure_tax=APIHelper.SKIP,
        destination_airport_code=APIHelper.SKIP,
        fare_basis_code=APIHelper.SKIP,
        flight_number=APIHelper.SKIP,
        stop_over_code=APIHelper.SKIP):
        """Initialize a Leg instance."""
        # Initialize members of the class
        if carrier_code is not APIHelper.SKIP:
            self.carrier_code = carrier_code
        if class_of_travel is not APIHelper.SKIP:
            self.class_of_travel = class_of_travel
        if date_of_travel is not APIHelper.SKIP:
            self.date_of_travel =\
                 APIHelper.apply_datetime_converter(
                date_of_travel, APIHelper.RFC3339DateTime)\
                 if date_of_travel else None
        if departure_airport_code is not APIHelper.SKIP:
            self.departure_airport_code = departure_airport_code
        if departure_tax is not APIHelper.SKIP:
            self.departure_tax = departure_tax
        if destination_airport_code is not APIHelper.SKIP:
            self.destination_airport_code = destination_airport_code
        if fare_basis_code is not APIHelper.SKIP:
            self.fare_basis_code = fare_basis_code
        if flight_number is not APIHelper.SKIP:
            self.flight_number = flight_number
        if stop_over_code is not APIHelper.SKIP:
            self.stop_over_code = stop_over_code

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        carrier_code =\
            dictionary.get("carrierCode")\
            if dictionary.get("carrierCode")\
                else APIHelper.SKIP
        class_of_travel =\
            dictionary.get("classOfTravel")\
            if dictionary.get("classOfTravel")\
                else APIHelper.SKIP
        date_of_travel = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("dateOfTravel")).datetime\
            if dictionary.get("dateOfTravel") else APIHelper.SKIP
        departure_airport_code =\
            dictionary.get("departureAirportCode")\
            if dictionary.get("departureAirportCode")\
                else APIHelper.SKIP
        departure_tax =\
            dictionary.get("departureTax")\
            if dictionary.get("departureTax")\
                else APIHelper.SKIP
        destination_airport_code =\
            dictionary.get("destinationAirportCode")\
            if dictionary.get("destinationAirportCode")\
                else APIHelper.SKIP
        fare_basis_code =\
            dictionary.get("fareBasisCode")\
            if dictionary.get("fareBasisCode")\
                else APIHelper.SKIP
        flight_number =\
            dictionary.get("flightNumber")\
            if dictionary.get("flightNumber")\
                else APIHelper.SKIP
        stop_over_code =\
            dictionary.get("stopOverCode")\
            if dictionary.get("stopOverCode")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(carrier_code,
                   class_of_travel,
                   date_of_travel,
                   departure_airport_code,
                   departure_tax,
                   destination_airport_code,
                   fare_basis_code,
                   flight_number,
                   stop_over_code)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _carrier_code=(
            self.carrier_code
            if hasattr(self, "carrier_code")
            else None
        )
        _class_of_travel=(
            self.class_of_travel
            if hasattr(self, "class_of_travel")
            else None
        )
        _date_of_travel=(
            self.date_of_travel
            if hasattr(self, "date_of_travel")
            else None
        )
        _departure_airport_code=(
            self.departure_airport_code
            if hasattr(self, "departure_airport_code")
            else None
        )
        _departure_tax=(
            self.departure_tax
            if hasattr(self, "departure_tax")
            else None
        )
        _destination_airport_code=(
            self.destination_airport_code
            if hasattr(self, "destination_airport_code")
            else None
        )
        _fare_basis_code=(
            self.fare_basis_code
            if hasattr(self, "fare_basis_code")
            else None
        )
        _flight_number=(
            self.flight_number
            if hasattr(self, "flight_number")
            else None
        )
        _stop_over_code=(
            self.stop_over_code
            if hasattr(self, "stop_over_code")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"carrier_code={_carrier_code!r}, "
            f"class_of_travel={_class_of_travel!r}, "
            f"date_of_travel={_date_of_travel!r}, "
            f"departure_airport_code={_departure_airport_code!r}, "
            f"departure_tax={_departure_tax!r}, "
            f"destination_airport_code={_destination_airport_code!r}, "
            f"fare_basis_code={_fare_basis_code!r}, "
            f"flight_number={_flight_number!r}, "
            f"stop_over_code={_stop_over_code!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _carrier_code=(
            self.carrier_code
            if hasattr(self, "carrier_code")
            else None
        )
        _class_of_travel=(
            self.class_of_travel
            if hasattr(self, "class_of_travel")
            else None
        )
        _date_of_travel=(
            self.date_of_travel
            if hasattr(self, "date_of_travel")
            else None
        )
        _departure_airport_code=(
            self.departure_airport_code
            if hasattr(self, "departure_airport_code")
            else None
        )
        _departure_tax=(
            self.departure_tax
            if hasattr(self, "departure_tax")
            else None
        )
        _destination_airport_code=(
            self.destination_airport_code
            if hasattr(self, "destination_airport_code")
            else None
        )
        _fare_basis_code=(
            self.fare_basis_code
            if hasattr(self, "fare_basis_code")
            else None
        )
        _flight_number=(
            self.flight_number
            if hasattr(self, "flight_number")
            else None
        )
        _stop_over_code=(
            self.stop_over_code
            if hasattr(self, "stop_over_code")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"carrier_code={_carrier_code!s}, "
            f"class_of_travel={_class_of_travel!s}, "
            f"date_of_travel={_date_of_travel!s}, "
            f"departure_airport_code={_departure_airport_code!s}, "
            f"departure_tax={_departure_tax!s}, "
            f"destination_airport_code={_destination_airport_code!s}, "
            f"fare_basis_code={_fare_basis_code!s}, "
            f"flight_number={_flight_number!s}, "
            f"stop_over_code={_stop_over_code!s}, "
            f")"
        )
