"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.stored_payment_method_resource import (
    StoredPaymentMethodResource,
)


class ListStoredPaymentMethodsResponse(object):
    """Implementation of the 'ListStoredPaymentMethodsResponse' model.

    Attributes:
        merchant_account (str): Your merchant account.
        shopper_reference (str): Your reference to uniquely identify this shopper,
            for example user ID or account ID. Minimum length: 3 characters. > Your
            reference must not include personally identifiable information (PII), for
            example name or email address.
        stored_payment_methods (List[StoredPaymentMethodResource]): List of all
            stored payment methods.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "merchant_account": "merchantAccount",
        "shopper_reference": "shopperReference",
        "stored_payment_methods": "storedPaymentMethods",
    }

    _optionals = [
        "merchant_account",
        "shopper_reference",
        "stored_payment_methods",
    ]

    def __init__(
        self,
        merchant_account=APIHelper.SKIP,
        shopper_reference=APIHelper.SKIP,
        stored_payment_methods=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListStoredPaymentMethodsResponse instance."""
        # Initialize members of the class
        if merchant_account is not APIHelper.SKIP:
            self.merchant_account = merchant_account
        if shopper_reference is not APIHelper.SKIP:
            self.shopper_reference = shopper_reference
        if stored_payment_methods is not APIHelper.SKIP:
            self.stored_payment_methods = stored_payment_methods

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        merchant_account =\
            dictionary.get("merchantAccount")\
            if dictionary.get("merchantAccount")\
                else APIHelper.SKIP
        shopper_reference =\
            dictionary.get("shopperReference")\
            if dictionary.get("shopperReference")\
                else APIHelper.SKIP
        stored_payment_methods = None
        if dictionary.get("storedPaymentMethods") is not None:
            stored_payment_methods = [
                StoredPaymentMethodResource.from_dictionary(x)
                    for x in dictionary.get("storedPaymentMethods")
            ]
        else:
            stored_payment_methods = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(merchant_account,
                   shopper_reference,
                   stored_payment_methods,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _merchant_account=(
            self.merchant_account
            if hasattr(self, "merchant_account")
            else None
        )
        _shopper_reference=(
            self.shopper_reference
            if hasattr(self, "shopper_reference")
            else None
        )
        _stored_payment_methods=(
            self.stored_payment_methods
            if hasattr(self, "stored_payment_methods")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"merchant_account={_merchant_account!r}, "
            f"shopper_reference={_shopper_reference!r}, "
            f"stored_payment_methods={_stored_payment_methods!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _merchant_account=(
            self.merchant_account
            if hasattr(self, "merchant_account")
            else None
        )
        _shopper_reference=(
            self.shopper_reference
            if hasattr(self, "shopper_reference")
            else None
        )
        _stored_payment_methods=(
            self.stored_payment_methods
            if hasattr(self, "stored_payment_methods")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"merchant_account={_merchant_account!s}, "
            f"shopper_reference={_shopper_reference!s}, "
            f"stored_payment_methods={_stored_payment_methods!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
