"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.data_center import DataCenter
from adyen.models.merchant_links_2 import MerchantLinks2


class Merchant(object):
    """Implementation of the 'Merchant' model.

    Attributes:
        links (MerchantLinks2): References to resources connected with this merchant.
        capture_delay (str): The [capture
            delay](https://docs.adyen.com/online-payments/capture#capture-delay) set
            for the merchant account.  Possible values: * **Immediate** * **Manual**
            * Number of days from **1** to **29**
        company_id (str): The unique identifier of the company account this merchant
            belongs to
        data_centers (List[DataCenter]): List of available data centers.  Adyen has
            several data centers around the world.In the URL that you use for making
            API requests, we recommend you use the live URL prefix from the data
            center closest to your shoppers.
        default_shopper_interaction (str): The default
            [`shopperInteraction`](https://docs.adyen.com/api-explorer/#/CheckoutServi
            ce/v68/post/payments__reqParam_shopperInteraction) value used when
            processing payments through this merchant account.
        description (str): Your description for the merchant account, maximum 300
            characters
        id (str): The unique identifier of the merchant account.
        merchant_city (str): The city where the legal entity of this merchant account
            is registered.
        name (str): The name of the legal entity associated with the merchant account.
        pricing_plan (str): Only applies to merchant accounts managed by Adyen's
            partners. The name of the pricing plan assigned to the merchant account.
        primary_settlement_currency (str): The currency of the country where the
            legal entity of this merchant account is registered. Format: [ISO
            currency
            code](https://docs.adyen.com/development-resources/currency-codes). For
            example, a legal entity based in the United States has USD as the primary
            settlement currency.
        reference (str): Reference of the merchant account.
        shop_web_address (str): The URL for the ecommerce website used with this
            merchant account.
        status (str): The status of the merchant account.  Possible values:  *
            **PreActive**: The merchant account has been created. Users cannot access
            the merchant account in the Customer Area. The account cannot process
            payments. * **Active**: Users can access the merchant account in the
            Customer Area. If the company account is also **Active**, then payment
            processing and payouts are enabled. * **InactiveWithModifications**:
            Users can access the merchant account in the Customer Area. You cannot
            process new payments but you can still modify payments, for example issue
            refunds. You can still receive payouts. * **Inactive**: Users can access
            the merchant account in the Customer Area. Payment processing and payouts
            are disabled. * **Closed**: The account is closed and this cannot be
            reversed. Users cannot log in. Payment processing and payouts are
            disabled.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "links": "_links",
        "capture_delay": "captureDelay",
        "company_id": "companyId",
        "data_centers": "dataCenters",
        "default_shopper_interaction": "defaultShopperInteraction",
        "description": "description",
        "id": "id",
        "merchant_city": "merchantCity",
        "name": "name",
        "pricing_plan": "pricingPlan",
        "primary_settlement_currency": "primarySettlementCurrency",
        "reference": "reference",
        "shop_web_address": "shopWebAddress",
        "status": "status",
    }

    _optionals = [
        "links",
        "capture_delay",
        "company_id",
        "data_centers",
        "default_shopper_interaction",
        "description",
        "id",
        "merchant_city",
        "name",
        "pricing_plan",
        "primary_settlement_currency",
        "reference",
        "shop_web_address",
        "status",
    ]

    def __init__(
        self,
        links=APIHelper.SKIP,
        capture_delay=APIHelper.SKIP,
        company_id=APIHelper.SKIP,
        data_centers=APIHelper.SKIP,
        default_shopper_interaction=APIHelper.SKIP,
        description=APIHelper.SKIP,
        id=APIHelper.SKIP,
        merchant_city=APIHelper.SKIP,
        name=APIHelper.SKIP,
        pricing_plan=APIHelper.SKIP,
        primary_settlement_currency=APIHelper.SKIP,
        reference=APIHelper.SKIP,
        shop_web_address=APIHelper.SKIP,
        status=APIHelper.SKIP):
        """Initialize a Merchant instance."""
        # Initialize members of the class
        if links is not APIHelper.SKIP:
            self.links = links
        if capture_delay is not APIHelper.SKIP:
            self.capture_delay = capture_delay
        if company_id is not APIHelper.SKIP:
            self.company_id = company_id
        if data_centers is not APIHelper.SKIP:
            self.data_centers = data_centers
        if default_shopper_interaction is not APIHelper.SKIP:
            self.default_shopper_interaction = default_shopper_interaction
        if description is not APIHelper.SKIP:
            self.description = description
        if id is not APIHelper.SKIP:
            self.id = id
        if merchant_city is not APIHelper.SKIP:
            self.merchant_city = merchant_city
        if name is not APIHelper.SKIP:
            self.name = name
        if pricing_plan is not APIHelper.SKIP:
            self.pricing_plan = pricing_plan
        if primary_settlement_currency is not APIHelper.SKIP:
            self.primary_settlement_currency = primary_settlement_currency
        if reference is not APIHelper.SKIP:
            self.reference = reference
        if shop_web_address is not APIHelper.SKIP:
            self.shop_web_address = shop_web_address
        if status is not APIHelper.SKIP:
            self.status = status

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        links =\
            MerchantLinks2.from_dictionary(
                dictionary.get("_links"))\
                if "_links" in dictionary.keys()\
                else APIHelper.SKIP
        capture_delay =\
            dictionary.get("captureDelay")\
            if dictionary.get("captureDelay")\
                else APIHelper.SKIP
        company_id =\
            dictionary.get("companyId")\
            if dictionary.get("companyId")\
                else APIHelper.SKIP
        data_centers = None
        if dictionary.get("dataCenters") is not None:
            data_centers = [
                DataCenter.from_dictionary(x)
                    for x in dictionary.get("dataCenters")
            ]
        else:
            data_centers = APIHelper.SKIP
        default_shopper_interaction =\
            dictionary.get("defaultShopperInteraction")\
            if dictionary.get("defaultShopperInteraction")\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        merchant_city =\
            dictionary.get("merchantCity")\
            if dictionary.get("merchantCity")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        pricing_plan =\
            dictionary.get("pricingPlan")\
            if dictionary.get("pricingPlan")\
                else APIHelper.SKIP
        primary_settlement_currency =\
            dictionary.get("primarySettlementCurrency")\
            if dictionary.get("primarySettlementCurrency")\
                else APIHelper.SKIP
        reference =\
            dictionary.get("reference")\
            if dictionary.get("reference")\
                else APIHelper.SKIP
        shop_web_address =\
            dictionary.get("shopWebAddress")\
            if dictionary.get("shopWebAddress")\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(links,
                   capture_delay,
                   company_id,
                   data_centers,
                   default_shopper_interaction,
                   description,
                   id,
                   merchant_city,
                   name,
                   pricing_plan,
                   primary_settlement_currency,
                   reference,
                   shop_web_address,
                   status)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        _capture_delay=(
            self.capture_delay
            if hasattr(self, "capture_delay")
            else None
        )
        _company_id=(
            self.company_id
            if hasattr(self, "company_id")
            else None
        )
        _data_centers=(
            self.data_centers
            if hasattr(self, "data_centers")
            else None
        )
        _default_shopper_interaction=(
            self.default_shopper_interaction
            if hasattr(self, "default_shopper_interaction")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _merchant_city=(
            self.merchant_city
            if hasattr(self, "merchant_city")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _pricing_plan=(
            self.pricing_plan
            if hasattr(self, "pricing_plan")
            else None
        )
        _primary_settlement_currency=(
            self.primary_settlement_currency
            if hasattr(self, "primary_settlement_currency")
            else None
        )
        _reference=(
            self.reference
            if hasattr(self, "reference")
            else None
        )
        _shop_web_address=(
            self.shop_web_address
            if hasattr(self, "shop_web_address")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"links={_links!r}, "
            f"capture_delay={_capture_delay!r}, "
            f"company_id={_company_id!r}, "
            f"data_centers={_data_centers!r}, "
            f"default_shopper_interaction={_default_shopper_interaction!r}, "
            f"description={_description!r}, "
            f"id={_id!r}, "
            f"merchant_city={_merchant_city!r}, "
            f"name={_name!r}, "
            f"pricing_plan={_pricing_plan!r}, "
            f"primary_settlement_currency={_primary_settlement_currency!r}, "
            f"reference={_reference!r}, "
            f"shop_web_address={_shop_web_address!r}, "
            f"status={_status!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _links=(
            self.links
            if hasattr(self, "links")
            else None
        )
        _capture_delay=(
            self.capture_delay
            if hasattr(self, "capture_delay")
            else None
        )
        _company_id=(
            self.company_id
            if hasattr(self, "company_id")
            else None
        )
        _data_centers=(
            self.data_centers
            if hasattr(self, "data_centers")
            else None
        )
        _default_shopper_interaction=(
            self.default_shopper_interaction
            if hasattr(self, "default_shopper_interaction")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _merchant_city=(
            self.merchant_city
            if hasattr(self, "merchant_city")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _pricing_plan=(
            self.pricing_plan
            if hasattr(self, "pricing_plan")
            else None
        )
        _primary_settlement_currency=(
            self.primary_settlement_currency
            if hasattr(self, "primary_settlement_currency")
            else None
        )
        _reference=(
            self.reference
            if hasattr(self, "reference")
            else None
        )
        _shop_web_address=(
            self.shop_web_address
            if hasattr(self, "shop_web_address")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"links={_links!s}, "
            f"capture_delay={_capture_delay!s}, "
            f"company_id={_company_id!s}, "
            f"data_centers={_data_centers!s}, "
            f"default_shopper_interaction={_default_shopper_interaction!s}, "
            f"description={_description!s}, "
            f"id={_id!s}, "
            f"merchant_city={_merchant_city!s}, "
            f"name={_name!s}, "
            f"pricing_plan={_pricing_plan!s}, "
            f"primary_settlement_currency={_primary_settlement_currency!s}, "
            f"reference={_reference!s}, "
            f"shop_web_address={_shop_web_address!s}, "
            f"status={_status!s}, "
            f")"
        )
