"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class MessageReference4(object):
    """Implementation of the 'MessageReference4' model.

    Identification of a previous POI transaction.

    Attributes:
        message_category (MessageCategory2Enum): Category of message.
            CardAcquisition, Display, Input, Loyalty, Payment, Print, CardReaderInit,
            CardReaderPowerOff. Possible values: * **Abort** * **Admin** *
            **BalanceInquiry** * **Batch** * **CardAcquisition** * **CardReaderInit**
            * **CardReaderPowerOff** * **Diagnosis** * **Display** *
            **EnableService** * **Event** * **GetTotals** * **Input** *
            **InputUpdate** * **Login** * **Logout** * **Loyalty** * **None** *
            **PIN** * **Payment** * **Print** * **Reconciliation** * **Reversal** *
            **Sound** * **StoredValue** * **TransactionStatus** * **Transmit**
        service_id (str): Identification of a message pair, which processes a
            transaction.
        device_id (str): Identification of a device message pair.
        sale_id (str): Identification of a Sale System or a Sale Terminal for the
            Sale to POI protocol. default MessageHeader.SaleID.
        poiid (str): Identification of a POI System or a POI Terminal for the Sale to
            POI protocol. Default `MessageHeader.POIID`.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "message_category": "MessageCategory",
        "service_id": "ServiceID",
        "device_id": "DeviceID",
        "sale_id": "SaleID",
        "poiid": "POIID",
    }

    _optionals = [
        "message_category",
        "service_id",
        "device_id",
        "sale_id",
        "poiid",
    ]

    def __init__(
        self,
        message_category=APIHelper.SKIP,
        service_id=APIHelper.SKIP,
        device_id=APIHelper.SKIP,
        sale_id=APIHelper.SKIP,
        poiid=APIHelper.SKIP):
        """Initialize a MessageReference4 instance."""
        # Initialize members of the class
        if message_category is not APIHelper.SKIP:
            self.message_category = message_category
        if service_id is not APIHelper.SKIP:
            self.service_id = service_id
        if device_id is not APIHelper.SKIP:
            self.device_id = device_id
        if sale_id is not APIHelper.SKIP:
            self.sale_id = sale_id
        if poiid is not APIHelper.SKIP:
            self.poiid = poiid

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        message_category =\
            dictionary.get("MessageCategory")\
            if dictionary.get("MessageCategory")\
                else APIHelper.SKIP
        service_id =\
            dictionary.get("ServiceID")\
            if dictionary.get("ServiceID")\
                else APIHelper.SKIP
        device_id =\
            dictionary.get("DeviceID")\
            if dictionary.get("DeviceID")\
                else APIHelper.SKIP
        sale_id =\
            dictionary.get("SaleID")\
            if dictionary.get("SaleID")\
                else APIHelper.SKIP
        poiid =\
            dictionary.get("POIID")\
            if dictionary.get("POIID")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(message_category,
                   service_id,
                   device_id,
                   sale_id,
                   poiid)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _message_category=(
            self.message_category
            if hasattr(self, "message_category")
            else None
        )
        _service_id=(
            self.service_id
            if hasattr(self, "service_id")
            else None
        )
        _device_id=(
            self.device_id
            if hasattr(self, "device_id")
            else None
        )
        _sale_id=(
            self.sale_id
            if hasattr(self, "sale_id")
            else None
        )
        _poiid=(
            self.poiid
            if hasattr(self, "poiid")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"message_category={_message_category!r}, "
            f"service_id={_service_id!r}, "
            f"device_id={_device_id!r}, "
            f"sale_id={_sale_id!r}, "
            f"poiid={_poiid!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _message_category=(
            self.message_category
            if hasattr(self, "message_category")
            else None
        )
        _service_id=(
            self.service_id
            if hasattr(self, "service_id")
            else None
        )
        _device_id=(
            self.device_id
            if hasattr(self, "device_id")
            else None
        )
        _sale_id=(
            self.sale_id
            if hasattr(self, "sale_id")
            else None
        )
        _poiid=(
            self.poiid
            if hasattr(self, "poiid")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"message_category={_message_category!s}, "
            f"service_id={_service_id!s}, "
            f"device_id={_device_id!s}, "
            f"sale_id={_sale_id!s}, "
            f"poiid={_poiid!s}, "
            f")"
        )
