"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class MigratedStores(object):
    """Implementation of the 'MigratedStores' model.

    Attributes:
        business_line_id (str): The unique identifier of the business line associated
            with the migrated account holder in the balance platform.
        store_code (str): The unique identifier of the store associated with the
            migrated account holder in the classic integration.
        store_id (str): The unique identifier of the store associated with the
            migrated account holder in the balance platform.
        store_reference (str): Your reference for the store in the classic
            integration. The [Customer Area](https://ca-test.adyen.com/) uses this
            value for the store description.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "business_line_id": "businessLineId",
        "store_code": "storeCode",
        "store_id": "storeId",
        "store_reference": "storeReference",
    }

    _optionals = [
        "business_line_id",
        "store_code",
        "store_id",
        "store_reference",
    ]

    def __init__(
        self,
        business_line_id=APIHelper.SKIP,
        store_code=APIHelper.SKIP,
        store_id=APIHelper.SKIP,
        store_reference=APIHelper.SKIP):
        """Initialize a MigratedStores instance."""
        # Initialize members of the class
        if business_line_id is not APIHelper.SKIP:
            self.business_line_id = business_line_id
        if store_code is not APIHelper.SKIP:
            self.store_code = store_code
        if store_id is not APIHelper.SKIP:
            self.store_id = store_id
        if store_reference is not APIHelper.SKIP:
            self.store_reference = store_reference

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        business_line_id =\
            dictionary.get("businessLineId")\
            if dictionary.get("businessLineId")\
                else APIHelper.SKIP
        store_code =\
            dictionary.get("storeCode")\
            if dictionary.get("storeCode")\
                else APIHelper.SKIP
        store_id =\
            dictionary.get("storeId")\
            if dictionary.get("storeId")\
                else APIHelper.SKIP
        store_reference =\
            dictionary.get("storeReference")\
            if dictionary.get("storeReference")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(business_line_id,
                   store_code,
                   store_id,
                   store_reference)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _business_line_id=(
            self.business_line_id
            if hasattr(self, "business_line_id")
            else None
        )
        _store_code=(
            self.store_code
            if hasattr(self, "store_code")
            else None
        )
        _store_id=(
            self.store_id
            if hasattr(self, "store_id")
            else None
        )
        _store_reference=(
            self.store_reference
            if hasattr(self, "store_reference")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"business_line_id={_business_line_id!r}, "
            f"store_code={_store_code!r}, "
            f"store_id={_store_id!r}, "
            f"store_reference={_store_reference!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _business_line_id=(
            self.business_line_id
            if hasattr(self, "business_line_id")
            else None
        )
        _store_code=(
            self.store_code
            if hasattr(self, "store_code")
            else None
        )
        _store_id=(
            self.store_id
            if hasattr(self, "store_id")
            else None
        )
        _store_reference=(
            self.store_reference
            if hasattr(self, "store_reference")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"business_line_id={_business_line_id!s}, "
            f"store_code={_store_code!s}, "
            f"store_id={_store_id!s}, "
            f"store_reference={_store_reference!s}, "
            f")"
        )
