"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.links_element_9 import LinksElement9
from adyen.models.links_element_10 import LinksElement10
from adyen.models.links_element_11 import LinksElement11
from adyen.models.links_element_12 import LinksElement12
from adyen.models.links_element_13 import LinksElement13


class PaginationLinks(object):
    """Implementation of the 'PaginationLinks' model.

    Attributes:
        first (LinksElement9): The first page.
        last (LinksElement10): The last page.
        next (LinksElement11): The next page. Only present if there is a next page.
        prev (LinksElement12): The previous page. Only present if there is a previous
            page.
        mself (LinksElement13): The current page.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "first": "first",
        "last": "last",
        "mself": "self",
        "next": "next",
        "prev": "prev",
    }

    _optionals = [
        "next",
        "prev",
    ]

    def __init__(
        self,
        first=None,
        last=None,
        mself=None,
        next=APIHelper.SKIP,
        prev=APIHelper.SKIP):
        """Initialize a PaginationLinks instance."""
        # Initialize members of the class
        self.first = first
        self.last = last
        if next is not APIHelper.SKIP:
            self.next = next
        if prev is not APIHelper.SKIP:
            self.prev = prev
        self.mself = mself

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        first =\
            LinksElement9.from_dictionary(
                dictionary.get("first"))\
                if dictionary.get("first") else None
        last =\
            LinksElement10.from_dictionary(
                dictionary.get("last"))\
                if dictionary.get("last") else None
        mself =\
            LinksElement13.from_dictionary(
                dictionary.get("self"))\
                if dictionary.get("self") else None
        next =\
            LinksElement11.from_dictionary(
                dictionary.get("next"))\
                if "next" in dictionary.keys()\
                else APIHelper.SKIP
        prev =\
            LinksElement12.from_dictionary(
                dictionary.get("prev"))\
                if "prev" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(first,
                   last,
                   mself,
                   next,
                   prev)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _first=self.first
        _last=self.last
        _next=(
            self.next
            if hasattr(self, "next")
            else None
        )
        _prev=(
            self.prev
            if hasattr(self, "prev")
            else None
        )
        _mself=self.mself
        return (
            f"{self.__class__.__name__}("
            f"first={_first!r}, "
            f"last={_last!r}, "
            f"next={_next!r}, "
            f"prev={_prev!r}, "
            f"mself={_mself!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _first=self.first
        _last=self.last
        _next=(
            self.next
            if hasattr(self, "next")
            else None
        )
        _prev=(
            self.prev
            if hasattr(self, "prev")
            else None
        )
        _mself=self.mself
        return (
            f"{self.__class__.__name__}("
            f"first={_first!s}, "
            f"last={_last!s}, "
            f"next={_next!s}, "
            f"prev={_prev!s}, "
            f"mself={_mself!s}, "
            f")"
        )
