"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class PayToInfo1(object):
    """Implementation of the 'PayToInfo1' model.

    Details to provide if `type` is **payto**.

    Attributes:
        merchant_name (str): Merchant name displayed to the shopper in the Agreements
        pay_to_purpose (str): Represents the purpose of the Agreements created, it
            relates to the business type **Allowed values**: mortgage, utility, loan,
            gambling, retail, salary, personal, government, pension, tax, other

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "merchant_name": "merchantName",
        "pay_to_purpose": "payToPurpose",
    }

    def __init__(
        self,
        merchant_name=None,
        pay_to_purpose=None):
        """Initialize a PayToInfo1 instance."""
        # Initialize members of the class
        self.merchant_name = merchant_name
        self.pay_to_purpose = pay_to_purpose

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        merchant_name =\
            dictionary.get("merchantName")\
            if dictionary.get("merchantName")\
                else None
        pay_to_purpose =\
            dictionary.get("payToPurpose")\
            if dictionary.get("payToPurpose")\
                else None

        # Return an object of this model
        return cls(merchant_name,
                   pay_to_purpose)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _merchant_name=self.merchant_name
        _pay_to_purpose=self.pay_to_purpose
        return (
            f"{self.__class__.__name__}("
            f"merchant_name={_merchant_name!r}, "
            f"pay_to_purpose={_pay_to_purpose!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _merchant_name=self.merchant_name
        _pay_to_purpose=self.pay_to_purpose
        return (
            f"{self.__class__.__name__}("
            f"merchant_name={_merchant_name!s}, "
            f"pay_to_purpose={_pay_to_purpose!s}, "
            f")"
        )
