"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class Payment1(object):
    """Implementation of the 'Payment1' model.

    Attributes:
        contactless_currency (str): The default currency for contactless payments on
            the payment terminal, in three-letter [ISO
            4217](https://en.wikipedia.org/wiki/ISO_4217) currency code format.
            Contact Adyen before you update this setting for the first time. To
            enable you to change the contactless currency, we first need to check if
            you meet the compliance requirements.
        hide_minor_units_in_currencies (List[str]): Hides the minor units for the
            listed [ISO currency codes](https://en.wikipedia.org/wiki/ISO_4217).

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "contactless_currency": "contactlessCurrency",
        "hide_minor_units_in_currencies": "hideMinorUnitsInCurrencies",
    }

    _optionals = [
        "contactless_currency",
        "hide_minor_units_in_currencies",
    ]

    def __init__(
        self,
        contactless_currency=APIHelper.SKIP,
        hide_minor_units_in_currencies=APIHelper.SKIP):
        """Initialize a Payment1 instance."""
        # Initialize members of the class
        if contactless_currency is not APIHelper.SKIP:
            self.contactless_currency = contactless_currency
        if hide_minor_units_in_currencies is not APIHelper.SKIP:
            self.hide_minor_units_in_currencies = hide_minor_units_in_currencies

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        contactless_currency =\
            dictionary.get("contactlessCurrency")\
            if dictionary.get("contactlessCurrency")\
                else APIHelper.SKIP
        hide_minor_units_in_currencies =\
            dictionary.get("hideMinorUnitsInCurrencies")\
            if dictionary.get("hideMinorUnitsInCurrencies")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(contactless_currency,
                   hide_minor_units_in_currencies)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _contactless_currency=(
            self.contactless_currency
            if hasattr(self, "contactless_currency")
            else None
        )
        _hide_minor_units_in_currencies=(
            self.hide_minor_units_in_currencies
            if hasattr(self, "hide_minor_units_in_currencies")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"contactless_currency={_contactless_currency!r}, "
            f"hide_minor_units_in_currencies={_hide_minor_units_in_currencies!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _contactless_currency=(
            self.contactless_currency
            if hasattr(self, "contactless_currency")
            else None
        )
        _hide_minor_units_in_currencies=(
            self.hide_minor_units_in_currencies
            if hasattr(self, "hide_minor_units_in_currencies")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"contactless_currency={_contactless_currency!s}, "
            f"hide_minor_units_in_currencies={_hide_minor_units_in_currencies!s}, "
            f")"
        )
