"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.card_data_1 import CardData1
from adyen.models.check_data_1 import CheckData1
from adyen.models.mobile_data_1 import MobileData1
from adyen.models.stored_value_account_id import (
    StoredValueAccountID,
)


class PaymentInstrumentData(object):
    """Implementation of the 'PaymentInstrumentData' model.

    Data related to the instrument of payment for the transaction.
    Sent in the result of the payment transaction. For a card, it could also be sent
    in the `CardAcquisition` response, to be processed by the Sale System.

    Attributes:
        payment_instrument_type (PaymentInstrumentType11Enum): Type of payment
            instrument. Possible values: * **Card** * **Cash** * **Check** *
            **Mobile** * **StoredValue**
        protected_card_data (str): Sensitive information related to the payment card,
            protected by CMS. SensitiveCardData protected by CMS EnvelopedData.
        card_data (CardData1): Information related to the payment card used for the
            transaction. If PaymentInstrumentType is Card.
        check_data (CheckData1): Information related to the paper check used for the
            transaction. If PaymentInstrumentType is Check.
        mobile_data (MobileData1): Information related to the mobile for the payment
            transaction. If PaymentInstrumentType is Mobile.
        stored_value_account_id (StoredValueAccountID): Identification of the stored
            value account or the stored value card and the associated product sold by
            the Sale System for stored value requests.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "payment_instrument_type": "PaymentInstrumentType",
        "protected_card_data": "ProtectedCardData",
        "card_data": "CardData",
        "check_data": "CheckData",
        "mobile_data": "MobileData",
        "stored_value_account_id": "StoredValueAccountID",
    }

    _optionals = [
        "protected_card_data",
        "card_data",
        "check_data",
        "mobile_data",
        "stored_value_account_id",
    ]

    def __init__(
        self,
        payment_instrument_type=None,
        protected_card_data=APIHelper.SKIP,
        card_data=APIHelper.SKIP,
        check_data=APIHelper.SKIP,
        mobile_data=APIHelper.SKIP,
        stored_value_account_id=APIHelper.SKIP):
        """Initialize a PaymentInstrumentData instance."""
        # Initialize members of the class
        self.payment_instrument_type = payment_instrument_type
        if protected_card_data is not APIHelper.SKIP:
            self.protected_card_data = protected_card_data
        if card_data is not APIHelper.SKIP:
            self.card_data = card_data
        if check_data is not APIHelper.SKIP:
            self.check_data = check_data
        if mobile_data is not APIHelper.SKIP:
            self.mobile_data = mobile_data
        if stored_value_account_id is not APIHelper.SKIP:
            self.stored_value_account_id = stored_value_account_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        payment_instrument_type =\
            dictionary.get("PaymentInstrumentType")\
            if dictionary.get("PaymentInstrumentType")\
                else None
        protected_card_data =\
            dictionary.get("ProtectedCardData")\
            if dictionary.get("ProtectedCardData")\
                else APIHelper.SKIP
        card_data =\
            CardData1.from_dictionary(
                dictionary.get("CardData"))\
                if "CardData" in dictionary.keys()\
                else APIHelper.SKIP
        check_data =\
            CheckData1.from_dictionary(
                dictionary.get("CheckData"))\
                if "CheckData" in dictionary.keys()\
                else APIHelper.SKIP
        mobile_data =\
            MobileData1.from_dictionary(
                dictionary.get("MobileData"))\
                if "MobileData" in dictionary.keys()\
                else APIHelper.SKIP
        stored_value_account_id =\
            StoredValueAccountID.from_dictionary(
                dictionary.get("StoredValueAccountID"))\
                if "StoredValueAccountID" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(payment_instrument_type,
                   protected_card_data,
                   card_data,
                   check_data,
                   mobile_data,
                   stored_value_account_id)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _payment_instrument_type=self.payment_instrument_type
        _protected_card_data=(
            self.protected_card_data
            if hasattr(self, "protected_card_data")
            else None
        )
        _card_data=(
            self.card_data
            if hasattr(self, "card_data")
            else None
        )
        _check_data=(
            self.check_data
            if hasattr(self, "check_data")
            else None
        )
        _mobile_data=(
            self.mobile_data
            if hasattr(self, "mobile_data")
            else None
        )
        _stored_value_account_id=(
            self.stored_value_account_id
            if hasattr(self, "stored_value_account_id")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"payment_instrument_type={_payment_instrument_type!r}, "
            f"protected_card_data={_protected_card_data!r}, "
            f"card_data={_card_data!r}, "
            f"check_data={_check_data!r}, "
            f"mobile_data={_mobile_data!r}, "
            f"stored_value_account_id={_stored_value_account_id!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _payment_instrument_type=self.payment_instrument_type
        _protected_card_data=(
            self.protected_card_data
            if hasattr(self, "protected_card_data")
            else None
        )
        _card_data=(
            self.card_data
            if hasattr(self, "card_data")
            else None
        )
        _check_data=(
            self.check_data
            if hasattr(self, "check_data")
            else None
        )
        _mobile_data=(
            self.mobile_data
            if hasattr(self, "mobile_data")
            else None
        )
        _stored_value_account_id=(
            self.stored_value_account_id
            if hasattr(self, "stored_value_account_id")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"payment_instrument_type={_payment_instrument_type!s}, "
            f"protected_card_data={_protected_card_data!s}, "
            f"card_data={_card_data!s}, "
            f"check_data={_check_data!s}, "
            f"mobile_data={_mobile_data!s}, "
            f"stored_value_account_id={_stored_value_account_id!s}, "
            f")"
        )
