"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class PaymentSource2(object):
    """Implementation of the 'PaymentSource2' enum.

    The source used to obtain the payload. Possible values: `qr`, `redirect`, and
    `pushNotification`.

    Attributes:
        REDIRECT: The enum member of type str.
        QR: The enum member of type str.
        PUSHNOTIFICATION: The enum member of type str.

    """

    REDIRECT = "redirect"

    QR = "qr"

    PUSHNOTIFICATION = "pushNotification"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
