"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class PciSigningResponse(object):
    """Implementation of the 'PciSigningResponse' model.

    Attributes:
        pci_questionnaire_ids (List[str]): The unique identifiers of the signed PCI
            documents.
        signed_by (str): The [legal entity
            ID](https://docs.adyen.com/api-explorer/#/legalentity/latest/post/legalEnt
            ities__resParam_id) of the individual who signed the PCI questionnaire.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "pci_questionnaire_ids": "pciQuestionnaireIds",
        "signed_by": "signedBy",
    }

    _optionals = [
        "pci_questionnaire_ids",
        "signed_by",
    ]

    def __init__(
        self,
        pci_questionnaire_ids=APIHelper.SKIP,
        signed_by=APIHelper.SKIP):
        """Initialize a PciSigningResponse instance."""
        # Initialize members of the class
        if pci_questionnaire_ids is not APIHelper.SKIP:
            self.pci_questionnaire_ids = pci_questionnaire_ids
        if signed_by is not APIHelper.SKIP:
            self.signed_by = signed_by

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        pci_questionnaire_ids =\
            dictionary.get("pciQuestionnaireIds")\
            if dictionary.get("pciQuestionnaireIds")\
                else APIHelper.SKIP
        signed_by =\
            dictionary.get("signedBy")\
            if dictionary.get("signedBy")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(pci_questionnaire_ids,
                   signed_by)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _pci_questionnaire_ids=(
            self.pci_questionnaire_ids
            if hasattr(self, "pci_questionnaire_ids")
            else None
        )
        _signed_by=(
            self.signed_by
            if hasattr(self, "signed_by")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"pci_questionnaire_ids={_pci_questionnaire_ids!r}, "
            f"signed_by={_signed_by!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _pci_questionnaire_ids=(
            self.pci_questionnaire_ids
            if hasattr(self, "pci_questionnaire_ids")
            else None
        )
        _signed_by=(
            self.signed_by
            if hasattr(self, "signed_by")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"pci_questionnaire_ids={_pci_questionnaire_ids!s}, "
            f"signed_by={_signed_by!s}, "
            f")"
        )
