"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.max_amount_3 import MaxAmount3
from adyen.models.single_transaction_limit import (
    SingleTransactionLimit,
)


class PermitRestriction2(object):
    """Implementation of the 'PermitRestriction2' model.

    Permit level restriction overrides.

    Attributes:
        max_amount (MaxAmount3): The model property of type MaxAmount3.
        single_transaction_limit (SingleTransactionLimit): The model property of type
            SingleTransactionLimit.
        single_use (bool): Only a single payment can be made using this permit if set
            to true, otherwise multiple payments are allowed.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "max_amount": "maxAmount",
        "single_transaction_limit": "singleTransactionLimit",
        "single_use": "singleUse",
    }

    _optionals = [
        "max_amount",
        "single_transaction_limit",
        "single_use",
    ]

    def __init__(
        self,
        max_amount=APIHelper.SKIP,
        single_transaction_limit=APIHelper.SKIP,
        single_use=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PermitRestriction2 instance."""
        # Initialize members of the class
        if max_amount is not APIHelper.SKIP:
            self.max_amount = max_amount
        if single_transaction_limit is not APIHelper.SKIP:
            self.single_transaction_limit = single_transaction_limit
        if single_use is not APIHelper.SKIP:
            self.single_use = single_use

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        max_amount =\
            MaxAmount3.from_dictionary(
                dictionary.get("maxAmount"))\
                if "maxAmount" in dictionary.keys()\
                else APIHelper.SKIP
        single_transaction_limit =\
            SingleTransactionLimit.from_dictionary(
                dictionary.get("singleTransactionLimit"))\
                if "singleTransactionLimit" in dictionary.keys()\
                else APIHelper.SKIP
        single_use =\
            dictionary.get("singleUse")\
            if "singleUse" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(max_amount,
                   single_transaction_limit,
                   single_use,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _max_amount=(
            self.max_amount
            if hasattr(self, "max_amount")
            else None
        )
        _single_transaction_limit=(
            self.single_transaction_limit
            if hasattr(self, "single_transaction_limit")
            else None
        )
        _single_use=(
            self.single_use
            if hasattr(self, "single_use")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"max_amount={_max_amount!r}, "
            f"single_transaction_limit={_single_transaction_limit!r}, "
            f"single_use={_single_use!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _max_amount=(
            self.max_amount
            if hasattr(self, "max_amount")
            else None
        )
        _single_transaction_limit=(
            self.single_transaction_limit
            if hasattr(self, "single_transaction_limit")
            else None
        )
        _single_use=(
            self.single_use
            if hasattr(self, "single_use")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"max_amount={_max_amount!s}, "
            f"single_transaction_limit={_single_transaction_limit!s}, "
            f"single_use={_single_use!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
