"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Plan1Enum(object):
    """Implementation of the 'Plan1' enum.

    Attributes:
        BONUS: The enum member of type str.
        BUYNOW_PAYLATER: The enum member of type str.
        INTERES_REFUND_PRCTG: The enum member of type str.
        INTEREST_BONUS: The enum member of type str.
        NOINTERES_REFUND_PRCTG: The enum member of type str.
        NOINTEREST_BONUS: The enum member of type str.
        REFUND_PRCTG: The enum member of type str.
        REGULAR: The enum member of type str.
        REVOLVING: The enum member of type str.
        WITH_INTEREST: The enum member of type str.

    """

    BONUS = "bonus"

    BUYNOW_PAYLATER = "buynow_paylater"

    INTERES_REFUND_PRCTG = "interes_refund_prctg"

    INTEREST_BONUS = "interest_bonus"

    NOINTERES_REFUND_PRCTG = "nointeres_refund_prctg"

    NOINTEREST_BONUS = "nointerest_bonus"

    REFUND_PRCTG = "refund_prctg"

    REGULAR = "regular"

    REVOLVING = "revolving"

    WITH_INTEREST = "with_interest"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
