"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class Recurring(object):
    """Implementation of the 'Recurring' model.

    The recurring settings for the payment. Use this property when you want to enable
    [recurring
    payments](https://docs.adyen.com/classic-integration/recurring-payments)., A
    container for the type of a recurring contract to be retrieved.
    The contract value needs to match the contract value submitted in the payment
    transaction used to create a recurring contract.
    However, if `ONECLICK,RECURRING` is the original contract definition in the
    initial payment, then `contract` should take either `ONECLICK` or `RECURRING`,
    depending on whether or not you want the shopper to enter their card's security
    code when they finalize their purchase., A container for the type of recurring
    contract to be retrieved.
    The recurring.contract must be set to `PAYOUT`, A container for the type of
    recurring contract to be retrieved.
    The `recurring.contract` must be set to "PAYOUT"., The recurring settings for the
    payment. Use this property when you want to enable [recurring
    payments](https://docs.adyen.com/classic-integration/recurring-payments)., The
    recurring settings for the payment. Use this property when you want to enable
    [recurring payments](https://docs.adyen.com/online-payments/tokenization).

    Attributes:
        contract (ContractEnum): The type of recurring contract to be used. Possible
            values: * `ONECLICK` – Payment details can be used to initiate a
            one-click payment, where the shopper enters the [card security code
            (CVC/CVV)](https://docs.adyen.com/payments-fundamentals/payment-glossary#c
            ard-security-code-cvc-cvv-cid). * `RECURRING` – Payment details can be
            used without the card security code to initiate [card-not-present
            transactions](https://docs.adyen.com/payments-fundamentals/payment-glossar
            y#card-not-present-cnp). * `ONECLICK,RECURRING` – Payment details can be
            used regardless of whether the shopper is on your site or not. * `PAYOUT`
            – Payment details can be used to [make a
            payout](https://docs.adyen.com/online-payments/online-payouts). *
            `EXTERNAL` - Use this when you store payment details and send the raw
            card number or network token directly in your API request.
        recurring_detail_name (str): A descriptive name for this detail.
        recurring_expiry (datetime): Date after which no further authorisations shall
            be performed. Only for 3D Secure 2.
        recurring_frequency (str): Minimum number of days between authorisations.
            Only for 3D Secure 2.
        token_service (TokenServiceEnum): The name of the token service.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "contract": "contract",
        "recurring_detail_name": "recurringDetailName",
        "recurring_expiry": "recurringExpiry",
        "recurring_frequency": "recurringFrequency",
        "token_service": "tokenService",
    }

    _optionals = [
        "contract",
        "recurring_detail_name",
        "recurring_expiry",
        "recurring_frequency",
        "token_service",
    ]

    def __init__(
        self,
        contract=APIHelper.SKIP,
        recurring_detail_name=APIHelper.SKIP,
        recurring_expiry=APIHelper.SKIP,
        recurring_frequency=APIHelper.SKIP,
        token_service=APIHelper.SKIP):
        """Initialize a Recurring instance."""
        # Initialize members of the class
        if contract is not APIHelper.SKIP:
            self.contract = contract
        if recurring_detail_name is not APIHelper.SKIP:
            self.recurring_detail_name = recurring_detail_name
        if recurring_expiry is not APIHelper.SKIP:
            self.recurring_expiry =\
                 APIHelper.apply_datetime_converter(
                recurring_expiry, APIHelper.RFC3339DateTime)\
                 if recurring_expiry else None
        if recurring_frequency is not APIHelper.SKIP:
            self.recurring_frequency = recurring_frequency
        if token_service is not APIHelper.SKIP:
            self.token_service = token_service

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        contract =\
            dictionary.get("contract")\
            if dictionary.get("contract")\
                else APIHelper.SKIP
        recurring_detail_name =\
            dictionary.get("recurringDetailName")\
            if dictionary.get("recurringDetailName")\
                else APIHelper.SKIP
        recurring_expiry = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("recurringExpiry")).datetime\
            if dictionary.get("recurringExpiry") else APIHelper.SKIP
        recurring_frequency =\
            dictionary.get("recurringFrequency")\
            if dictionary.get("recurringFrequency")\
                else APIHelper.SKIP
        token_service =\
            dictionary.get("tokenService")\
            if dictionary.get("tokenService")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(contract,
                   recurring_detail_name,
                   recurring_expiry,
                   recurring_frequency,
                   token_service)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _contract=(
            self.contract
            if hasattr(self, "contract")
            else None
        )
        _recurring_detail_name=(
            self.recurring_detail_name
            if hasattr(self, "recurring_detail_name")
            else None
        )
        _recurring_expiry=(
            self.recurring_expiry
            if hasattr(self, "recurring_expiry")
            else None
        )
        _recurring_frequency=(
            self.recurring_frequency
            if hasattr(self, "recurring_frequency")
            else None
        )
        _token_service=(
            self.token_service
            if hasattr(self, "token_service")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"contract={_contract!r}, "
            f"recurring_detail_name={_recurring_detail_name!r}, "
            f"recurring_expiry={_recurring_expiry!r}, "
            f"recurring_frequency={_recurring_frequency!r}, "
            f"token_service={_token_service!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _contract=(
            self.contract
            if hasattr(self, "contract")
            else None
        )
        _recurring_detail_name=(
            self.recurring_detail_name
            if hasattr(self, "recurring_detail_name")
            else None
        )
        _recurring_expiry=(
            self.recurring_expiry
            if hasattr(self, "recurring_expiry")
            else None
        )
        _recurring_frequency=(
            self.recurring_frequency
            if hasattr(self, "recurring_frequency")
            else None
        )
        _token_service=(
            self.token_service
            if hasattr(self, "token_service")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"contract={_contract!s}, "
            f"recurring_detail_name={_recurring_detail_name!s}, "
            f"recurring_expiry={_recurring_expiry!s}, "
            f"recurring_frequency={_recurring_frequency!s}, "
            f"token_service={_token_service!s}, "
            f")"
        )
