"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.delegated_authentication_data import (
    DelegatedAuthenticationData,
)


class RegisterScaRequest(object):
    """Implementation of the 'RegisterSCARequest' model.

    Attributes:
        name (str): The name of the SCA device that you are registering. You can use
            it to help your users identify the device.  If you do not specify a
            `name`, Adyen automatically generates one.
        payment_instrument_id (str): The unique identifier of the payment instrument
            for which you are registering the SCA device.
        strong_customer_authentication (DelegatedAuthenticationData): The model
            property of type DelegatedAuthenticationData.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "payment_instrument_id": "paymentInstrumentId",
        "strong_customer_authentication": "strongCustomerAuthentication",
        "name": "name",
    }

    _optionals = [
        "name",
    ]

    def __init__(
        self,
        payment_instrument_id=None,
        strong_customer_authentication=None,
        name=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a RegisterScaRequest instance."""
        # Initialize members of the class
        if name is not APIHelper.SKIP:
            self.name = name
        self.payment_instrument_id = payment_instrument_id
        self.strong_customer_authentication = strong_customer_authentication

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        payment_instrument_id =\
            dictionary.get("paymentInstrumentId")\
            if dictionary.get("paymentInstrumentId")\
                else None
        strong_customer_authentication =\
            DelegatedAuthenticationData.from_dictionary(
                dictionary.get("strongCustomerAuthentication"))\
                if dictionary.get("strongCustomerAuthentication") else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(payment_instrument_id,
                   strong_customer_authentication,
                   name,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _payment_instrument_id=self.payment_instrument_id
        _strong_customer_authentication=self.strong_customer_authentication
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!r}, "
            f"payment_instrument_id={_payment_instrument_id!r}, "
            f"strong_customer_authentication={_strong_customer_authentication!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _payment_instrument_id=self.payment_instrument_id
        _strong_customer_authentication=self.strong_customer_authentication
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!s}, "
            f"payment_instrument_id={_payment_instrument_id!s}, "
            f"strong_customer_authentication={_strong_customer_authentication!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
