"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class RepaymentTerm(object):
    """Implementation of the 'RepaymentTerm' model.

    An object containing the details of the configuration for repayment term.,
    Contains information about the time period in which your user must repay the
    total amount of the grant.

    Attributes:
        estimated_days (int): The estimated term for repaying the grant, in days.
        maximum_days (int): The maximum term for repaying the grant, in days. Only
            applies when `contractType` is **loan**.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "estimated_days": "estimatedDays",
        "maximum_days": "maximumDays",
    }

    _optionals = [
        "maximum_days",
    ]

    def __init__(
        self,
        estimated_days=None,
        maximum_days=APIHelper.SKIP):
        """Initialize a RepaymentTerm instance."""
        # Initialize members of the class
        self.estimated_days = estimated_days
        if maximum_days is not APIHelper.SKIP:
            self.maximum_days = maximum_days

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        estimated_days =\
            dictionary.get("estimatedDays")\
            if dictionary.get("estimatedDays")\
                else None
        maximum_days =\
            dictionary.get("maximumDays")\
            if dictionary.get("maximumDays")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(estimated_days,
                   maximum_days)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _estimated_days=self.estimated_days
        _maximum_days=(
            self.maximum_days
            if hasattr(self, "maximum_days")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"estimated_days={_estimated_days!r}, "
            f"maximum_days={_maximum_days!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _estimated_days=self.estimated_days
        _maximum_days=(
            self.maximum_days
            if hasattr(self, "maximum_days")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"estimated_days={_estimated_days!s}, "
            f"maximum_days={_maximum_days!s}, "
            f")"
        )
