"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class RiskScores(object):
    """Implementation of the 'RiskScores' model.

    Attributes:
        mastercard (int): Transaction risk score provided by Mastercard. Values
            provided by Mastercard range between 0 (lowest risk) to 998 (highest
            risk).
        visa (int): Transaction risk score provided by Visa. Values provided by Visa
            range between 01 (lowest risk) to 99 (highest risk).

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mastercard": "mastercard",
        "visa": "visa",
    }

    _optionals = [
        "mastercard",
        "visa",
    ]

    def __init__(
        self,
        mastercard=APIHelper.SKIP,
        visa=APIHelper.SKIP):
        """Initialize a RiskScores instance."""
        # Initialize members of the class
        if mastercard is not APIHelper.SKIP:
            self.mastercard = mastercard
        if visa is not APIHelper.SKIP:
            self.visa = visa

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mastercard =\
            dictionary.get("mastercard")\
            if dictionary.get("mastercard")\
                else APIHelper.SKIP
        visa =\
            dictionary.get("visa")\
            if dictionary.get("visa")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(mastercard,
                   visa)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mastercard=(
            self.mastercard
            if hasattr(self, "mastercard")
            else None
        )
        _visa=(
            self.visa
            if hasattr(self, "visa")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"mastercard={_mastercard!r}, "
            f"visa={_visa!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mastercard=(
            self.mastercard
            if hasattr(self, "mastercard")
            else None
        )
        _visa=(
            self.visa
            if hasattr(self, "visa")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"mastercard={_mastercard!s}, "
            f"visa={_visa!s}, "
            f")"
        )
