"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class ScaEntityType1(object):
    """Implementation of the 'ScaEntityType1' enum.

    The type of entity you are associating the device with.
    Possible values: **accountHolder**, **legalEntity** or **paymentInstrument**.

    Attributes:
        ACCOUNTHOLDER: The enum member of type str.
        LEGALENTITY: The enum member of type str.
        PAYMENTINSTRUMENT: The enum member of type str.

    """

    ACCOUNTHOLDER = "accountHolder"

    LEGALENTITY = "legalEntity"

    PAYMENTINSTRUMENT = "paymentInstrument"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
