"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class ScaInformation1(object):
    """Implementation of the 'ScaInformation1' model.

    Information for the Strong Customer Authentication (SCA)

    Attributes:
        exemption (ScaExemptionEnum): The type of exemption for Strong Customer
            Authentication (SCA). Possible values: * **lowerLimit**: the newly
            created limit is lower than the existing limit. * **notRegulated**: the
            limit is created in a country, region, or industry where it is not
            mandated by law to use SCA. * **setByPlatform**: you set a limit for one
            of your user's balance accounts, or for your balance platform. *
            **initialLimit**: there are no existing transfer limits set on the
            balance account or balance platform. * **alreadyPerformed**: you are
            confident about your user's identity and do not need to verify this using
            SCA.
        status (ScaStatusEnum): The status of Strong Customer Authentication (SCA).
            Possible values: * **notPerformed**: the requester was unable to
            successfully authenticate the request using SCA, or has an SCA exemption.
            * **pending**: the request is pending SCA authentication. *
            **performed**: the request is successfully authenticated using SCA.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "status": "status",
        "exemption": "exemption",
    }

    _optionals = [
        "exemption",
    ]

    def __init__(
        self,
        status=None,
        exemption=APIHelper.SKIP):
        """Initialize a ScaInformation1 instance."""
        # Initialize members of the class
        if exemption is not APIHelper.SKIP:
            self.exemption = exemption
        self.status = status

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else None
        exemption =\
            dictionary.get("exemption")\
            if dictionary.get("exemption")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(status,
                   exemption)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _exemption=(
            self.exemption
            if hasattr(self, "exemption")
            else None
        )
        _status=self.status
        return (
            f"{self.__class__.__name__}("
            f"exemption={_exemption!r}, "
            f"status={_status!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _exemption=(
            self.exemption
            if hasattr(self, "exemption")
            else None
        )
        _status=self.status
        return (
            f"{self.__class__.__name__}("
            f"exemption={_exemption!s}, "
            f"status={_status!s}, "
            f")"
        )
