"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class ShopperIdPaymentMethod(object):
    """Implementation of the 'ShopperIdPaymentMethod' model.

    Attributes:
        mtype (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
    }

    _optionals = [
        "mtype",
    ]

    def __init__(
        self,
        mtype="ShopperIdPaymentMethod"):
        """Initialize a ShopperIdPaymentMethod instance."""
        # Initialize members of the class
        self.mtype = mtype

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        discriminators = {
            "payTo": PayToPaymentMethod.from_dictionary,
            "upi_collect": UPIPaymentMethod.from_dictionary,
        }
        unboxer = discriminators.get(dictionary.get("type"))

        # Delegate unboxing to another function if a discriminator
        # value for a child class is present.
        if unboxer:
            return unboxer(dictionary)

        # Extract variables from the dictionary
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else "ShopperIdPaymentMethod"

        # Return an object of this model
        return cls(mtype)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!s}, "
            f")"
        )

class PayToPaymentMethod(ShopperIdPaymentMethod):
    """Implementation of the 'PayToPaymentMethod' model.
    NOTE: This class inherits from 'ShopperIdPaymentMethod'.

    Attributes:
        shopper_reference (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "shopper_reference": "shopperReference",
        "mtype": "type",
    }

    _optionals = [
        "shopper_reference",
    ]
    _optionals.extend(ShopperIdPaymentMethod._optionals)

    def __init__(
        self,
        shopper_reference=APIHelper.SKIP,
        mtype="payTo"):
        """Initialize a PayToPaymentMethod instance."""
        # Initialize members of the class
        if shopper_reference is not APIHelper.SKIP:
            self.shopper_reference = shopper_reference

        # Call the constructor for the base class
        super(PayToPaymentMethod, self).__init__(
            mtype)

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        shopper_reference =\
            dictionary.get("shopperReference")\
            if dictionary.get("shopperReference")\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else "payTo"

        # Return an object of this model
        return cls(shopper_reference,
                   mtype)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _shopper_reference=(
            self.shopper_reference
            if hasattr(self, "shopper_reference")
            else None
        )
        _base_repr = super().__repr__()
        _base_repr = _base_repr[_base_repr.find("(") + 1:-1]
        return (
            f"{self.__class__.__name__}("
            f"base_repr={_base_repr!r}, "
            f"shopper_reference={_shopper_reference!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _shopper_reference=(
            self.shopper_reference
            if hasattr(self, "shopper_reference")
            else None
        )
        _base_str = super().__str__()
        _base_str = _base_str[_base_str.find("(") + 1:-1]
        return (
            f"{self.__class__.__name__}("
            f"base_str={_base_str!s}, "
            f"shopper_reference={_shopper_reference!s}, "
            f")"
        )

class UPIPaymentMethod(ShopperIdPaymentMethod):
    """Implementation of the 'UPIPaymentMethod' model.
    NOTE: This class inherits from 'ShopperIdPaymentMethod'.

    Attributes:
        virtual_payment_address (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "virtual_payment_address": "virtualPaymentAddress",
        "mtype": "type",
    }

    _optionals = [
        "virtual_payment_address",
    ]
    _optionals.extend(ShopperIdPaymentMethod._optionals)

    def __init__(
        self,
        virtual_payment_address=APIHelper.SKIP,
        mtype="upi_collect"):
        """Initialize a UPIPaymentMethod instance."""
        # Initialize members of the class
        if virtual_payment_address is not APIHelper.SKIP:
            self.virtual_payment_address = virtual_payment_address

        # Call the constructor for the base class
        super(UPIPaymentMethod, self).__init__(
            mtype)

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        virtual_payment_address =\
            dictionary.get("virtualPaymentAddress")\
            if dictionary.get("virtualPaymentAddress")\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else "upi_collect"

        # Return an object of this model
        return cls(virtual_payment_address,
                   mtype)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _virtual_payment_address=(
            self.virtual_payment_address
            if hasattr(self, "virtual_payment_address")
            else None
        )
        _base_repr = super().__repr__()
        _base_repr = _base_repr[_base_repr.find("(") + 1:-1]
        return (
            f"{self.__class__.__name__}("
            f"base_repr={_base_repr!r}, "
            f"virtual_payment_address={_virtual_payment_address!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _virtual_payment_address=(
            self.virtual_payment_address
            if hasattr(self, "virtual_payment_address")
            else None
        )
        _base_str = super().__str__()
        _base_str = _base_str[_base_str.find("(") + 1:-1]
        return (
            f"{self.__class__.__name__}("
            f"base_str={_base_str!s}, "
            f"virtual_payment_address={_virtual_payment_address!s}, "
            f")"
        )
