"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.amount_31 import Amount31


class Split1(object):
    """Implementation of the 'Split1' model.

    Attributes:
        account (str): The unique identifier of the account to which the split amount
            is booked. Required if `type` is **MarketPlace** or **BalanceAccount**.
            * [Classic Platforms
            integration](https://docs.adyen.com/classic-platforms): The
            [`accountCode`](https://docs.adyen.com/api-explorer/Account/latest/post/up
            dateAccount#request-accountCode) of the account to which the split amount
            is booked. * [Balance
            Platform](https://docs.adyen.com/adyen-for-platforms-model): The
            [`balanceAccountId`](https://docs.adyen.com/api-explorer/balanceplatform/l
            atest/get/balanceAccounts/_id_#path-id) of the account to which the split
            amount is booked.
        amount (Amount31): The model property of type Amount31.
        description (str): Your description for the split item.
        reference (str): Your unique reference for the part of the payment booked to
            the specified `account`.  This is required if `type` is **MarketPlace**
            ([Classic Platforms
            integration](https://docs.adyen.com/classic-platforms)) or
            **BalanceAccount** ([Balance
            Platform](https://docs.adyen.com/adyen-for-platforms-model)).  For the
            other types, we also recommend providing a **unique** reference so you
            can reconcile the split and the associated payment in the transaction
            overview and in the reports.
        mtype (Type15): The model property of type Type15.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
        "account": "account",
        "amount": "amount",
        "description": "description",
        "reference": "reference",
    }

    _optionals = [
        "account",
        "amount",
        "description",
        "reference",
    ]

    def __init__(
        self,
        mtype=None,
        account=APIHelper.SKIP,
        amount=APIHelper.SKIP,
        description=APIHelper.SKIP,
        reference=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Split1 instance."""
        # Initialize members of the class
        if account is not APIHelper.SKIP:
            self.account = account
        if amount is not APIHelper.SKIP:
            self.amount = amount
        if description is not APIHelper.SKIP:
            self.description = description
        if reference is not APIHelper.SKIP:
            self.reference = reference
        self.mtype = mtype

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        account =\
            dictionary.get("account")\
            if dictionary.get("account")\
                else APIHelper.SKIP
        amount =\
            Amount31.from_dictionary(
                dictionary.get("amount"))\
                if "amount" in dictionary.keys()\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        reference =\
            dictionary.get("reference")\
            if dictionary.get("reference")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(mtype,
                   account,
                   amount,
                   description,
                   reference,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account=(
            self.account
            if hasattr(self, "account")
            else None
        )
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _reference=(
            self.reference
            if hasattr(self, "reference")
            else None
        )
        _mtype=self.mtype
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account={_account!r}, "
            f"amount={_amount!r}, "
            f"description={_description!r}, "
            f"reference={_reference!r}, "
            f"mtype={_mtype!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account=(
            self.account
            if hasattr(self, "account")
            else None
        )
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _reference=(
            self.reference
            if hasattr(self, "reference")
            else None
        )
        _mtype=self.mtype
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account={_account!s}, "
            f"amount={_amount!s}, "
            f"description={_description!s}, "
            f"reference={_reference!s}, "
            f"mtype={_mtype!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
