"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Status14Enum(object):
    """Implementation of the 'Status14' enum.

    The current status of the grant. Possible values: **Pending**, **Active**,
    **Repaid**, **WrittenOff**, **Failed**, **Revoked**.

    Attributes:
        PENDING: The enum member of type str.
        ACTIVE: The enum member of type str.
        REPAID: The enum member of type str.
        FAILED: The enum member of type str.
        WRITTENOFF: The enum member of type str.
        REVOKED: The enum member of type str.

    """

    PENDING = "Pending"

    ACTIVE = "Active"

    REPAID = "Repaid"

    FAILED = "Failed"

    WRITTENOFF = "WrittenOff"

    REVOKED = "Revoked"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
