"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class SubMerchantData2(object):
    """Implementation of the 'SubMerchantData2' model.

    Attributes:
        city (str): The city of the sub-merchant's address.
        country (str): The country/region of the sub-merchant's address, specified as
            the three-letter country code in [ISO 3166-1
            alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) format.
        display_name (str): The name of the sub-merchant as it should appear on the
            display of the mobile device during transactions.
        email (str): The email address of the sub-merchant. Required for American
            Express.
        id (str): Your unique identifier of the sub-merchant.
        mcc (str): The sub-merchant's four-digit Merchant Category Code (MCC). This
            parameter is used to correctly route the transaction.
        name (str): The name of the sub-merchant.
        phone_number (str): The phone number of the sub-merchant. Required for
            American Express.
        postal_code (str): The postal code of the sub-merchant's address, without
            dashes.
        state (str): The state code of the sub-merchant's address, if applicable for
            the country or region.
        street (str): The street name and house number of the sub-merchant's address.
        tax_id (str): The tax ID of the sub-merchant. Required only in Brazil and for
            Cartes Bancaires in France. For Brazil, this is the 11-digit CPF or
            14-digit CNPJ. For France, this is the SIRET, with a maximum of 14 digits.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "display_name": "displayName",
        "id": "id",
        "mcc": "mcc",
        "name": "name",
        "city": "city",
        "country": "country",
        "email": "email",
        "phone_number": "phoneNumber",
        "postal_code": "postalCode",
        "state": "state",
        "street": "street",
        "tax_id": "taxId",
    }

    _optionals = [
        "city",
        "country",
        "email",
        "phone_number",
        "postal_code",
        "state",
        "street",
        "tax_id",
    ]

    def __init__(
        self,
        display_name=None,
        id=None,
        mcc=None,
        name=None,
        city=APIHelper.SKIP,
        country=APIHelper.SKIP,
        email=APIHelper.SKIP,
        phone_number=APIHelper.SKIP,
        postal_code=APIHelper.SKIP,
        state=APIHelper.SKIP,
        street=APIHelper.SKIP,
        tax_id=APIHelper.SKIP):
        """Initialize a SubMerchantData2 instance."""
        # Initialize members of the class
        if city is not APIHelper.SKIP:
            self.city = city
        if country is not APIHelper.SKIP:
            self.country = country
        self.display_name = display_name
        if email is not APIHelper.SKIP:
            self.email = email
        self.id = id
        self.mcc = mcc
        self.name = name
        if phone_number is not APIHelper.SKIP:
            self.phone_number = phone_number
        if postal_code is not APIHelper.SKIP:
            self.postal_code = postal_code
        if state is not APIHelper.SKIP:
            self.state = state
        if street is not APIHelper.SKIP:
            self.street = street
        if tax_id is not APIHelper.SKIP:
            self.tax_id = tax_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        display_name =\
            dictionary.get("displayName")\
            if dictionary.get("displayName")\
                else None
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        mcc =\
            dictionary.get("mcc")\
            if dictionary.get("mcc")\
                else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        city =\
            dictionary.get("city")\
            if dictionary.get("city")\
                else APIHelper.SKIP
        country =\
            dictionary.get("country")\
            if dictionary.get("country")\
                else APIHelper.SKIP
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else APIHelper.SKIP
        phone_number =\
            dictionary.get("phoneNumber")\
            if dictionary.get("phoneNumber")\
                else APIHelper.SKIP
        postal_code =\
            dictionary.get("postalCode")\
            if dictionary.get("postalCode")\
                else APIHelper.SKIP
        state =\
            dictionary.get("state")\
            if dictionary.get("state")\
                else APIHelper.SKIP
        street =\
            dictionary.get("street")\
            if dictionary.get("street")\
                else APIHelper.SKIP
        tax_id =\
            dictionary.get("taxId")\
            if dictionary.get("taxId")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(display_name,
                   id,
                   mcc,
                   name,
                   city,
                   country,
                   email,
                   phone_number,
                   postal_code,
                   state,
                   street,
                   tax_id)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _city=(
            self.city
            if hasattr(self, "city")
            else None
        )
        _country=(
            self.country
            if hasattr(self, "country")
            else None
        )
        _display_name=self.display_name
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _id=self.id
        _mcc=self.mcc
        _name=self.name
        _phone_number=(
            self.phone_number
            if hasattr(self, "phone_number")
            else None
        )
        _postal_code=(
            self.postal_code
            if hasattr(self, "postal_code")
            else None
        )
        _state=(
            self.state
            if hasattr(self, "state")
            else None
        )
        _street=(
            self.street
            if hasattr(self, "street")
            else None
        )
        _tax_id=(
            self.tax_id
            if hasattr(self, "tax_id")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"city={_city!r}, "
            f"country={_country!r}, "
            f"display_name={_display_name!r}, "
            f"email={_email!r}, "
            f"id={_id!r}, "
            f"mcc={_mcc!r}, "
            f"name={_name!r}, "
            f"phone_number={_phone_number!r}, "
            f"postal_code={_postal_code!r}, "
            f"state={_state!r}, "
            f"street={_street!r}, "
            f"tax_id={_tax_id!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _city=(
            self.city
            if hasattr(self, "city")
            else None
        )
        _country=(
            self.country
            if hasattr(self, "country")
            else None
        )
        _display_name=self.display_name
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _id=self.id
        _mcc=self.mcc
        _name=self.name
        _phone_number=(
            self.phone_number
            if hasattr(self, "phone_number")
            else None
        )
        _postal_code=(
            self.postal_code
            if hasattr(self, "postal_code")
            else None
        )
        _state=(
            self.state
            if hasattr(self, "state")
            else None
        )
        _street=(
            self.street
            if hasattr(self, "street")
            else None
        )
        _tax_id=(
            self.tax_id
            if hasattr(self, "tax_id")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"city={_city!s}, "
            f"country={_country!s}, "
            f"display_name={_display_name!s}, "
            f"email={_email!s}, "
            f"id={_id!s}, "
            f"mcc={_mcc!s}, "
            f"name={_name!s}, "
            f"phone_number={_phone_number!s}, "
            f"postal_code={_postal_code!s}, "
            f"state={_state!s}, "
            f"street={_street!s}, "
            f"tax_id={_tax_id!s}, "
            f")"
        )
