"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class SuspendAccountHolderRequest(object):
    """Implementation of the 'SuspendAccountHolderRequest' model.

    Attributes:
        account_holder_code (str): The code of the account holder to be suspended.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_holder_code": "accountHolderCode",
    }

    def __init__(
        self,
        account_holder_code=None):
        """Initialize a SuspendAccountHolderRequest instance."""
        # Initialize members of the class
        self.account_holder_code = account_holder_code

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_holder_code =\
            dictionary.get("accountHolderCode")\
            if dictionary.get("accountHolderCode")\
                else None

        # Return an object of this model
        return cls(account_holder_code)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_holder_code=self.account_holder_code
        return (
            f"{self.__class__.__name__}("
            f"account_holder_code={_account_holder_code!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_holder_code=self.account_holder_code
        return (
            f"{self.__class__.__name__}("
            f"account_holder_code={_account_holder_code!s}, "
            f")"
        )
