"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class TaxReportingClassification(object):
    """Implementation of the 'TaxReportingClassification' model.

    Attributes:
        business_type (BusinessType): The model property of type BusinessType.
        financial_institution_number (str): The Global Intermediary Identification
            Number (GIIN) required for FATCA. Only required if the organization is a
            US financial institution and the `businessType` is
            **financialInstitution**.
        main_source_of_income (MainSourceOfIncome): The model property of type
            MainSourceOfIncome.
        mtype (Type151): The model property of type Type151.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "business_type": "businessType",
        "financial_institution_number": "financialInstitutionNumber",
        "main_source_of_income": "mainSourceOfIncome",
        "mtype": "type",
    }

    _optionals = [
        "business_type",
        "financial_institution_number",
        "main_source_of_income",
        "mtype",
    ]

    def __init__(
        self,
        business_type=APIHelper.SKIP,
        financial_institution_number=APIHelper.SKIP,
        main_source_of_income=APIHelper.SKIP,
        mtype=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a TaxReportingClassification instance."""
        # Initialize members of the class
        if business_type is not APIHelper.SKIP:
            self.business_type = business_type
        if financial_institution_number is not APIHelper.SKIP:
            self.financial_institution_number = financial_institution_number
        if main_source_of_income is not APIHelper.SKIP:
            self.main_source_of_income = main_source_of_income
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        business_type =\
            dictionary.get("businessType")\
            if dictionary.get("businessType")\
                else APIHelper.SKIP
        financial_institution_number =\
            dictionary.get("financialInstitutionNumber")\
            if dictionary.get("financialInstitutionNumber")\
                else APIHelper.SKIP
        main_source_of_income =\
            dictionary.get("mainSourceOfIncome")\
            if dictionary.get("mainSourceOfIncome")\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(business_type,
                   financial_institution_number,
                   main_source_of_income,
                   mtype,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _business_type=(
            self.business_type
            if hasattr(self, "business_type")
            else None
        )
        _financial_institution_number=(
            self.financial_institution_number
            if hasattr(self, "financial_institution_number")
            else None
        )
        _main_source_of_income=(
            self.main_source_of_income
            if hasattr(self, "main_source_of_income")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"business_type={_business_type!r}, "
            f"financial_institution_number={_financial_institution_number!r}, "
            f"main_source_of_income={_main_source_of_income!r}, "
            f"mtype={_mtype!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _business_type=(
            self.business_type
            if hasattr(self, "business_type")
            else None
        )
        _financial_institution_number=(
            self.financial_institution_number
            if hasattr(self, "financial_institution_number")
            else None
        )
        _main_source_of_income=(
            self.main_source_of_income
            if hasattr(self, "main_source_of_income")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"business_type={_business_type!s}, "
            f"financial_institution_number={_financial_institution_number!s}, "
            f"main_source_of_income={_main_source_of_income!s}, "
            f"mtype={_mtype!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
