"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class TerminalReassignmentRequest(object):
    """Implementation of the 'TerminalReassignmentRequest' model.

    Attributes:
        company_id (str): The unique identifier of the company account to which the
            terminal is reassigned.
        inventory (bool): Must be specified when reassigning terminals to a merchant
            account:  - If set to **true**, reassigns terminals to the inventory of
            the merchant account and the terminals cannot process transactions.  - If
            set to **false**, reassigns terminals directly to the merchant account
            and the terminals can process transactions.
        merchant_id (str): The unique identifier of the merchant account to which the
            terminal is reassigned. When reassigning terminals to a merchant account,
            you must specify the `inventory` field.
        store_id (str): The unique identifier of the store to which the terminal is
            reassigned.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "company_id": "companyId",
        "inventory": "inventory",
        "merchant_id": "merchantId",
        "store_id": "storeId",
    }

    _optionals = [
        "company_id",
        "inventory",
        "merchant_id",
        "store_id",
    ]

    def __init__(
        self,
        company_id=APIHelper.SKIP,
        inventory=APIHelper.SKIP,
        merchant_id=APIHelper.SKIP,
        store_id=APIHelper.SKIP):
        """Initialize a TerminalReassignmentRequest instance."""
        # Initialize members of the class
        if company_id is not APIHelper.SKIP:
            self.company_id = company_id
        if inventory is not APIHelper.SKIP:
            self.inventory = inventory
        if merchant_id is not APIHelper.SKIP:
            self.merchant_id = merchant_id
        if store_id is not APIHelper.SKIP:
            self.store_id = store_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        company_id =\
            dictionary.get("companyId")\
            if dictionary.get("companyId")\
                else APIHelper.SKIP
        inventory =\
            dictionary.get("inventory")\
            if "inventory" in dictionary.keys()\
                else APIHelper.SKIP
        merchant_id =\
            dictionary.get("merchantId")\
            if dictionary.get("merchantId")\
                else APIHelper.SKIP
        store_id =\
            dictionary.get("storeId")\
            if dictionary.get("storeId")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(company_id,
                   inventory,
                   merchant_id,
                   store_id)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _company_id=(
            self.company_id
            if hasattr(self, "company_id")
            else None
        )
        _inventory=(
            self.inventory
            if hasattr(self, "inventory")
            else None
        )
        _merchant_id=(
            self.merchant_id
            if hasattr(self, "merchant_id")
            else None
        )
        _store_id=(
            self.store_id
            if hasattr(self, "store_id")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"company_id={_company_id!r}, "
            f"inventory={_inventory!r}, "
            f"merchant_id={_merchant_id!r}, "
            f"store_id={_store_id!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _company_id=(
            self.company_id
            if hasattr(self, "company_id")
            else None
        )
        _inventory=(
            self.inventory
            if hasattr(self, "inventory")
            else None
        )
        _merchant_id=(
            self.merchant_id
            if hasattr(self, "merchant_id")
            else None
        )
        _store_id=(
            self.store_id
            if hasattr(self, "store_id")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"company_id={_company_id!s}, "
            f"inventory={_inventory!s}, "
            f"merchant_id={_merchant_id!s}, "
            f"store_id={_store_id!s}, "
            f")"
        )
