"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.terminal_connectivity_bluetooth import (
    TerminalConnectivityBluetooth,
)
from adyen.models.terminal_connectivity_cellular import (
    TerminalConnectivityCellular,
)
from adyen.models.terminal_connectivity_ethernet import (
    TerminalConnectivityEthernet,
)
from adyen.models.terminal_connectivity_wifi import (
    TerminalConnectivityWifi,
)


class TerminalConnectivity2(object):
    """Implementation of the 'TerminalConnectivity2' model.

    Information about bluetooth, cellular, ethernet and wifi connectivity for the
    terminal.

    Attributes:
        bluetooth (TerminalConnectivityBluetooth): The model property of type
            TerminalConnectivityBluetooth.
        cellular (TerminalConnectivityCellular): The model property of type
            TerminalConnectivityCellular.
        ethernet (TerminalConnectivityEthernet): The model property of type
            TerminalConnectivityEthernet.
        wifi (TerminalConnectivityWifi): The model property of type
            TerminalConnectivityWifi.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "bluetooth": "bluetooth",
        "cellular": "cellular",
        "ethernet": "ethernet",
        "wifi": "wifi",
    }

    _optionals = [
        "bluetooth",
        "cellular",
        "ethernet",
        "wifi",
    ]

    def __init__(
        self,
        bluetooth=APIHelper.SKIP,
        cellular=APIHelper.SKIP,
        ethernet=APIHelper.SKIP,
        wifi=APIHelper.SKIP):
        """Initialize a TerminalConnectivity2 instance."""
        # Initialize members of the class
        if bluetooth is not APIHelper.SKIP:
            self.bluetooth = bluetooth
        if cellular is not APIHelper.SKIP:
            self.cellular = cellular
        if ethernet is not APIHelper.SKIP:
            self.ethernet = ethernet
        if wifi is not APIHelper.SKIP:
            self.wifi = wifi

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        bluetooth =\
            TerminalConnectivityBluetooth.from_dictionary(
                dictionary.get("bluetooth"))\
                if "bluetooth" in dictionary.keys()\
                else APIHelper.SKIP
        cellular =\
            TerminalConnectivityCellular.from_dictionary(
                dictionary.get("cellular"))\
                if "cellular" in dictionary.keys()\
                else APIHelper.SKIP
        ethernet =\
            TerminalConnectivityEthernet.from_dictionary(
                dictionary.get("ethernet"))\
                if "ethernet" in dictionary.keys()\
                else APIHelper.SKIP
        wifi =\
            TerminalConnectivityWifi.from_dictionary(
                dictionary.get("wifi"))\
                if "wifi" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(bluetooth,
                   cellular,
                   ethernet,
                   wifi)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _bluetooth=(
            self.bluetooth
            if hasattr(self, "bluetooth")
            else None
        )
        _cellular=(
            self.cellular
            if hasattr(self, "cellular")
            else None
        )
        _ethernet=(
            self.ethernet
            if hasattr(self, "ethernet")
            else None
        )
        _wifi=(
            self.wifi
            if hasattr(self, "wifi")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"bluetooth={_bluetooth!r}, "
            f"cellular={_cellular!r}, "
            f"ethernet={_ethernet!r}, "
            f"wifi={_wifi!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _bluetooth=(
            self.bluetooth
            if hasattr(self, "bluetooth")
            else None
        )
        _cellular=(
            self.cellular
            if hasattr(self, "cellular")
            else None
        )
        _ethernet=(
            self.ethernet
            if hasattr(self, "ethernet")
            else None
        )
        _wifi=(
            self.wifi
            if hasattr(self, "wifi")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"bluetooth={_bluetooth!s}, "
            f"cellular={_cellular!s}, "
            f"ethernet={_ethernet!s}, "
            f"wifi={_wifi!s}, "
            f")"
        )
