"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class TerminalConnectivityCellular(object):
    """Implementation of the 'TerminalConnectivityCellular' model.

    Attributes:
        iccid (str): The integrated circuit card identifier (ICCID) of the primary
            SIM card in the terminal.
        iccid_2 (str): The integrated circuit card identifier (ICCID) of the
            secondary SIM card in the terminal, typically used for a [third-party SIM
            card](https://docs.adyen.com/point-of-sale/design-your-integration/network
            -and-connectivity/cellular-failover/#using-a-third-party-sim-card).
        status (Status32): The model property of type Status32.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "iccid": "iccid",
        "iccid_2": "iccid2",
        "status": "status",
    }

    _optionals = [
        "iccid",
        "iccid_2",
        "status",
    ]

    def __init__(
        self,
        iccid=APIHelper.SKIP,
        iccid_2=APIHelper.SKIP,
        status=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a TerminalConnectivityCellular instance."""
        # Initialize members of the class
        if iccid is not APIHelper.SKIP:
            self.iccid = iccid
        if iccid_2 is not APIHelper.SKIP:
            self.iccid_2 = iccid_2
        if status is not APIHelper.SKIP:
            self.status = status

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        iccid =\
            dictionary.get("iccid")\
            if dictionary.get("iccid")\
                else APIHelper.SKIP
        iccid_2 =\
            dictionary.get("iccid2")\
            if dictionary.get("iccid2")\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(iccid,
                   iccid_2,
                   status,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _iccid=(
            self.iccid
            if hasattr(self, "iccid")
            else None
        )
        _iccid_2=(
            self.iccid_2
            if hasattr(self, "iccid_2")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"iccid={_iccid!r}, "
            f"iccid_2={_iccid_2!r}, "
            f"status={_status!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _iccid=(
            self.iccid
            if hasattr(self, "iccid")
            else None
        )
        _iccid_2=(
            self.iccid_2
            if hasattr(self, "iccid_2")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"iccid={_iccid!s}, "
            f"iccid_2={_iccid_2!s}, "
            f"status={_status!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
