"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class ThreeDSecureData3(object):
    """Implementation of the 'ThreeDSecureData3' model.

    Authentication data from a [merchant plug-in
    (MPI)](https://en.wikipedia.org/wiki/Merchant_plug-in) like Mastercard
    SecureCode, Visa Secure, or Cartes Bancaires. Required for cardholder-initiated
    transaction (CIT) adjustments.

    Attributes:
        authentication_response (AuthenticationResponseEnum): In 3D Secure 2, this is
            the `transStatus` from the challenge result. If the transaction was
            frictionless, omit this parameter.
        cavv (str): The cardholder authentication value (base64 encoded, 20 bytes in
            a decoded form).
        cavv_algorithm (str): The CAVV algorithm used. Include this only for 3D
            Secure 1.
        challenge_cancel (ChallengeCancelEnum): Indicator informing the Access
            Control Server (ACS) and the Directory Server (DS) that the
            authentication has been cancelled. For possible values, refer to [3D
            Secure API
            reference](https://docs.adyen.com/online-payments/3d-secure/api-reference#
            mpidata).
        directory_response (DirectoryResponseEnum): In 3D Secure 2, this is the
            `transStatus` from the `ARes`.
        ds_trans_id (str): Supported for 3D Secure 2. The unique transaction
            identifier assigned by the Directory Server (DS) to identify a single
            transaction.
        eci (str): The electronic commerce indicator.
        risk_score (str): Risk score calculated by Directory Server (DS). Required
            for Cartes Bancaires integrations.
        three_ds_version (str): The version of the 3D Secure protocol.
        token_authentication_verification_value (str): Network token authentication
            verification value (TAVV). The network token cryptogram.
        trans_status_reason (str): Provides information on why the `transStatus`
            field has the specified value. For possible values, refer to [our
            docs](https://docs.adyen.com/online-payments/3d-secure/api-reference#possi
            ble-transstatusreason-values).
        xid (str): Supported for 3D Secure 1. The transaction identifier
            (Base64-encoded, 20 bytes in a decoded form).

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "authentication_response": "authenticationResponse",
        "cavv": "cavv",
        "cavv_algorithm": "cavvAlgorithm",
        "challenge_cancel": "challengeCancel",
        "directory_response": "directoryResponse",
        "ds_trans_id": "dsTransID",
        "eci": "eci",
        "risk_score": "riskScore",
        "three_ds_version": "threeDSVersion",
        "token_authentication_verification_value":
            "tokenAuthenticationVerificationValue",
        "trans_status_reason": "transStatusReason",
        "xid": "xid",
    }

    _optionals = [
        "authentication_response",
        "cavv",
        "cavv_algorithm",
        "challenge_cancel",
        "directory_response",
        "ds_trans_id",
        "eci",
        "risk_score",
        "three_ds_version",
        "token_authentication_verification_value",
        "trans_status_reason",
        "xid",
    ]

    def __init__(
        self,
        authentication_response=APIHelper.SKIP,
        cavv=APIHelper.SKIP,
        cavv_algorithm=APIHelper.SKIP,
        challenge_cancel=APIHelper.SKIP,
        directory_response=APIHelper.SKIP,
        ds_trans_id=APIHelper.SKIP,
        eci=APIHelper.SKIP,
        risk_score=APIHelper.SKIP,
        three_ds_version=APIHelper.SKIP,
        token_authentication_verification_value=APIHelper.SKIP,
        trans_status_reason=APIHelper.SKIP,
        xid=APIHelper.SKIP):
        """Initialize a ThreeDSecureData3 instance."""
        # Initialize members of the class
        if authentication_response is not APIHelper.SKIP:
            self.authentication_response = authentication_response
        if cavv is not APIHelper.SKIP:
            self.cavv = cavv
        if cavv_algorithm is not APIHelper.SKIP:
            self.cavv_algorithm = cavv_algorithm
        if challenge_cancel is not APIHelper.SKIP:
            self.challenge_cancel = challenge_cancel
        if directory_response is not APIHelper.SKIP:
            self.directory_response = directory_response
        if ds_trans_id is not APIHelper.SKIP:
            self.ds_trans_id = ds_trans_id
        if eci is not APIHelper.SKIP:
            self.eci = eci
        if risk_score is not APIHelper.SKIP:
            self.risk_score = risk_score
        if three_ds_version is not APIHelper.SKIP:
            self.three_ds_version = three_ds_version
        if token_authentication_verification_value is not APIHelper.SKIP:
            self.token_authentication_verification_value =\
                 token_authentication_verification_value
        if trans_status_reason is not APIHelper.SKIP:
            self.trans_status_reason = trans_status_reason
        if xid is not APIHelper.SKIP:
            self.xid = xid

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        authentication_response =\
            dictionary.get("authenticationResponse")\
            if dictionary.get("authenticationResponse")\
                else APIHelper.SKIP
        cavv =\
            dictionary.get("cavv")\
            if dictionary.get("cavv")\
                else APIHelper.SKIP
        cavv_algorithm =\
            dictionary.get("cavvAlgorithm")\
            if dictionary.get("cavvAlgorithm")\
                else APIHelper.SKIP
        challenge_cancel =\
            dictionary.get("challengeCancel")\
            if dictionary.get("challengeCancel")\
                else APIHelper.SKIP
        directory_response =\
            dictionary.get("directoryResponse")\
            if dictionary.get("directoryResponse")\
                else APIHelper.SKIP
        ds_trans_id =\
            dictionary.get("dsTransID")\
            if dictionary.get("dsTransID")\
                else APIHelper.SKIP
        eci =\
            dictionary.get("eci")\
            if dictionary.get("eci")\
                else APIHelper.SKIP
        risk_score =\
            dictionary.get("riskScore")\
            if dictionary.get("riskScore")\
                else APIHelper.SKIP
        three_ds_version =\
            dictionary.get("threeDSVersion")\
            if dictionary.get("threeDSVersion")\
                else APIHelper.SKIP
        token_authentication_verification_value =\
            dictionary.get("tokenAuthenticationVerificationValue")\
            if dictionary.get("tokenAuthenticationVerificationValue")\
                else APIHelper.SKIP
        trans_status_reason =\
            dictionary.get("transStatusReason")\
            if dictionary.get("transStatusReason")\
                else APIHelper.SKIP
        xid =\
            dictionary.get("xid")\
            if dictionary.get("xid")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(authentication_response,
                   cavv,
                   cavv_algorithm,
                   challenge_cancel,
                   directory_response,
                   ds_trans_id,
                   eci,
                   risk_score,
                   three_ds_version,
                   token_authentication_verification_value,
                   trans_status_reason,
                   xid)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _authentication_response=(
            self.authentication_response
            if hasattr(self, "authentication_response")
            else None
        )
        _cavv=(
            self.cavv
            if hasattr(self, "cavv")
            else None
        )
        _cavv_algorithm=(
            self.cavv_algorithm
            if hasattr(self, "cavv_algorithm")
            else None
        )
        _challenge_cancel=(
            self.challenge_cancel
            if hasattr(self, "challenge_cancel")
            else None
        )
        _directory_response=(
            self.directory_response
            if hasattr(self, "directory_response")
            else None
        )
        _ds_trans_id=(
            self.ds_trans_id
            if hasattr(self, "ds_trans_id")
            else None
        )
        _eci=(
            self.eci
            if hasattr(self, "eci")
            else None
        )
        _risk_score=(
            self.risk_score
            if hasattr(self, "risk_score")
            else None
        )
        _three_ds_version=(
            self.three_ds_version
            if hasattr(self, "three_ds_version")
            else None
        )
        _token_authentication_verification_value=(
            self.token_authentication_verification_value
            if hasattr(self, "token_authentication_verification_value")
            else None
        )
        _trans_status_reason=(
            self.trans_status_reason
            if hasattr(self, "trans_status_reason")
            else None
        )
        _xid=(
            self.xid
            if hasattr(self, "xid")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"authentication_response={_authentication_response!r}, "
            f"cavv={_cavv!r}, "
            f"cavv_algorithm={_cavv_algorithm!r}, "
            f"challenge_cancel={_challenge_cancel!r}, "
            f"directory_response={_directory_response!r}, "
            f"ds_trans_id={_ds_trans_id!r}, "
            f"eci={_eci!r}, "
            f"risk_score={_risk_score!r}, "
            f"three_ds_version={_three_ds_version!r}, "
            f"token_authentication_verification_value={_token_authentication_verification_value!r}, "
            f"trans_status_reason={_trans_status_reason!r}, "
            f"xid={_xid!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _authentication_response=(
            self.authentication_response
            if hasattr(self, "authentication_response")
            else None
        )
        _cavv=(
            self.cavv
            if hasattr(self, "cavv")
            else None
        )
        _cavv_algorithm=(
            self.cavv_algorithm
            if hasattr(self, "cavv_algorithm")
            else None
        )
        _challenge_cancel=(
            self.challenge_cancel
            if hasattr(self, "challenge_cancel")
            else None
        )
        _directory_response=(
            self.directory_response
            if hasattr(self, "directory_response")
            else None
        )
        _ds_trans_id=(
            self.ds_trans_id
            if hasattr(self, "ds_trans_id")
            else None
        )
        _eci=(
            self.eci
            if hasattr(self, "eci")
            else None
        )
        _risk_score=(
            self.risk_score
            if hasattr(self, "risk_score")
            else None
        )
        _three_ds_version=(
            self.three_ds_version
            if hasattr(self, "three_ds_version")
            else None
        )
        _token_authentication_verification_value=(
            self.token_authentication_verification_value
            if hasattr(self, "token_authentication_verification_value")
            else None
        )
        _trans_status_reason=(
            self.trans_status_reason
            if hasattr(self, "trans_status_reason")
            else None
        )
        _xid=(
            self.xid
            if hasattr(self, "xid")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"authentication_response={_authentication_response!s}, "
            f"cavv={_cavv!s}, "
            f"cavv_algorithm={_cavv_algorithm!s}, "
            f"challenge_cancel={_challenge_cancel!s}, "
            f"directory_response={_directory_response!s}, "
            f"ds_trans_id={_ds_trans_id!s}, "
            f"eci={_eci!s}, "
            f"risk_score={_risk_score!s}, "
            f"three_ds_version={_three_ds_version!s}, "
            f"token_authentication_verification_value={_token_authentication_verification_value!s}, "
            f"trans_status_reason={_trans_status_reason!s}, "
            f"xid={_xid!s}, "
            f")"
        )
