"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.amount_5 import Amount5
from adyen.models.payment_instrument_2 import (
    PaymentInstrument2,
)
from adyen.models.resource_reference import (
    ResourceReference,
)
from adyen.models.transfer_view import TransferView


class Transaction1(object):
    """Implementation of the 'Transaction1' model.

    Attributes:
        account_holder (ResourceReference): The model property of type
            ResourceReference.
        amount (Amount5): The model property of type Amount5.
        balance_account (ResourceReference): The model property of type
            ResourceReference.
        balance_platform (str): The unique identifier of the balance platform.
        booking_date (datetime): The date the transaction was booked into the balance
            account.
        creation_date (datetime): The date and time when the event was triggered, in
            ISO 8601 extended format. For example, **2025-03-19T10:15:30+01:00**.
        description (str): The `description` from the `/transfers` request.
        id (str): The unique identifier of the transaction.
        payment_instrument (PaymentInstrument2): The model property of type
            PaymentInstrument2.
        reference_for_beneficiary (str): The reference sent to or received from the
            counterparty.  * For outgoing funds, this is the
            [`referenceForBeneficiary`](https://docs.adyen.com/api-explorer/#/transfer
            s/latest/post/transfers__resParam_referenceForBeneficiary) from the
            [`/transfers`](https://docs.adyen.com/api-explorer/#/transfers/latest/post
            /transfers__reqParam_referenceForBeneficiary) request.   * For incoming
            funds, this is the reference from the sender.
        status (Status71): The model property of type Status71.
        transfer (TransferView): The model property of type TransferView.
        value_date (datetime): The date the transfer amount becomes available in the
            balance account.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_holder": "accountHolder",
        "amount": "amount",
        "balance_account": "balanceAccount",
        "balance_platform": "balancePlatform",
        "booking_date": "bookingDate",
        "id": "id",
        "status": "status",
        "value_date": "valueDate",
        "creation_date": "creationDate",
        "description": "description",
        "payment_instrument": "paymentInstrument",
        "reference_for_beneficiary": "referenceForBeneficiary",
        "transfer": "transfer",
    }

    _optionals = [
        "creation_date",
        "description",
        "payment_instrument",
        "reference_for_beneficiary",
        "transfer",
    ]

    def __init__(
        self,
        account_holder=None,
        amount=None,
        balance_account=None,
        balance_platform=None,
        booking_date=None,
        id=None,
        status=None,
        value_date=None,
        creation_date=APIHelper.SKIP,
        description=APIHelper.SKIP,
        payment_instrument=APIHelper.SKIP,
        reference_for_beneficiary=APIHelper.SKIP,
        transfer=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Transaction1 instance."""
        # Initialize members of the class
        self.account_holder = account_holder
        self.amount = amount
        self.balance_account = balance_account
        self.balance_platform = balance_platform
        self.booking_date =\
             APIHelper.apply_datetime_converter(
            booking_date, APIHelper.RFC3339DateTime)\
             if booking_date else None
        if creation_date is not APIHelper.SKIP:
            self.creation_date =\
                 APIHelper.apply_datetime_converter(
                creation_date, APIHelper.RFC3339DateTime)\
                 if creation_date else None
        if description is not APIHelper.SKIP:
            self.description = description
        self.id = id
        if payment_instrument is not APIHelper.SKIP:
            self.payment_instrument = payment_instrument
        if reference_for_beneficiary is not APIHelper.SKIP:
            self.reference_for_beneficiary = reference_for_beneficiary
        self.status = status
        if transfer is not APIHelper.SKIP:
            self.transfer = transfer
        self.value_date =\
             APIHelper.apply_datetime_converter(
            value_date, APIHelper.RFC3339DateTime)\
             if value_date else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_holder =\
            ResourceReference.from_dictionary(
                dictionary.get("accountHolder"))\
                if dictionary.get("accountHolder") else None
        amount =\
            Amount5.from_dictionary(
                dictionary.get("amount"))\
                if dictionary.get("amount") else None
        balance_account =\
            ResourceReference.from_dictionary(
                dictionary.get("balanceAccount"))\
                if dictionary.get("balanceAccount") else None
        balance_platform =\
            dictionary.get("balancePlatform")\
            if dictionary.get("balancePlatform")\
                else None
        booking_date = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("bookingDate")).datetime\
            if dictionary.get("bookingDate") else None
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else None
        value_date = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("valueDate")).datetime\
            if dictionary.get("valueDate") else None
        creation_date = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("creationDate")).datetime\
            if dictionary.get("creationDate") else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        payment_instrument =\
            PaymentInstrument2.from_dictionary(
                dictionary.get("paymentInstrument"))\
                if "paymentInstrument" in dictionary.keys()\
                else APIHelper.SKIP
        reference_for_beneficiary =\
            dictionary.get("referenceForBeneficiary")\
            if dictionary.get("referenceForBeneficiary")\
                else APIHelper.SKIP
        transfer =\
            TransferView.from_dictionary(
                dictionary.get("transfer"))\
                if "transfer" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(account_holder,
                   amount,
                   balance_account,
                   balance_platform,
                   booking_date,
                   id,
                   status,
                   value_date,
                   creation_date,
                   description,
                   payment_instrument,
                   reference_for_beneficiary,
                   transfer,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_holder=self.account_holder
        _amount=self.amount
        _balance_account=self.balance_account
        _balance_platform=self.balance_platform
        _booking_date=self.booking_date
        _creation_date=(
            self.creation_date
            if hasattr(self, "creation_date")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _id=self.id
        _payment_instrument=(
            self.payment_instrument
            if hasattr(self, "payment_instrument")
            else None
        )
        _reference_for_beneficiary=(
            self.reference_for_beneficiary
            if hasattr(self, "reference_for_beneficiary")
            else None
        )
        _status=self.status
        _transfer=(
            self.transfer
            if hasattr(self, "transfer")
            else None
        )
        _value_date=self.value_date
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_holder={_account_holder!r}, "
            f"amount={_amount!r}, "
            f"balance_account={_balance_account!r}, "
            f"balance_platform={_balance_platform!r}, "
            f"booking_date={_booking_date!r}, "
            f"creation_date={_creation_date!r}, "
            f"description={_description!r}, "
            f"id={_id!r}, "
            f"payment_instrument={_payment_instrument!r}, "
            f"reference_for_beneficiary={_reference_for_beneficiary!r}, "
            f"status={_status!r}, "
            f"transfer={_transfer!r}, "
            f"value_date={_value_date!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_holder=self.account_holder
        _amount=self.amount
        _balance_account=self.balance_account
        _balance_platform=self.balance_platform
        _booking_date=self.booking_date
        _creation_date=(
            self.creation_date
            if hasattr(self, "creation_date")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _id=self.id
        _payment_instrument=(
            self.payment_instrument
            if hasattr(self, "payment_instrument")
            else None
        )
        _reference_for_beneficiary=(
            self.reference_for_beneficiary
            if hasattr(self, "reference_for_beneficiary")
            else None
        )
        _status=self.status
        _transfer=(
            self.transfer
            if hasattr(self, "transfer")
            else None
        )
        _value_date=self.value_date
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"account_holder={_account_holder!s}, "
            f"amount={_amount!s}, "
            f"balance_account={_balance_account!s}, "
            f"balance_platform={_balance_platform!s}, "
            f"booking_date={_booking_date!s}, "
            f"creation_date={_creation_date!s}, "
            f"description={_description!s}, "
            f"id={_id!s}, "
            f"payment_instrument={_payment_instrument!s}, "
            f"reference_for_beneficiary={_reference_for_beneficiary!s}, "
            f"status={_status!s}, "
            f"transfer={_transfer!s}, "
            f"value_date={_value_date!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
