"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class TransferRoute(object):
    """Implementation of the 'TransferRoute' model.

    Attributes:
        category (Category2Enum): The type of transfer.   Possible values:    -
            **bank**: Transfer to a [transfer
            instrument](https://docs.adyen.com/api-explorer/#/legalentity/latest/post/
            transferInstruments__resParam_id) or a bank account.
        country (str): The two-character ISO-3166-1 alpha-2 country code of the
            counterparty. For example, **US** or **NL**.
        currency (str): The three-character ISO currency code of transfer. For
            example, **USD** or **EUR**.
        priority (Priority2Enum): The priority for the bank transfer. This sets the
            speed at which the transfer is sent and the fees that you have to pay.
            Possible values:  * **regular**: For normal, low-value transactions.  *
            **fast**: A faster way to transfer funds, but the fees are higher.
            Recommended for high-priority, low-value transactions.  * **wire**: The
            fastest way to transfer funds, but this has the highest fees. Recommended
            for high-priority, high-value transactions.  * **instant**: For instant
            funds transfers within the United States and in [SEPA
            locations](https://www.ecb.europa.eu/paym/integration/retail/sepa/html/ind
            ex.en.html).  * **crossBorder**: For high-value transfers to a recipient
            in a different country.  * **internal**: For transfers to an Adyen-issued
            business bank account (by bank account number/IBAN).
        requirements (List[AdditionalBankIdentificationRequirement |
            AddressRequirement | AmountMinMaxRequirement |
            AmountNonZeroDecimalsRequirement |
            BankAccountIdentificationTypeRequirement |
            IbanAccountIdentificationRequirement | PaymentInstrumentRequirement |
            USInstantPayoutAddressRequirement | USInternationalAchAddressRequirement
            | USInternationalAchPriorityRequirement] | None): A set of rules defined
            by clearing houses and banking partners. Your transfer request must
            adhere to these rules to ensure successful initiation of transfer. Based
            on the priority, one or more requirements may be returned. Each
            requirement is defined with a `type` and `description`.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "category": "category",
        "country": "country",
        "currency": "currency",
        "priority": "priority",
        "requirements": "requirements",
    }

    _optionals = [
        "category",
        "country",
        "currency",
        "priority",
        "requirements",
    ]

    def __init__(
        self,
        category=APIHelper.SKIP,
        country=APIHelper.SKIP,
        currency=APIHelper.SKIP,
        priority=APIHelper.SKIP,
        requirements=APIHelper.SKIP):
        """Initialize a TransferRoute instance."""
        # Initialize members of the class
        if category is not APIHelper.SKIP:
            self.category = category
        if country is not APIHelper.SKIP:
            self.country = country
        if currency is not APIHelper.SKIP:
            self.currency = currency
        if priority is not APIHelper.SKIP:
            self.priority = priority
        if requirements is not APIHelper.SKIP:
            self.requirements = requirements

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from adyen.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        category =\
            dictionary.get("category")\
            if dictionary.get("category")\
                else APIHelper.SKIP
        country =\
            dictionary.get("country")\
            if dictionary.get("country")\
                else APIHelper.SKIP
        currency =\
            dictionary.get("currency")\
            if dictionary.get("currency")\
                else APIHelper.SKIP
        priority =\
            dictionary.get("priority")\
            if dictionary.get("priority")\
                else APIHelper.SKIP
        requirements = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("TransferRouteRequirements"),
            dictionary.get("requirements"),
            False)\
            if dictionary.get("requirements") is not None\
            else APIHelper.SKIP

        # Return an object of this model
        return cls(category,
                   country,
                   currency,
                   priority,
                   requirements)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _category=(
            self.category
            if hasattr(self, "category")
            else None
        )
        _country=(
            self.country
            if hasattr(self, "country")
            else None
        )
        _currency=(
            self.currency
            if hasattr(self, "currency")
            else None
        )
        _priority=(
            self.priority
            if hasattr(self, "priority")
            else None
        )
        _requirements=(
            self.requirements
            if hasattr(self, "requirements")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"category={_category!r}, "
            f"country={_country!r}, "
            f"currency={_currency!r}, "
            f"priority={_priority!r}, "
            f"requirements={_requirements!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _category=(
            self.category
            if hasattr(self, "category")
            else None
        )
        _country=(
            self.country
            if hasattr(self, "country")
            else None
        )
        _currency=(
            self.currency
            if hasattr(self, "currency")
            else None
        )
        _priority=(
            self.priority
            if hasattr(self, "priority")
            else None
        )
        _requirements=(
            self.requirements
            if hasattr(self, "requirements")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"category={_category!s}, "
            f"country={_country!s}, "
            f"currency={_currency!s}, "
            f"priority={_priority!s}, "
            f"requirements={_requirements!s}, "
            f")"
        )
