"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper
from adyen.models.schedule_2 import Schedule2
from adyen.models.threshold_2 import Threshold2


class Trigger1(object):
    """Implementation of the 'Trigger1' model.

    The condition that triggers the top-up. This can be a recurring schedule or a
    minimum balance threshold.

    Attributes:
        schedule (Schedule2): The model property of type Schedule2.
        threshold (Threshold2): The model property of type Threshold2.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "threshold": "threshold",
        "schedule": "schedule",
    }

    _optionals = [
        "schedule",
    ]

    def __init__(
        self,
        threshold=None,
        schedule=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Trigger1 instance."""
        # Initialize members of the class
        if schedule is not APIHelper.SKIP:
            self.schedule = schedule
        self.threshold = threshold

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        threshold =\
            Threshold2.from_dictionary(
                dictionary.get("threshold"))\
                if dictionary.get("threshold") else None
        schedule =\
            Schedule2.from_dictionary(
                dictionary.get("schedule"))\
                if "schedule" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(threshold,
                   schedule,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _schedule=(
            self.schedule
            if hasattr(self, "schedule")
            else None
        )
        _threshold=self.threshold
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"schedule={_schedule!r}, "
            f"threshold={_threshold!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _schedule=(
            self.schedule
            if hasattr(self, "schedule")
            else None
        )
        _threshold=self.threshold
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"schedule={_schedule!s}, "
            f"threshold={_threshold!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
