"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Type211Enum(object):
    """Implementation of the 'Type211' enum.

    The type of check.
    Possible values:
     * **BANK_ACCOUNT_VERIFICATION**: Used in v5 and earlier. Replaced by
    **PAYOUT_METHOD_VERIFICATION** in v6 and later.
     * **COMPANY_VERIFICATION**
      * **CARD_VERIFICATION**
    * **IDENTITY_VERIFICATION**
    * **LEGAL_ARRANGEMENT_VERIFICATION**
    * **NONPROFIT_VERIFICATION**
     * **PASSPORT_VERIFICATION**
    * **PAYOUT_METHOD_VERIFICATION**: Used in v6 and later.
    * **PCI_VERIFICATION**

    Attributes:
        BANK_ACCOUNT_VERIFICATION: The enum member of type str.
        CARD_VERIFICATION: The enum member of type str.
        COMPANY_VERIFICATION: The enum member of type str.
        IDENTITY_VERIFICATION: The enum member of type str.
        LEGAL_ARRANGEMENT_VERIFICATION: The enum member of type str.
        NONPROFIT_VERIFICATION: The enum member of type str.
        PASSPORT_VERIFICATION: The enum member of type str.
        PAYOUT_METHOD_VERIFICATION: The enum member of type str.
        PCI_VERIFICATION: The enum member of type str.

    """

    BANK_ACCOUNT_VERIFICATION = "BANK_ACCOUNT_VERIFICATION"

    CARD_VERIFICATION = "CARD_VERIFICATION"

    COMPANY_VERIFICATION = "COMPANY_VERIFICATION"

    IDENTITY_VERIFICATION = "IDENTITY_VERIFICATION"

    LEGAL_ARRANGEMENT_VERIFICATION = "LEGAL_ARRANGEMENT_VERIFICATION"

    NONPROFIT_VERIFICATION = "NONPROFIT_VERIFICATION"

    PASSPORT_VERIFICATION = "PASSPORT_VERIFICATION"

    PAYOUT_METHOD_VERIFICATION = "PAYOUT_METHOD_VERIFICATION"

    PCI_VERIFICATION = "PCI_VERIFICATION"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
