"""adyen.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from adyen.api_helper import APIHelper


class WeChatPayResponseInfo2(object):
    """Implementation of the 'WeChatPayResponseInfo2' model.

    **wechatpay** details

    Attributes:
        contact_person_name (str): The name of the contact person from merchant
            support.
        email (str): The email address of merchant support.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "contact_person_name": "contactPersonName",
        "email": "email",
    }

    _optionals = [
        "contact_person_name",
        "email",
    ]

    def __init__(
        self,
        contact_person_name=APIHelper.SKIP,
        email=APIHelper.SKIP):
        """Initialize a WeChatPayResponseInfo2 instance."""
        # Initialize members of the class
        if contact_person_name is not APIHelper.SKIP:
            self.contact_person_name = contact_person_name
        if email is not APIHelper.SKIP:
            self.email = email

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        contact_person_name =\
            dictionary.get("contactPersonName")\
            if dictionary.get("contactPersonName")\
                else APIHelper.SKIP
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(contact_person_name,
                   email)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _contact_person_name=(
            self.contact_person_name
            if hasattr(self, "contact_person_name")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"contact_person_name={_contact_person_name!r}, "
            f"email={_email!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _contact_person_name=(
            self.contact_person_name
            if hasattr(self, "contact_person_name")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"contact_person_name={_contact_person_name!s}, "
            f"email={_email!s}, "
            f")"
        )
